- plural/plural/recipe/console-equinix.yaml
- plural/terraform/equinix/deps.yaml
- plural/terraform/equinix/main.tf
- plural/terraform/equinix/terraform.tfvars
- plural/terraform/equinix/variables.tf
This PR adds the necessary artifacts for the console on Equinix Metal
> Equinix Metal artifacts

- assets/src/components/Installations.js
Retain applications across sessions in Console
Closes #32
> retain application across sessions

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/ingress.yaml
- plural/helm/console/values.yaml
- plural/helm/console/values.yaml.tpl
- plural/plural/recipe/console-kind.yaml
- plural/terraform/kind/deps.yaml
- plural/terraform/kind/main.tf
- plural/terraform/kind/terraform.tfvars
- plural/terraform/kind/variables.tf
Add support for deploying the console on KinD clusters.
Local linking
> Add support for KinD clusters

- plural/terraform/gcp/deps.yaml
- plural/terraform/gcp/main.tf
- plural/terraform/gcp/variables.tf
Changes to the GCP artifact for the region changes.
> changes for GCP

- assets/src/components/Console.js
- assets/src/components/graphql/users.js
When demo project is present in config, add a top banner explaining the deadline to expiration for demo projects
Fixes ENG-154
tested locally
> Add demo project banner in react

- .github/workflows/assets.yaml
- assets/.eslintrc.yml
- assets/README.md
- assets/cypress.config.ts
- assets/cypress/config/config.ts
- assets/cypress/e2e/stories/bounce.cy.ts
- assets/cypress/pages/base.ts
- assets/cypress/pages/login.ts
- assets/cypress/plugins/cy-ts-preprocessor.ts
- assets/cypress/plugins/index.ts
- assets/cypress/support/commands.ts
- assets/cypress/support/e2e.ts
- assets/cypress/support/index.ts
- assets/cypress/tsconfig.json
- assets/package.json
- assets/src/components/Login.js
- assets/src/components/Logs.js
- assets/src/components/OauthCallback.js
- assets/src/components/users/CreateInvite.js
- assets/src/components/users/EditUser.js
- assets/src/components/utils/SmoothScroller.js
- assets/src/helpers/client.js
- assets/src/helpers/hostname.js
- assets/src/setupProxy.js
- assets/yarn.lock
- bootstrap cypress configuration
- add simple story to log in to the application
- update logic for proxying API and use `http-proxy-middleware` instead of custom logic
- update README
- allow overriding API proxy URL via environment variable
I think I have tested all impacted features but I'd recommend that someone else also checks it just to be sure.
> ENG-339 Bootstrap cypress e2e

- .github/workflows/assets.yaml
- assets/.gitignore
- assets/cypress.config.ts
- assets/cypress/e2e/stories/bounce.cy.ts
As in the title
See the slack `cypress-artifacts` channel and GH actions status.
> ENG-350 - Upload cypress artifacts to slack on failure

- lib/console/graphql/plural.ex
- lib/console/plural/models.ex
- lib/console/plural/queries.ex
- plural/helm/console/Chart.yaml
- plural/helm/console/templates/secrets.yaml
Will be needed to properly message that certain recipes cannot be installed in-console
unit tests
> Allow querying restricted states on recipes

- .github/workflows/assets.yaml
> Remove node modules cache from CI

- .github/workflows/publish-cypress.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- Dockerfile
- Makefile
- renovate.json
Fixes ENG-285.
Note that it also bumps CLI version that is used. Let me know if that change needs to be reverted.
Tested manually to the point that it was possible on M1 Mac.
> ENG-285: Download CLI from GitHub releases and other container improvements

- plural/repository.yaml
Related to ENG-465.
Adds description that couldn't be added in https://github.com/pluralsh/plural-artifacts/pull/344.
> Update console description

- Dockerfile
Updates the Plural CLI used in the console to the latest version. This solves an issue we discovered in the previous release of the CLI and console that was fixed in https://github.com/pluralsh/plural-cli/pull/178.
Build container manually and test in clusters.
> update to latest CLI

- .github/workflows/pr-labels.yaml
This PR adds a workflow that requires labels
> add workflow for required labels

- Dockerfile
Updates the CLI to the latest version to fix the rollout of our Azure infrastructure update.
Tested the CLI locally
> update CLI to unblock Azure update

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
Bump the console artifact to use the latest image tag
> bump chart tag

- .tool-versions
- Dockerfile
- lib/console/deployer.ex
- lib/console/storage/git.ex
- rel/config/config.exs
This adds some outstanding fixes including:
* configurable prometheus/loki hosts
* reintroducing a more robust plural repair
* trying to make sure the storage sync is functional (likely helped by plural repair)
ensure existing tests pass
> Miscellaneous console improvements

- lib/console/deployer.ex
We currently don't do this automatically and I'm honestly not sure why.  This will be closer to the expected experience when you update configuration in the console.
manual when baking release
> Autodeploy after config update

- Dockerfile
- lib/console/commands/plural.ex
- lib/console/deployer.ex
This is a good bit more robust than the alternative, as it reduces the risk of getting tripped on a flaky unrelated app
existing tests
> Implement --from flag for installer

- Dockerfile
- assets/src/components/oidc/queries.js
Looks like the case strictness of the new version of absinthe has broken this
local
> Fix in-console oidc provider updates

- lib/console/deployer.ex
- lib/console/graphql.ex
- lib/console/graphql/plural.ex
- lib/console/graphql/resolvers/plural.ex
- lib/kube/client.ex
- lib/kube/client/base.ex
Also adds an optional commit message arg for configuration updates
existing tests
> Clean up Kube.Client

- lib/console.ex
- lib/console/configuration.ex
- lib/console/graphql/middleware/sandboxed.ex
- lib/console/graphql/users.ex
- lib/console/graphql/webhooks.ex
- rel/config/console.exs
We won't want our demo sandbox to do things that can escalate demo user perms, this middleware will prevent that
n/a
> Add Sanbox guardrails for mutations

- lib/console/commands/plural.ex
- lib/console/deployer.ex
- lib/console/graphql/plural.ex
- lib/console/graphql/resolvers/plural.ex
- lib/console/plural/context.ex
- lib/console/plural/models.ex
- lib/console/plural/queries.ex
- lib/console/plural/repositories.ex
- lib/console/services/base.ex
- lib/console/services/plural.ex
- test/console/graphql/mutations/plural_mutations_test.exs
- test/console/graphql/queries/plural_queries_test.exs
- test/console/services/plural_test.exs
This adds the stack query and install mutation to the console's api.  It also does a full oidc enablement pass which seems a tad risky but /shrug
added unit tests
> Implement stack install apis in-console

- lib/console/commands/plural.ex
- lib/console/deployer.ex
- lib/console/runbooks/action.ex
- lib/console/schema/build.ex
Basically just runs `plural destroy NAME` but with opt in for all arguments
existing tests
> Add destroy build type

- assets/src/components/OauthCallback.js
This would choke opaquely before, a proper error alert is a far better ux (we should change with redesign obviously)
tested locally
> Better oauth error handling

- Dockerfile
- lib/console/deployer.ex
- lib/console/graphql/plural.ex
- lib/console/graphql/resolvers/plural.ex
- lib/console/plural/context.ex
- lib/console/services/plural.ex
- test/console/graphql/mutations/plural_mutations_test.exs
- test/console/services/plural_test.exs
These are needed to fully validate bucket/domain uniqueness, which shouldn't be a huge deal with the graphical interface, but still worth doing.
fixed unit tests
> Add buckets/domains to stack install apis and pluralContext gql query

- .github/workflows/test.yaml
This PR pushes images built during CI tests of PRs to GHCR so we can test them more easily without creating a release.
> push pr images to ghcr for testing

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
Updates the Plural console to use the latest released image.
Local linking.
> bump helm chart version

- assets/package.json
- assets/src/components/cluster/Gauges.tsx
- assets/src/components/cluster/nodes/ClusterGauges.tsx
- assets/src/components/utils/PieChart.tsx
- assets/src/components/utils/RadialBarChart.tsx
- assets/src/components/utils/charts.tsx
- assets/yarn.lock
Mostly working, but hack to get tooltips to display in a portal does not show tooltips in correct position yet.
> WIP: Add Radial Bar Chart

- assets/package.json
- assets/src/components/Console.tsx
- assets/src/components/cluster/Gauges.tsx
- assets/src/components/cluster/nodes/ClusterGauges.tsx
- assets/src/components/cluster/nodes/NodeGraphs.tsx
- assets/src/components/utils/ChartTooltip.tsx
- assets/src/components/utils/CursorPosition.tsx
- assets/src/components/utils/PieChart.tsx
- assets/src/components/utils/RadialBarChart.tsx
- assets/src/components/utils/charts.tsx
- assets/yarn.lock
RadialBarChart now has
- Portalled tooltips (to prevent cropping or scrollbars when breaking outside of containing elements) that properly track the cursor.
- Updated styling
- Also added portalled tooltip to PieChart
> Finished RadialBarChart

- assets/src/components/cluster/TableElements.tsx
- assets/src/components/cluster/containers/ContainerShell.tsx
- assets/src/components/cluster/nodes/SaturationGraphs.tsx
- assets/src/components/cluster/pods/Pods.tsx
- assets/src/components/cluster/pods/PodsList.tsx
- assets/src/components/cluster/queries.js
- assets/src/components/terminal/Terminal.tsx
- assets/src/components/utils/RadialBarChart.tsx
- assets/src/routes/clusterRoutes.tsx
Finished pods page, updated pod terminal page
> Console improvements (Pods and terminal)

- lib/console/watchers/upgrade.ex
This needs to be 100% bulletproof as it'll eventually bring down the console if it thrashes, so just handle errors and back off if the api flakes
existing tests
> Make upgrade queue setup more robust

- assets/package.json
- assets/src/components/apps/app/oidc/UserManagement.tsx
- assets/src/components/hooks/useNavBlocker.tsx
- assets/yarn.lock
https://linear.app/pluralsh/issue/ENG-1128/add-confirmation-dialog-when-user-tries-to-leave-with-unsaved-changes
Also fixes bug where form changes were not being detected properly
> feat: ENG-1128 - Add confirmation dialog when user tries to leave with unsaved changes in OIDC config

- assets/src/components/apps/app/runbooks/runbook/RunbookStatus.tsx
https://linear.app/pluralsh/issue/ENG-1142/add-tooltip-to-runbooks-alert-chip
> feat: ENG-1142 - Add tooltip to Runbooks alert chip

- assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
- assets/src/components/apps/app/runbooks/runbook/RunbookAlert.tsx
- assets/src/components/apps/app/runbooks/runbook/RunbookAlerts.tsx
- assets/src/components/apps/app/runbooks/runbook/RunbookDisplay.tsx
Not quite finished yet, but stable enough to merge if its helpful.
> WIP: ENG-1143 Add alerts to top of Runbook page

- assets/src/components/types.js
- config/config.exs
- lib/console.ex
- lib/console/application.ex
- lib/console/clustering/bootstrapper.ex
- lib/console/clustering/connect.ex
- lib/console/commands/configuration.ex
- lib/console/commands/plural.ex
- lib/console/deployer.ex
- lib/console/deployer/dedicated.ex
- lib/console/deployer/operations.ex
- lib/console/runner/harakiri.ex
- lib/console/schema/build.ex
- lib/console/services/builds.ex
- lib/kube/builder.ex
- mix.lock
- plural/helm/console/templates/secrets.yaml
- plural/terraform/aws/deps.yaml
- plural/terraform/aws/node-group.tf
- plural/terraform/aws/variables.tf
- priv/repo/migrations/20230118012409_add_build_k8s_job.exs
- rel/config/console.exs
Will be used to sidestep breaking node updates, we'll need to add a new build type to support this and logic in the upgrade system to also facilitate it.
local link worked
> ENG-1117 Add dedicated node group for console nodes

- lib/console/plural/queries.ex
> feat: Update recipe config query fragment to properly expose optional field

- assets/package.json
- assets/src/components/cluster/containers/ContainersList.tsx
- assets/src/components/repos/installer/Application.tsx
- assets/src/components/repos/installer/Configuration.tsx
- assets/src/components/repos/installer/ConfigurationItem.tsx
- assets/yarn.lock
Updated the app installer with some VQA nit picks.
Locally
> fix: Update empty config message and add leading period to domain

- assets/src/components/apps/AppCard.tsx
- assets/src/components/apps/AppStatus.tsx
- assets/src/components/apps/app/App.tsx
- assets/src/components/apps/app/components/ComponentProgress.tsx
- assets/src/components/apps/app/config/ConfigurationEditor.tsx
- assets/src/components/builds/BuildStatus.tsx
- assets/src/components/cluster/nodes/NodesList.tsx
- assets/src/components/cluster/pods/PodInfo.tsx
s/Passed/Succesr/ for builds, and use right region/zone values in nodes list
local
> Minor Console language fixes

- assets/package.json
- assets/src/components/apps/app/components/Components.tsx
- assets/src/components/utils/layout/ResponsiveLayoutSidecarContainer.tsx
- assets/src/components/utils/layout/ResponsiveLayoutSidenavContainer.tsx
- assets/yarn.lock
---
- https://app.asana.com/0/0/1203845496040383
> feat: Add dropdown Components filter

- assets/src/components/cluster/nodes/NodesList.tsx
Eliminates scroll-in-scroll behavior since the list isn't going to be excessively large
local
> Fix nodes table display

- assets/package.json
- assets/src/components/apps/Apps.tsx
- assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
- assets/src/components/apps/app/runbooks/runbook/RunbookExecutions.tsx
- assets/src/components/cluster/containers/ContainerShell.tsx
- assets/src/components/terminal/Terminal.tsx
- assets/yarn.lock
Well, I accidentally pushed most of my branch commits directly to `reskin` so this PR looks a lot smaller than what I'm going to list below, but still adding all my changes here for reference.
- [Shell Screen Fixes](https://app.asana.com/0/1203642829646384/1203863119380891/f)
- [Move alerts on runbooks to the bottom
](https://app.asana.com/0/1203642829646384/1203829571006355/f)
- [Update the spacing at the top of the full screens](https://app.asana.com/0/1203642829646384/1203860079881502/f)
- Improved visuals on line graphs
- Loading indicator improvements (no more flash of white background), swapped all old loading animations to design system version
- Added a confirmation dialog when removing admin privileges from a user. (I was tired of always living on the edge of possibly locking …
> Console updates

- assets/src/components/apps/app/components/component/Component.tsx
- assets/src/utils/status.ts
- lib/console/application.ex
- lib/console/cached/pods.ex
- lib/console/graphql/kubernetes/application.ex
- test/console/cached/pod_test.exs
We were marking complete as same as ready, which looks really wrong for init containers.
local
> Fix readiness color scheme

- lib/console/graphql/kubernetes.ex
- lib/console/graphql/resolvers/kubernetes.ex
- test/test_helper.exs
This could potentially dramatically speed up the cluster pods view for users.
n/a
> Query for cached pods

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
This will help a user in discord that wants a recent fix that missed last release
verified on gcp cluster
> Bump console to v0.3.25

- lib/console/pubsub/protocols/recurse.ex
- lib/console/runner.ex
- lib/console/schema/build.ex
- lib/console/services/builds.ex
- priv/repo/migrations/20230203195928_add_build_pid.exs
- test/console/pubsub/recurse/builds_test.exs
- test/console/runner_test.exs
This will help make approvals a bit more reliable as it seems that swarm doesn't always register properly
added some unit tests
> Register build pids in db

- assets/src/components/apps/AppCard.tsx
- assets/src/components/apps/app/logs/LogLine.tsx
- lib/console/schema/user.ex
* make info logs green
* case insensitive user name search
* add anchor for app selector for sandbox
local
> Small console tweaks

- assets/src/components/cluster/LabelsAnnotations.tsx
---
- https://app.asana.com/0/0/1203894855330888
> fix: Make sure key:value pairs display values on Components metadata page

- assets/src/components/apps/app/components/Component.tsx
- assets/src/components/apps/app/components/Components.tsx
---
- https://app.asana.com/0/0/1203894855330893
> feat: Split components into 2 across

- assets/src/components/apps/app/logs/LogLine.tsx
- assets/src/components/cluster/ContainerStatuses.tsx
- assets/src/components/cluster/containers/getPodContainersStats.tsx
- assets/src/utils/status.ts
It looks like we weren't respecting 0 exit codes, this will fix
local
> Fix terminated container statuses

- assets/src/components/apps/app/components/Component.tsx
- assets/src/components/apps/app/components/Components.tsx
Always show two-column, and sort components by priority
local
> Improve two-column components view

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
Console redesign!
in console.plural.sh
> Releasing console v0.4.0

- assets/src/components/repos/constants.ts
- assets/src/components/repos/installer/Configuration.tsx
- assets/src/components/repos/installer/ConfigurationItem.tsx
- assets/src/components/repos/installer/Installer.tsx
- Add `EQ` condition support for API fields
- Fix boolean logic for Switch component
- Update `forbidden` error message
Locally
---
- https://app.asana.com/0/0/1203893704234717
> feat: Update installer

- assets/src/components/apps/app/components/Components.tsx
- assets/src/components/apps/app/components/component/Component.tsx
- assets/src/components/utils/Graph.tsx
- Center components empty state
- Improve graph display
- Fix cropped outline in component details view
Tested locally.
---
- https://app.asana.com/0/0/1203884919610722
> fix: Various improvements

- assets/package.json
- assets/src/components/apps/app/components/component/info/CronJob.tsx
- assets/src/components/apps/app/components/component/info/Pods.tsx
- assets/src/components/cluster/containers/ContainersList.tsx
- assets/src/components/cluster/nodes/NodeInfo.tsx
- assets/src/components/cluster/nodes/NodesList.tsx
- assets/src/components/cluster/pods/Pods.tsx
- assets/src/components/cluster/pods/PodsList.tsx
- assets/yarn.lock
Uses https://github.com/pluralsh/design-system/pull/406 instead of inline links.
---
- https://app.asana.com/0/0/1203887349570279
> feat: Add hover to table rows and remove inline links

- assets/src/components/cluster/ContainerStatuses.tsx
- assets/src/components/layout/AppNav.tsx
- assets/src/components/layout/Subheader.tsx
It adds global app navigation to the console subheader.
https://user-images.githubusercontent.com/2823399/217531557-2538ea0d-0275-472d-8793-c92558eb3ddc.mov
Locally.
---
- https://app.asana.com/0/0/1203893704234702
> feat: Global app navigation

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
Global app nav and a few other nice features
our console
> Release v0.4.1

- assets/src/components/hooks/useOnClickOutside.tsx
- assets/src/components/layout/AppNav.tsx
Now slides in from the right, and using react-spring for buttery-smooth animation.
> feat: Finesse App switcher transitions

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
minor fixes for redesign
wired into our cosnole
> Console release

- assets/src/components/login/OauthCallback.tsx
> fix: OAuthCallback was hanging

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
fixes for login and conf edits
n/a
> Release console v0.4.3

- assets/src/components/apps/app/components/component/ComponentInfo.tsx
- assets/src/components/apps/app/components/component/info/Metadata.tsx
Fixed component detail page layout.
Locally.
> fix: Fix component detail page layout

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/proxies.yaml
Fix target name for the Proxy object
> fix target name

- assets/src/components/layout/Console.tsx
No more `test` :slightly_smiling_face: 
Locally
> fix: Get rid of test message

- assets/src/components/apps/app/components/component/ViewLogsButton.tsx
This just slows things down and we already have decent back button support so not that needed
n/a
> Don't open logs in new tab

- assets/src/components/apps/app/components/Components.tsx
Add option to clear all selected component types.
Locally.
---
- https://app.asana.com/0/0/1203894855330896
> feat: Add option to clear all selected component types

- assets/src/components/apps/app/config/ConfigurationSettings.tsx
- assets/src/components/builds/CreateBuild.tsx
- assets/src/components/cluster/containers/getPodContainersStats.tsx
- assets/src/components/cluster/pods/Pods.tsx
- assets/src/components/login/Login.tsx
Use combobox to select apps when creating builds.
https://user-images.githubusercontent.com/2823399/219031200-7e88ba14-5fd5-46bd-8520-113799a77aff.mov
</br>
Use combobox to select namespaces.
Note: After clicking on "view all" footer the combobox will not close. It looks like there may be some issue in design system. I have left comment in the code to check that later.
Locally.
---
- https://app.asana.com/0/0/1203845499454688
> feat: Use combobox to filter apps and namespaces

- plural/helm/console/Chart.yaml
Minor fixes post-launch
in our console
> Release v0.4.4

- assets/.gitignore
- lib/kube/wireguard.ex
Fixed a typo in the VPN client list module and added my local GQL schema files to gitignore.
> fix: Fix VPN api typo

- lib/console/graphql/kubernetes/vpn.ex
- lib/console/graphql/schema/base.ex
- lib/console/services/vpn.ex
- lib/kube/client.ex
- lib/kube/wireguard.ex
- test/support/kubernetes_scaffolds.ex
need to ! the read_namespaced_secret method
unit tests
> Fix vpn config fetch

- assets/src/components/account/vpn/VPN.tsx
- lib/kube/client.ex
- lib/kube/client/base.ex
not entirely sure what's going on but it might be related to not setting content type
linked to our console
> Potentially fix deleting wireguard peer

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
includes vpn CRUD interface, app specific docs, and more goodies
link
> Publish v0.4.5

- assets/src/components/account/vpn/VPN.tsx
- assets/src/components/profile/VPN.tsx
- assets/src/components/vpn/VPNClientList.tsx
- assets/src/components/vpn/columns/Actions.tsx
Table will be scrollable now.
Locally
---
- https://app.asana.com/0/0/1204067114987471
> fix: Fix VPN table scrolling

- assets/src/components/layout/AppNav.tsx
Before: <img width="300" alt="Zrzut ekranu 2023-03-6 o 09 51 45" src="https://user-images.githubusercontent.com/2823399/223062058-91015215-83a4-4680-a5fa-e5f997751422.png"> After: <img width="300" alt="Zrzut ekranu 2023-03-6 o 09 51 24" src="https://user-images.githubusercontent.com/2823399/223062074-c04730ba-31d2-4bed-826f-b04fc5baf3e6.png">
Tested locally.
> fix: App nav is displayed under overlay

- assets/src/components/layout/Header.tsx
Tested locally.
---
- https://app.asana.com/0/0/1204017267791552
> fix: Link in header is not helpful

- lib/console/graphql/configuration.ex
- lib/console/plural/queries.ex
Will be useful for configuring access to groups/roles
n/a
> expose user management feature

- assets/codegen.yml
- assets/src/generated/graphql.ts
- schema/schema.graphql
The schema generation config file was accidentally changed and the schema wasn't updated properly. This PR fixes the config and updates the schema.
> fix schema generation and update schema

- .github/workflows/pr-labels.yaml
- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
> Release v0.4.7

- assets/src/components/graphql/users.js
- assets/src/components/profile/SecurityAccess.tsx
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/pubsub/events.ex
- lib/console/pubsub/protocols/audit.ex
- lib/console/schema/audit.ex
- lib/console/services/users.ex
- test/console/graphql/queries/user_queries_test.exs
- test/console/pubsub/audit/users_test.exs
also includes audit logging
local
> Use audited temporary token query

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
> Release v0.4.8

- assets/src/generated/graphql.ts
- lib/console/features.ex
- lib/console/graphql/configuration.ex
- lib/console/graphql/plural.ex
- lib/console/graphql/resolvers/plural.ex
- lib/console/graphql/schema/base.ex
- lib/console/plural/models.ex
- lib/console/plural/queries.ex
- schema/schema.graphql
- test/console/graphql/queries/plural_queries_test.exs
Will be useful to refactor billing treatment in ui
unit test
> Add query to fetch account

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
fixes for console billing and other details
n/a
> release v0.4.9

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
Bumps the console for the latest release that includes posthog.
> console release v0.4.10

- .github/workflows/push-to-plural.yaml
- plural/plural/recipe/console-aws.yaml
- plural/plural/recipe/console-azure.yaml
- plural/plural/recipe/console-equinix.yaml
- plural/plural/recipe/console-gcp.yaml
- plural/plural/recipe/console-kind.yaml
As done in pluralsh/plural-artifacts
n/a
> Add primary recipes

- Dockerfile
This is needed for the console to be able to handle zonal gke clusters
will test in our console
> Bump cli version in dockerfile

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
includes fix for zonal clusters
n/a
> Release v0.4.12

- plural/plural/recipe/console-aws-cluster-api.yaml
- plural/plural/recipe/console-gcp-cluster-api.yaml
make private recipes for cluster API
> make private recipes for cluster api

- Dockerfile
should speed up builds and clean up some CVEs
wire up a console instance
> Remove unnecessary deps from docker image

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
increases header lengths, improves docker image
deploy to our consoles
> Release v0.4.13

- assets/src/components/builds/UpgradePolicyCreate.tsx
- lib/console/graphql/policies.ex
- lib/console/schema/upgrade_policy.ex
- lib/console/services/policies.ex
- priv/repo/migrations/20230516163204_add_upgrade_policy_repos.exs
- test/console/services/policies_test.exs
Extends the upgrade policy system to be a bit more user-friendly with explicit regexes and repository lists.
unit tests
> Support regex and repo list policies

- Dockerfile
Needed to introduce changelog fixes and other new cli features
include pr image in deployed console, ensure encryption works
> Update plural cli in dockerfile

- plural/helm/console/Chart.yaml
deploys command palette and cli updates
deployed to prod console, tested new features and that builds can be created
> Release v0.4.15

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
> release v0.4.17

- assets/src/components/account/users/OIDCInvite.tsx
- assets/src/components/account/users/Users.tsx
- assets/src/components/apps/app/oidc/UserManagement.tsx
Add a modal that just surfaces the OIDC edit page in-modal on the console account page since that's a more natural spot to look.  Also change the description text to be semantically clear about the underlying operation.
local
---
- https://app.asana.com/0/0/1204956661871892
> feat: Console OIDC in Users tab

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/deployment.yaml
- plural/helm/console/values.yaml
Also cleaned up the console chart a bit
link
> Release v0.4.18

- .github/workflows/publish.yaml
This will automatically create a commit w/ a helm chart bump then a pr to approve and merge it.
imitates the pluralsh/plural setup
> Add auto-bump to console release process too

- Dockerfile
- lib/console/commands/plural.ex
Also have plural diff not break builds
existing tests, deploy to test console
> Bump console cli to 0.6.26

- assets/package.json
- assets/src/components/apps/app/App.tsx
- assets/src/components/apps/app/oidc/UserManagement.tsx
- assets/src/generated/graphql.ts
- assets/yarn.lock
- lib/console/graphql/audit.ex
- lib/console/graphql/build.ex
- lib/console/graphql/configuration.ex
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/kubernetes/application.ex
- lib/console/graphql/kubernetes/certificate.ex
- lib/console/graphql/kubernetes/ingress.ex
- lib/console/graphql/observability.ex
- lib/console/graphql/plural.ex
- lib/console/graphql/policies.ex
- lib/console/graphql/resolvers/kubernetes.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/runbooks.ex
- lib/console/graphql/schema/base.ex
- lib/console/graphql/users.ex
- lib/console/graphql/webhooks.ex
- lib/console/services/users.ex
- lib/kube/client.ex
- schema/schema.graphql
- test/console/graphql/mutations/kubernetes_mutations_test.exs
- test/console/graphql/mutations/user_mutations_test.exs
- test/support/factory.ex
Will help w/ some of the console user mgmt flows
unit test
> Rename user management, add delete mutation

- assets/src/generated/graphql.ts
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/kubernetes/base.ex
- lib/console/graphql/kubernetes/config.ex
- lib/console/graphql/resolvers/kubernetes.ex
- schema/schema.graphql
- test/console/graphql/queries/kubernetes_queries_test.exs
- test/support/kubernetes_scaffolds.ex
These will allow us to safely query config data and surface them in the console
unit test
> Add config map/secret queries

- .github/workflows/publish.yaml
- .github/workflows/push-to-plural.yaml
Leverages oidc temporary credentials where needed
n/a
> Use new setup-plural action

- assets/src/components/apps/AppCard.tsx
Some catalog app versions have v prefixes so just don't force-prefix it.
n/a
> Better version name inference

- assets/src/components/layout/Header.tsx
- assets/src/components/vpn/actions/Download.tsx
- lib/console/services/vpn.ex
- test/support/kubernetes_scaffolds.ex
The type match was slightly wrong for wireguard peers, causing an issue with vpn client downloads.
n/a
---
- https://app.asana.com/0/0/1205326696364460
> Fix vpn download and remove plural account cta

- assets/package.json
- assets/src/components/login/CurrentUser.tsx
- assets/src/components/login/Login.tsx
- assets/yarn.lock
- Intercom default launcher was still showing on sandbox
- AI chat wouldn't launch on sandbox
- Changed `CurrentUser` context provider to still render children if user isn't logged into `app.plural.sh` so `<PluralAPI>` could still work for accessing public queries.
- Added TypeScript types for `uuid` package
> fix: Support chat on sandbox

- Dockerfile
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- lib/console/graphql/database.ex
- lib/console/graphql/kubernetes.ex
- schema/schema.graphql
Will include sync marking and other changes
wire into running console
> Bump cli version in console

- assets/src/generated/graphql.ts
- lib/console/graphql/database.ex
- schema/schema.graphql
this apparently is heavily lagged, so just need to accept it
existing
> Allow postgres statuses to be nullable

- assets/src/components/apps/AppCard.tsx
- assets/src/components/apps/app/App.tsx
- assets/src/components/apps/app/AppSelector.tsx
- assets/src/generated/graphql.ts
- lib/console/graphql/plural.ex
- schema/schema.graphql
Small view bug, also added more handling of deletion protection in uninstall view.
local test
> Fix version display in app select

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml.tpl
This PR ensures the console artifact is compatible with both `google` and `gcp` as the provider returned by the CLI.
> fix(artifact): make compatible with gcp provider

- plural/helm/console/values.yaml.tpl
Should fix a linting issue preventing the chart from being pushed to Plural.
> fix(artifact): cleanup templating

- assets/src/components/cluster/nodes/NodesList.tsx
Nodes are listed with their CPU usage as an absolute number, rather than relative to their CPUs available.
> List cpu usage relative to total cpus

- Dockerfile
- assets/src/components/apps/app/App.tsx
- assets/src/components/apps/app/config/Configuration.tsx
- assets/src/components/apps/app/config/misc.ts
- assets/src/components/apps/app/docs/MarkdocContent.tsx
- assets/src/components/graphql/plural.js
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- lib/console/graphql/configuration.ex
- lib/console/graphql/resolvers/plural.ex
- lib/console/services/plural.ex
- schema/schema.graphql
This will let us show chart values docs in-console
test on local console
> Allow querying chart readmes

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/secrets.yaml
- plural/helm/console/values.yaml.tpl
This was never actually used in the console but will be for storing some stuff in db for CD so lets set it.
link
> Set aes key

- .tool-versions
- lib/console/storage/git.ex
- lib/console/watchers/upgrade.ex
Also just a bit cleaner overall
apply to local console
> Use clone -b to avoid weird decryption sequencing

- lib/console/deployments/clusters.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/cluster.ex
- priv/repo/migrations/20231006141431_add_cluster_creds.exs
- test/console/deployments/clusters_test.exs
just maps the credential record to the cluster
unit
> Add support for specifying cluster credentials

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/deployment.yaml
- plural/helm/console/templates/migration.yaml
- plural/helm/console/values.yaml
Allows us to switch runasuser easier as well.
link
> Allow for secret mounts to be configured

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/deployment.yaml
- plural/helm/console/values.yaml
> fix: Add configurable probes

- Dockerfile
- lib/console_web/console_web.ex
- rel/config/console.exs
security hygeine.  This depends on another pr to modify our helm charts before merging
manual
> Convert console dkr image to run as nonroot

- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/cd/cluster/ClusterMetadata.tsx
- assets/src/components/cd/cluster/ClusterMetadataPanel.tsx
- assets/src/components/cd/cluster/ClusterPermissions.tsx
- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/clusters/ClusterUpgrade.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
- assets/src/components/utils/InfoPanel.tsx
- assets/src/components/utils/Prop.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
- assets/src/graph/cdServices.graphql
> feat: CD cluster details and fix now button improvements

- assets/src/components/apps/app/components/ComponentCard.tsx
- assets/src/components/apps/app/components/ComponentList.tsx
- assets/src/components/apps/app/components/ComponentProgress.tsx
- assets/src/components/apps/app/components/Components.tsx
- assets/src/components/apps/app/components/component/Component.tsx
- assets/src/components/apps/app/components/component/ComponentInfo.tsx
- assets/src/components/cd/ContinuousDeployment.tsx
- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/components/cd/providers/Providers.tsx
- assets/src/components/cd/repos/GitRepositories.tsx
- assets/src/components/cd/services/ServiceSelector.tsx
- assets/src/components/cd/services/Services.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
- assets/src/components/cd/services/ServicesRollbackDeployment.tsx
- assets/src/components/cd/services/component/ServiceComponent.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
- assets/src/components/cd/services/service/ServiceSecrets.tsx
- assets/src/components/cluster/queries.js
- assets/src/components/layout/Sidebar.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdComponent.graphql
- assets/src/graph/cdServices.graphql
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/cdRoutesConsts.tsx
- assets/src/utils/isNonNullable.ts
- Services routing and breadcrumbs improvements
- Start of Component details view
> feat: Services work

- assets/src/components/cd/cluster/ClusterPods.tsx
- assets/src/components/cd/providers/CreateProvider.tsx
- assets/src/components/cd/providers/ProviderSettings.tsx
- assets/src/components/cd/providers/UpdateProvider.tsx
- assets/src/components/cd/services/DecoratedName.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/ServicesDeployService.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
- assets/src/components/cd/services/component/ServiceComponent.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/cd/services/service/ServiceSecrets.tsx
- assets/src/components/component/ComponentDetails.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdGitRepos.graphql
- assets/src/graph/cdServices.graphql
- assets/src/routes/cdRoutesConsts.tsx
- Enable creating Service Deployments in the UI
- Change Component Details urls to use IDs
- Show service name in breadcrumbs instead of ID after loading
> feat: Component Details path change + Service deployment creation

- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/clusters/ClusterHealthChip.tsx
- assets/src/components/cd/providers/ProviderSettings.tsx
- assets/src/components/cd/services/ServiceDeprecations.tsx
- assets/src/components/cd/services/ServiceErrors.tsx
- assets/src/components/cd/services/Services.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/cd/services/service/ServiceDeprecationsModal.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdServices.graphql
- assets/src/types/global.d.ts
- assets/src/utils/date.ts
---
- https://app.asana.com/0/0/1205789093135011
> feat: Service Errors should be viewable as a status chip in services table

- assets/src/components/cd/ModalAlt.tsx
- assets/src/components/cd/cluster/ClusterPermissions.tsx
- assets/src/components/cd/clusters/GlobalSettings.tsx
- assets/src/components/cd/providers/ProviderSettings.tsx
- assets/src/components/cd/repos/GitHealthChip.tsx
- assets/src/components/cd/repos/GitRepositoriesImportGit.tsx
- assets/src/components/cd/repos/GitRepositoriesUpdateGit.tsx
- assets/src/components/cd/services/CreateGlobalService.tsx
- assets/src/components/cd/services/DeleteService.tsx
- assets/src/components/cd/services/ServicePermissions.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/utils/PermissionsModal.tsx
- assets/src/components/cd/utils/SshKeyUpload.tsx
- assets/src/components/utils/FileDrop.tsx
- assets/src/components/utils/MoreMenu.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
- assets/src/graph/cdGlobalServices.graphql
- assets/src/graph/cdServices.graphql
Add private key upload, service permissions, start global service creation modal
> feat: Daily CD handoff

- assets/src/components/cd/providers/CreateProvider.tsx
- assets/src/components/cd/providers/ProviderSettings.tsx
- assets/src/components/cd/services/Services.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
> feat: Add option to create Azure provider

- assets/src/components/cd/cluster/ClusterMetadata.tsx
- assets/src/components/cd/clusters/ClusterConditions.tsx
- assets/src/components/cd/clusters/ClusterUpgrade.tsx
- assets/src/components/cd/clusters/VersionSelect.tsx
- assets/src/components/cd/clusters/create/CreateCluster.tsx
- assets/src/components/cd/clusters/create/CreateClusterContent.tsx
- assets/src/components/cd/clusters/create/NameVersionHandle.tsx
- assets/src/components/cd/clusters/create/ProviderTabSelector.tsx
- assets/src/components/cd/clusters/create/helpers.ts
- assets/src/components/cd/clusters/create/provider/AWS.tsx
- assets/src/components/cd/clusters/create/provider/Azure.tsx
- assets/src/components/cd/clusters/create/provider/GCP.tsx
- assets/src/components/cd/clusters/create/provider/NodeGroup.tsx
- assets/src/components/cd/clusters/create/provider/NodeGroupContainer.tsx
- assets/src/components/cd/clusters/create/types.ts
- assets/src/components/cd/clusters/deprecationsColumns.tsx
- assets/src/components/cd/providers/CreateProvider.tsx
- assets/src/components/cd/providers/ProviderSettings.tsx
- assets/src/components/cd/providers/Providers.tsx
- assets/src/components/cd/utils/ProviderCredsSelect.tsx
- assets/src/components/cluster/pods/Pods.tsx
- assets/src/components/utils/typography/Text.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdProviders.graphql
Cluster creation:
- Add dropdown selector for version
- Consolidate form state in one place
- Add dropdown selector for credentials when available (not thoroughly tested, since we don't seem to have any added credentials at the moment)
Provider creation:
- Nicer cloud provider selector stolen from cluster creation
- Prevent selection of cloud providers that have already been used
> feat: Cluster/Provider creation enhancements

- .github/workflows/test.yaml
- Dockerfile
- plural/helm/console/Chart.yaml
- plural/helm/console/templates/azure.yaml
- plural/helm/console/values.yaml
- plural/helm/console/values.yaml.tpl
- plural/terraform/azure/deps.yaml
- plural/terraform/azure/main.tf
- plural/terraform/azure/outputs.tf
Tested with:
```sh
export EXP_PLURAL_CAPI=true
plural bundle install bootstrap azure-cluster-api-simple-test
plural bundle install console console-azure
plural packages uninstall helm bootstrap azure-identity
plural build
plural link terraform console --name azure --path ../console/plural/terraform/azure
plural link helm console --name console --path ../console/plural/helm/console
plural build --force
plural deploy --commit "console"
```
```yaml
console:
image:
repository: ghcr.io/pluralsh/console
tag: sha-75165de
imagePullPolicy: Always
```
```
az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
```
https://developer.hashicorp.com/terraform/language/settings/backends/azurerm …
> fix: Update console Azure auth

- lib/console/schema/cluster.ex
- test/console/deployments/clusters_test.exs
server side validate that cluster version changes don't happen while other upgrades are in-flight
unit
> feat: add server-side validation for updating clusters

- assets/src/components/apps/Apps.tsx
- assets/src/components/cd/PrepareGitStep.tsx
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/components/cd/clusters/ClustersDemoTable.tsx
- assets/src/components/cd/clusters/ClustersGettingStarted.tsx
- assets/src/components/cd/clusters/create/ImportClusterContent.tsx
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/utils/layout/EmbedAspectRatio.tsx
- assets/src/components/utils/typography/Text.tsx
- assets/src/routes/cdRoutesConsts.tsx
- assets/src/utils/constants.ts
If user has 1 or fewer clusters, show Getting Started Guide below clusters table.
> feat: Add Getting Started guide to Clusters page

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/_helpers.tpl
- plural/helm/console/templates/ingress.yaml
- plural/helm/console/values.yaml
Useful for deployments from private consoles
Will add the new release tag for the console when it's ready as will
link
> Support external ingress configuration

- lib/console/deployments/compatibilities/schema.ex
- lib/console/deployments/compatibilities/table.ex
- static/compatibilities/cert-manager.yaml
- static/compatibilities/external-dns.yaml
- static/compatibilities/manifest.yaml
- test/console/graphql/queries/deployment_queries_test.exs
> More compatibilities

- assets/src/components/cd/clusters/runtime/ExpandedColumn.tsx
- assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
- assets/src/components/cd/clusters/runtime/columns.tsx
Will help guide upgrade paths if you're really really behind
n/a
> Add expander to display all versions for a discovered add-on

- assets/src/generated/graphql.ts
- lib/console/deployments/compatibilities/schema.ex
- lib/console/graphql/deployments/cluster.ex
- schema/schema.graphql
Apparently this was wired weirdly, this should be better
n/a
> Fix cloud settings schema

- lib/console/deployments/services.ex
- lib/console/schema/api_deprecation.ex
- priv/repo/migrations/20231130034012_add_deprecations_unique_constraint.exs
- test/console/deployments/services_test.exs
Optimize the handling of api deprecations, and confirm it no-ops if no service update is required (which should reduce write IOPS load)
unit
> Improve update components performance

- assets/src/components/cd/pipelines/nodes/StageNode.tsx
> better complete status for pipeline stages

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/service.ex
- schema/schema.graphql
Needed to properly paginate services views
n/a
> Add status query for services

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments.ex
- lib/console/graphql/middleware/observability_client.ex
- lib/console/graphql/observability.ex
- lib/console/schema/agent_migration.ex
- lib/console/schema/deployment_settings.ex
- lib/console/services/observability.ex
- lib/loki/client.ex
- lib/prometheus/client.ex
- priv/repo/migrations/20231204165634_add_prometheus_configs.exs
- schema/schema.graphql
will help us bring back some of the metrics in-ui for CD
existing
> Add global prometheus + loki setup

- assets/src/components/cd/services/ServiceSettings.tsx
- assets/src/components/cd/services/ServiceUpdateHelmValues.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/deployModal/DeployService.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsHelmValues.tsx
- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/cd/services/service/ServiceHelm.tsx
- assets/src/components/cd/services/service/ServiceSettings.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdServices.graphql
- assets/src/routes/cdRoutes.tsx
- Enable editing of helm `values` and `valuesFiles` in three-dots menu and in service details
- Make sure git settings are still editable from three-dots menu when a helm repo is also present
- Enable editing settings (git, helm, delete protection) form service details
---
- https://app.asana.com/0/0/1206095700447450
> feat: Display values.yaml file and allow new file on upgrade

- assets/src/components/cd/clusters/ClusterUpgrade.tsx
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/utils/semver.ts
> fix: Fix upgrade check

- assets/src/components/cd/services/ServicesTable.tsx
> fix: Error deploying a new service due to missing `refetch()` function 

- assets/src/generated/graphql.ts
- lib/console/cached/cluster_nodes.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/cluster.ex
- lib/console/schema/tag.ex
- schema/schema.graphql
- test/console/graphql/queries/deployment_queries_test.exs
- test/support/factory.ex
This will help flesh out our cluster view to drive better search/filter experiences there.
added unit tests
> Add additional cluster filters and grouping queries

- assets/src/components/cd/services/deployModal/DeployService.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
- assets/src/components/cd/utils/RepoKindSelector.tsx
- assets/src/components/hooks/useOnUnMount.tsx
- Clear incomplete forms when switching away from Git or Helm tab
- Add "Deselect" link to quickly remove a git or helm repo
- Add check mark icon to Git and Helm tabs that have completed repo forms to make it clear these will be included even if they are not the currently selected tab.
> feat: Improved UX for Deploy Service repository selection screen

- lib/console/deployments/services.ex
want to avoid unnecessary writes
n/a
> feat: figure out update component write frequency

- assets/package.json
- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/cd/clusters/runtime/columns.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
- assets/src/components/cd/services/ServicesTable.tsx
- assets/src/components/cd/services/deployModal/DeployService.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsBasic.tsx
- assets/src/components/cd/utils/ClusterSelector.tsx
- assets/src/components/hooks/useThrottle.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
- assets/src/graph/cdServices.graphql
- assets/yarn.lock
- Change to new ComboBox-based ClusterSelector in Services views and Service creation
- Change Services table to use server-side queries for status-based filtering
> feat: Server side queries for Cluster selection and Service status filtering

- assets/src/components/cd/pipelines/nodes/StageNode.tsx
- assets/src/components/cd/services/ServiceStatusChip.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
- assets/src/generated/graphql.ts
- crds/flagger-canary.yaml
- lib/console/deployments/services.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/kubernetes/base.ex
- lib/console/graphql/kubernetes/canary.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/kubernetes.ex
- lib/console/schema/service.ex
- lib/console_web/controllers/git_controller.ex
- lib/console_web/router.ex
- lib/kube/client.ex
- lib/kube/models.ex
- priv/repo/migrations/20231215015805_add_service_proceed.exs
- schema/schema.graphql
- test-apps/canary/canary.yaml
- test-apps/canary/configmap.yaml
- test-apps/canary/deployment.yaml
- test-apps/canary/ingress.yaml
- test-apps/helm-values/values-flagger.yaml
- test/console/deployments/services_test.exs
- test/console/graphql/mutations/deployment_mutations_test.exs
- test/console_web/controllers/git_controller_test.exs
testing crd application, adding support for service paused state, and other details
n/a
> Begin working on flagger integration

- assets/src/components/apps/app/components/misc.tsx
- assets/src/generated/graphql.ts
- lib/console/schema/service_component.ex
- schema/schema.graphql
needed for flagger integration
n/a
> Add component paused

- assets/src/generated/graphql.ts
- lib/console/deployments/clusters.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/cluster.ex
- schema/schema.graphql
Forgot to include this in the gql schema.
n/a
> Support cluster tag updates

- charts/system-upgrade-controller/.helmignore
- charts/system-upgrade-controller/Chart.yaml
- charts/system-upgrade-controller/crds/plan.yaml
- charts/system-upgrade-controller/templates/_helpers.tpl
- charts/system-upgrade-controller/templates/clusterrolebinding.yaml
- charts/system-upgrade-controller/templates/configmap.yaml
- charts/system-upgrade-controller/templates/deployment.yaml
- charts/system-upgrade-controller/templates/serviceaccount.yaml
- charts/system-upgrade-controller/values.yaml
- test-apps/k3s/agent.yaml
- test-apps/k3s/server.yaml
just playing w/ the crd based upgrade support
n/a
> Test out k3s upgrades via CRD

- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/services/deployModal/DeployService.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsBasic.tsx
- assets/src/index.css
---
- https://app.asana.com/0/0/1206207411339718
> feat: Add "Deploy service" button to Cluster > Services page

- assets/src/components/cd/pipelines/Pipelines.tsx
> fix: Infinite redirect on `/cd/pipelines` route

- Makefile
- assets/src/components/cd/services/ServiceSettings.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
- assets/src/components/cd/services/service/ServiceSettings.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdGitRepos.graphql
- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/discovery.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/resolvers/deployments.ex
- schema/schema.graphql
- test-apps/pipelines/k3s.yaml
- test/console/deployments/helm/repository_test.exs
this will allow us to have a dropdown for the git ref in-ui
n/a
> Allow querying branches/tags for repos

- assets/src/components/cluster/pods/PodsList.tsx
- assets/src/components/cluster/queries.js
- assets/src/components/component/info/Pods.tsx
- charts/console/Chart.yaml
- charts/console/templates/migration.yaml
We didn't actually add the service id to delete pod CTAs, this will allow us to have that functionality in the multi-cluster UI.
local test
> Delete pod in CD

- charts/console/Chart.yaml
- charts/console/templates/deployment.yaml
- charts/console/templates/secrets.yaml
- charts/console/values.yaml
- lib/console/graphql/resolvers/plural.ex
- plural/helm/console/Chart.yaml
- plural/helm/console/templates/migration.yaml
- templates/values.yaml.liquid
- templates/values.yaml.tpl
Used when auto-generating the secret
locals
> Migration job needs to have a service account assigned

- .github/workflows/publish.yaml
- charts/controller/Chart.yaml
- charts/controller/templates/deployment.yaml
- charts/controller/values.yaml
Defaults the console url to the k8s internal one and can be overrided in values
local
> Minor chart tweaks, and finalize deployability of the operator

- controller/api/v1alpha1/servicedeployment_types.go.go
- controller/api/v1alpha1/zz_generated.deepcopy.go
- controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
- controller/internal/controller/servicedeployment_controller.go
- controller/internal/controller/servicedeployment_ginkgo_test.go
Fixes https://app.asana.com/0/home/1203829673754776/1206268847103215.
---
- https://app.asana.com/0/0/1206268847103215
> fix: Remove service deployment defaulting

- assets/src/components/layout/Sidebar.tsx
Just a nil pointer check fix
Locally
> fix: fix cd pages not loading due to ts error

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments.ex
- schema/schema.graphql
- test/console/deployments/pipeline_test.exs
- test/console/graphql/mutations/deployment_mutations_test.exs
This was left out, adding it back in.
unit
> Delete pipeline mutation

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/pipeline.ex
- schema/schema.graphql
Needed to make the gql simpler to execute.
existing
> Change labels/annotations on gate jobs

- controller/api/v1alpha1/globalservice_types.go
- controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
- controller/go.mod
- controller/go.sum
- controller/internal/client/console.go
- controller/internal/client/globalservice.go
- controller/internal/client/service.go
- controller/internal/controller/globalservice_controller.go
- controller/internal/controller/globalservice_scope.go
- controller/internal/controller/globalservice_test.go
- controller/internal/test/mocks/ConsoleClient_mock.go
- controller/internal/types/reconciler.go
Add support for GlobalService objects
> feat: Global service

- assets/src/components/component/ComponentInfo.tsx
- assets/src/components/component/info/Canary.tsx
- assets/src/components/component/info/Deployment.tsx
- assets/src/components/component/info/Ingress.tsx
- assets/src/components/component/info/Metadata.tsx
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/utils/PieChart.tsx
- assets/src/components/utils/typography/InlineLink.tsx
- Clicking an Ingress or Deployment in canary view shows a modal with details for those components
- Add placeholder visual for Pie charts without any data.
---
- https://app.asana.com/0/0/1206232855142999
> feat: Show details for Ingress/Deployments in canary view

- controller/cmd/main.go
- controller/internal/controller/gitrepository_controller_test.go
- controller/internal/controller/globalservice_controller.go
- controller/internal/controller/servicedeployment_controller.go
- controller/internal/controller/servicedeployment_controller_test.go
- controller/internal/errors/base.go
Set `Ready` condition to `true` if all components are healthy
> feat: Update service condition

- assets/src/generated/graphql.ts
- crds/plural-cluster.yaml
- crds/plural-gitrepo.yaml
- crds/plural-service.yaml
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/kubernetes/plural.ex
- lib/console/graphql/resolvers/kubernetes.ex
- lib/console/graphql/resolvers/kubernetes/plural.ex
- lib/kube/client.ex
- lib/kube/models.ex
- schema/schema.graphql
- test/console/graphql/queries/kubernetes_queries_test.exs
- test/support/kubernetes_scaffolds.ex
Will be able to properly render dedicated service views for them via gql
unit tests
> Add first-class objects for plural deployments crds

- assets/package.json
- assets/src/components/apps/AppCard.tsx
- assets/src/components/apps/app/App.tsx
- assets/src/components/builds/build/Build.tsx
- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/cd/cluster/ClusterAddOns.tsx
- assets/src/components/cd/cluster/ClusterMetadata.tsx
- assets/src/components/cd/cluster/ClusterNodes.tsx
- assets/src/components/cd/cluster/addon/ClusterAddOnCompatibility.tsx
- assets/src/components/cd/cluster/addon/ClusterAddOnDetails.tsx
- assets/src/components/cd/cluster/addon/ClusterAddOnDetailsSidecar.tsx
- assets/src/components/cd/clusters/ClusterUpgrade.tsx
- assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
- assets/src/components/cd/clusters/runtime/columns.tsx
- assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
- assets/src/components/cluster/nodes/ClusterGauges.tsx
- assets/src/components/component/info/common.tsx
- assets/src/components/utils/Metadata.tsx
- assets/src/components/utils/typography/Text.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/cdRoutesConsts.tsx
- assets/yarn.lock
- Add new 'Add-ons' tab to Cluster details view
- Add new cluster addon details pages with compatibility matrix
- Remove row expansions in upgrades modal table and link to compatibility matrix instead
---
- https://app.asana.com/0/0/1206268274161467
> feat: Upgrade modal revision

- assets/src/generated/graphql.ts
- lib/console/deployments/clusters.ex
- lib/console/deployments/compatibilities/schema.ex
- lib/console/deployments/policies/rbac.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/pr_automation.ex
- lib/console/schema/service.ex
- lib/console/schema/service_component.ex
- schema/schema.graphql
- static/compatibilities/argo-rollouts.yaml
- static/compatibilities/cert-manager.yaml
- static/compatibilities/external-dns.yaml
- static/compatibilities/ingress-nginx.yaml
- static/compatibilities/istio.yaml
- static/compatibilities/kube-prometheus-stack.yaml
- test/console/graphql/queries/deployment_queries_test.exs
Will help us flesh out our details pages for these
unit
> Expose readmes/release urls for compatibilities

- lib/console/deployments/helm/cache.ex
- lib/console/deployments/helm/server.ex
- lib/console/schema/service_component.ex
- test/console/deployments/services_test.exs
> Improve Helm chart caching, and dry run persistence

- assets/src/generated/graphql.ts
- lib/console/commands/plural.ex
- lib/console/deployments/git.ex
- lib/console/deployments/pr/config.ex
- lib/console/deployments/pr/dispatcher.ex
- lib/console/deployments/pr/git.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/deployments/pr/impl/gitlab.ex
- lib/console/graphql/deployments/git.ex
- lib/console/schema/pr_automation.ex
- lib/console/schema/scm_connection.ex
- schema/schema.graphql
- test/console/deployments/git_test.exs
- test/console/graphql/mutations/deployments/git_mutations_test.exs
> feat: Properly shell to `plural pr template`

- assets/src/components/apps/app/runbooks/runbook/RunbookExecutions.tsx
- assets/src/components/audits/table/AuditTable.tsx
- assets/src/components/builds/Build.tsx
- assets/src/components/builds/build/BuildTimer.tsx
- assets/src/components/cd/cluster/ClusterMetadata.tsx
- assets/src/components/cd/clusters/ClusterConditions.tsx
- assets/src/components/cd/clusters/ClusterHealthChip.tsx
- assets/src/components/cd/clusters/ClusterUpgrade.tsx
- assets/src/components/cd/repos/GitRepositoriesColumns.tsx
- assets/src/components/cd/services/ServiceRevisionColumns.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cluster/pods/PodConditions.tsx
- assets/src/components/db-management/DatabasesList.tsx
- assets/src/components/profile/AccessTokens.tsx
- assets/src/components/utils/EventsTable.tsx
- assets/src/components/utils/TooltipTime.tsx
- assets/src/components/utils/table/DateTimeCol.tsx
Adds a timestamp tooltip w/ copy-on-click functionality to dates across the app
---
- https://app.asana.com/0/0/1206407280605431
> feat: Add precise tooltips to all timestamps in Console

- assets/src/generated/graphql.ts
- lib/console/deployments/helm/server.ex
- lib/console/graphql/deployments/git.ex
- lib/console/schema/embeds.ex
- lib/console/schema/pr_automation.ex
- priv/repo/migrations/20240124153455_add_pr_configs.exs
- schema/schema.graphql
Will help us build full ui around the automation flow
n/a
> Add git pr configuration types

- assets/src/generated/graphql.ts
- lib/console/deployments/git.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/resolvers/deployments/git.ex
- schema/schema.graphql
will aid operator development
n/a
> Support querying scm/pr automation objects by name alongsideid

- Dockerfile
- assets/src/generated/graphql.ts
- lib/console/deployments/services.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments/service.ex
- schema/schema.graphql
- test/console/deployments/services_test.exs
- test/console/graphql/mutations/deployments/services_mutations_test.exs
Will be useful in soft-delete ui
unit
> Add detach service api

- assets/src/components/cd/clusters/ClustersColumns.tsx
- assets/src/components/cd/providers/DeleteCluster.tsx
- assets/src/components/cd/providers/DetachCluster.tsx
- assets/src/components/cd/services/DetachService.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
- assets/src/graph/cdServices.graphql
> Feat: Add detach options to three-dot menus in Clusters and Services tables

- charts/controller/values.yaml
- controller/internal/controller/servicedeployment_controller.go
noticed this on a test cluster, should address it
n/a
> Fix null pointer crash in console controller

- static/compatibilities/linkerd.yaml
- static/compatibilities/manifest.yaml
Added Linkerd, a graduated cncf project. Compatibility details can be found here: https://linkerd.io/2.14/reference/k8s-versions/
> feat: Added linkerd compatibility

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/git.ex
- schema/schema.graphql
Needed for agent poller, and to express if its bound in-ui
n/a
> Add restore/object store cluster sideloads

- assets/src/generated/graphql.ts
- lib/console/deployments/compatibilities/schema.ex
- lib/console/deployments/pr/git.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/users.ex
- lib/console/schema/scm_connection.ex
- lib/console/schema/user.ex
- priv/repo/migrations/20240130195216_add_ssh_signing_key.exs
- schema/schema.graphql
- test/console/graphql/queries/deployments/cluster_queries_test.exs
> Check if an add-on is blocking for next not current k8s version

- assets/src/generated/graphql.ts
- lib/console.ex
- lib/console/commands/plural.ex
- lib/console/deployments/backups.ex
- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/discovery.ex
- lib/console/deployments/pr/dispatcher.ex
- lib/console/graphql/deployments/backup.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/middleware/authenticated.ex
- lib/console/graphql/resolvers/deployments/backup.ex
- lib/console/schema/cluster_backup.ex
- lib/console/schema/pr_automation.ex
- priv/repo/migrations/20240131170141_add_pr_auto_git.exs
- schema/schema.graphql
- test/console/deployments/backups_test.exs
- test/console/deployments/git_test.exs
- test/console/graphql/mutations/deployments/backup_mutations_test.exs
- test/console/graphql/mutations/deployments/git_mutations_test.exs
- test/support/factory.ex
Adds the structures needed for create mode pr automation, and also added some tweaks to support backup/restore
n/a
> Implement PR Create File flow, more fixups for backup/restore

- lib/console/graphql/resolvers/deployments/backup.ex
> Handle nulls in polymorphic cluster backup query

- controller/internal/controller/servicedeployment_controller.go
Allow updating user/group read/write bindings when updating ServiceDeployment CRD.
> fix: pass bindings to service deployment update mutation

- static/compatibilities/cert-manager.yaml
1.14 has been released.
https://cert-manager.io/docs/releases/#upcoming-releases
> feat: updated cert-manager compatibility

- assets/src/components/audits/table/AuditTable.tsx
> feat: Add link to app from audits table

- .github/workflows/assets.yaml
- .github/workflows/controller-cd.yaml
- assets/src/generated/graphql.ts
- lib/console/deployments/clusters.ex
- lib/console/graphql/deployments/git.ex
- schema/schema.graphql
will unblock ui a bit more
n/a
> Nullable scm token updates

- lib/console/schema/pr_automation.ex
copypasta mapped these to the same column, this should fix
n/a
> Fix binding mappings

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments/service.ex
- schema/schema.graphql
- test/console/graphql/queries/deployments/pipeline_queries_test.exs
- test/console/graphql/queries/deployments/service_queries_test.exs
Will help us bound mem consumption when polling the api for these per-cluster
unit
> Add paginated cluster service/gate fetches

- assets/src/components/profile/AccessTokens.tsx
- assets/src/components/profile/AccessTokensCreate.tsx
- assets/src/components/profile/AccessTokensCreateModal.tsx
- assets/src/components/profile/AccessTokensCreateScope.tsx
- assets/src/components/profile/AccessTokensScopes.tsx
- assets/src/components/utils/TooltipTime.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/tokens.graphql
---
- https://app.asana.com/0/0/1206285242609281
> feat: Access token scopes

- assets/src/generated/graphql.ts
- lib/console/deployments/tree.ex
- lib/console/graphql/deployments/backup.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/kubernetes/deployment.ex
- lib/console/graphql/resolvers/deployments/backup.ex
- lib/console/schema/cluster_restore.ex
- schema/schema.graphql
- test/console/graphql/queries/deployments/backup_queries_test.exs
Realized we hadn't implemented these, adding them now
unit
> Cluster Backup/Restore list queries

- assets/src/generated/graphql.ts
- lib/console/graphql.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/dataloader.ex
- lib/console/schema/pipeline.ex
- schema/schema.graphql
- test/console/graphql/queries/deployments/pipeline_queries_test.exs
Query aggregates for pipeline gates closed or pending to be able to render statuses in-table.
unit test
> Add pipeline status sideload

- assets/src/generated/graphql.ts
- lib/console/deployments/git.ex
- lib/console/deployments/pr/dispatcher.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/deployments/pr/impl/gitlab.ex
- lib/console/deployments/pr/impl/pass.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/schema/pipeline_gate.ex
- lib/console/schema/pull_request.ex
- lib/console_web/controllers/webhook_controller.ex
- priv/repo/migrations/20240211011247_add_pull_request_status.exs
- schema/schema.graphql
- test/console_web/controllers/webhook_controller_test.exs
Extract url and state from pr webhook responses and flush them to db as appropriate
unit
> Add scm webhook receiver implementation

- charts/console/Chart.yaml
- charts/console/templates/dashboard/configmap.yaml
- charts/console/templates/dashboard/deployment.yaml
- charts/console/templates/dashboard/rbac.yaml
- charts/console/templates/dashboard/secret.yaml
- charts/console/templates/dashboard/service.yaml
- charts/console/templates/dashboard/serviceaccount.yaml
- charts/console/templates/deployment.yaml
- charts/console/templates/ingress.yaml
- charts/console/values.yaml
- plural/helm/console/Chart.yaml
- plural/helm/console/templates/dashboard/configmap.yaml
- plural/helm/console/templates/dashboard/deployment.yaml
- plural/helm/console/templates/dashboard/rbac.yaml
- plural/helm/console/templates/dashboard/secret.yaml
- plural/helm/console/templates/dashboard/service.yaml
- plural/helm/console/templates/dashboard/serviceaccount.yaml
- plural/helm/console/values.yaml
Will be useful for our new dashboard view (default disabled for now)
n/a
> Optional k8s dashboard in console chart

- assets/src/generated/graphql.ts
- lib/console/deployments/git.ex
- lib/console/deployments/tree.ex
- lib/console/external_graphql.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/schema/dependency_management_service.ex
- lib/kube/utils.ex
- priv/repo/migrations/20240213194902_add_scm_service_link.exs
- schema/schema.graphql
- test/console/deployments/git_test.exs
Only includes a list endpoint for now
unit test change
> Add abiltiy to query services that were set up to manage dependencies for an scm connection

- assets/src/generated/graphql.ts
- lib/console/deployments/pipelines.ex
- lib/console/deployments/policies/rbac.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments/pipeline.ex
- schema/schema.graphql
- test/console/graphql/queries/deployments/pipeline_queries_test.exs
We should only promote on context changes not service revisions for these
n/a
> Control promotions for pr pipelines

- assets/src/generated/graphql.ts
- lib/console/deployments/backups.ex
- lib/console/graphql/deployments/backup.ex
- lib/console/graphql/resolvers/deployments/backup.ex
- schema/schema.graphql
- test/console/deployments/backups_test.exs
- test/console/graphql/mutations/deployments/backup_mutations_test.exs
Also fix branch naming when setting up backups
unit test
> Add query to remove backup configuration for a cluster

- .github/workflows/controller-cd.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
push the image to docker registry
> feat: push image to docker registry

- lib/console/graphql/resolvers/deployments/service.ex
- lib/console/schema/pipeline_stage.ex
> Fix kick service, and applied context in query

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/pipeline.ex
- schema/schema.graphql
Needed to create pr automation based pipelines
n/a
> Add pr automation id to promotion criteria

- lib/console/deployments/services.ex
- test/console/graphql/mutations/deployments/services_mutations_test.exs
Needed to return the right value
unit
> Fix kickService bugs

- charts/controller/crds/deployments.plural.sh_pipelines.yaml
- controller/api/v1alpha1/pipeline_types.go
- controller/api/v1alpha1/zz_generated.deepcopy.go
- controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
- controller/go.mod
- controller/go.sum
- controller/internal/controller/pipeline_controller_attributes.go
- controller/internal/utils/kubernetes.go
promotion criteria should be able to take a prAutomationRef to bind to a pr automation
> feat: extend promotion criteria with PR automation ref

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/git.ex
- schema/schema.graphql
I think pull requests status field
n/a
> Fix null constraint for status

- assets/src/components/cd/cluster/ClusterNodes.tsx
- assets/src/components/cd/services/component/ServiceComponent.tsx
- assets/src/components/cluster/nodes/ClusterGauges.tsx
- assets/src/components/cluster/nodes/ClusterMetrics.tsx
- assets/src/components/cluster/nodes/Nodes.tsx
- assets/src/components/cluster/nodes/SaturationGraphs.tsx
- assets/src/components/contexts/DeploymentSettingsContext.tsx
- assets/src/components/hooks/usePersistedState.tsx
- assets/src/components/layout/Console.tsx
- assets/src/routes/cdRoutes.tsx
Views now check for existence of prometheus connection before attempting metrics queries.
> fix: byok consoles don't handle metrics properly

- lib/console/schema/pr_automation.ex
- test/console/deployments/git_test.exs
prevents creation of create-mode pr autos
unit
> fix cast embed call

- lib/console/schema/object_store.ex
- lib/console/schema/service.ex
- test/console/deployments/clusters_test.exs
Omnibus pr for a lot of backup/restore improvements
Fixes ENG-1781, ENG-1781, ENG-1803
unit
> Default templated to true and other backup/restore fixes

- charts/velero/templates/secret.yaml
Forgot to commit in the previous PR.
> fix: Fix velero secret

- Dockerfile
- lib/console/schema/pr_automation.ex
- test/console/deployments/git_test.exs
Adds some more pr automation features
n/a
> Bump plural cli in docker

- lib/console/deployments/services.ex
We need to see if its a fixed chart.
n/a
> Properly check helm chart config for multisource

- assets/src/generated/graphql.ts
- config/prod.exs
- lib/console/deployments/backups.ex
- lib/console/deployments/notifications.ex
- lib/console/deployments/pubsub/consumers/notifications.ex
- lib/console/deployments/pubsub/protocols/notifiable.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/deployments/notification.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/deployments/notification.ex
- lib/console/schema/notification_router.ex
- lib/console/schema/notification_sink.ex
- lib/console/schema/router_filter.ex
- lib/console/schema/router_sink.ex
- priv/notifications/slack/cluster.create.json.eex
- priv/notifications/slack/pipeline.update.json.eex
- priv/notifications/slack/service.update.json.eex
- priv/notifications/teams/service.update.json.eex
- priv/repo/migrations/20240222232242_add_notification_routing.exs
- schema/schema.graphql
- test/console/deployments/backups_test.exs
- test/console/deployments/notifications_test.exs
- test/console/deployments/pubsub/notification_test.exs
- test/console/graphql/mutations/deployments/notification_mutations_test.exs
- test/console/graphql/queries/deployments/notification_queries_test.exs
- test/support/factory.ex
- test/support/test_helpers.ex
Adds a fully configurable system for routing and delivering notifications.  The goal will be to bake this into a set of crds alongside other tooling
unit tests
> Notification Router APIs

- assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
- assets/src/components/cd/services/service/ServiceKick.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdServices.graphql
- controller/internal/controller/pipeline_controller_attributes.go
- controller/internal/controller/pipeline_controller_test.go
Looks like we're trying to fetch a cluster ref that need not be there and that's causing some issues
n/a
> feat: Fix crash in controller on pr automation pipelines

- charts/console/Chart.yaml
- charts/console/templates/ingress.yaml
- charts/console/values.yaml
Can be needed for people who set up tls termination at cloud load balancer
local template
> Allow console tls to be disabled

- assets/src/generated/graphql.ts
- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- controller/Makefile
- controller/api/v1alpha1/prautomation_types.go
- controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- controller/go.mod
- controller/go.sum
- lib/console/graphql/deployments/pipeline.ex
- lib/console/schema/stage_service.ex
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
- schema/schema.graphql
Needed for the simpler update-mode form
n/a
> Add new fields for pr automation regex replacements

- lib/console/deployments/git.ex
- lib/console/deployments/pipelines.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/deployments/pr/impl/gitlab.ex
- test/console/deployments/pipeline_test.exs
- test/console/deployments/pubsub/recurse_test.exs
Adding owner where needed, will try to figure out how to add labels
n/a
> Flesh out more attributes for pr generation

- assets/src/components/cd/pipelines/nodes/StageNode.tsx
- assets/src/components/pr/queue/PrQueueColumns.tsx
> feat: Move PR link column to left

- lib/console/deployments/events.ex
- lib/console/deployments/git.ex
- lib/console/deployments/pipelines.ex
- lib/console/deployments/pubsub/protocols/notifiable.ex
- lib/console/schema/notification_router.ex
- priv/notifications/slack/pipeline.update.json.eex
- priv/notifications/slack/pr.close.json.eex
- priv/notifications/teams/pipeline.update.json.eex
- priv/notifications/teams/pr.close.json.eex
- test/console/deployments/pubsub/notification_test.exs
It's also usefult to know when these happen, especially to know if a pipeline needs attending
unit
> Deliver notifications for pr close/merge events

- assets/src/components/cd/pipelines/nodes/StageNode.tsx
- assets/src/components/help/CountBadge.tsx
> feat: Show badge with open PR count in Pipeline Stage nodes

- assets/src/components/pr/queue/PrQueueColumns.tsx
- lib/console/deployments/services.ex
- lib/console/schema/service.ex
- test/console/deployments/services_test.exs
Not sure if there are actually some other fields worth pinning, there is a justification to allow repository to be changable along w/ other things.
unit test
> Make cluster id immutable for services

- assets/src/generated/graphql.ts
- lib/console/deployments/policies/rbac.ex
- lib/console/deployments/policy.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/deployments/pr/impl/gitlab.ex
- lib/console/external_graphql.ex
- lib/console/graphql.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/notification.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/policies.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/deployments/base.ex
- lib/console/graphql/resolvers/deployments/policy.ex
- lib/console/schema/constraint_violation.ex
- lib/console/schema/policy_constraint.ex
- priv/repo/migrations/20240307164829_add_constraints_violations.exs
- schema/schema.graphql
- test/console/deployments/policy_test.exs
- test/console/graphql/mutations/deployments/policy_mutations_test.exs
- test/console/graphql/queries/deployments/cluster_queries_test.exs
- test/console/graphql/queries/deployments/policy_queries_test.exs
- test/support/factory.ex
Apis to register OPA gatekeeper constraints across clusters, and aggregate any constraints found.
unit test
> Implement OPA gatekeeper viz apis

- controller/api/v1alpha1/servicedeployment_types.go
- controller/internal/controller/servicedeployment_controller.go
- controller/internal/controller/servicedeployment_controller_test.go
It's a bit goofy to splat the high level fields into separate keys, easier to just have a canonical named key for the full yaml vals file
unit test
> fix the valuesFrom fetch for service helm values

- assets/src/generated/graphql.ts
- charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
- controller/api/v1alpha1/servicedeployment_types.go
- controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
- controller/internal/controller/servicedeployment_controller.go
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/resolvers/deployments/policy.ex
- lib/console/schema/policy_constraint.ex
- plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
- schema/schema.graphql
- test/console/graphql/queries/deployments/policy_queries_test.exs
Add the ability to filter/aggregate based on namespace/kind
unit
> More advanced policy constraint queries

- charts/controller/crds/deployments.plural.sh_notificationrouters.yaml
- controller/api/v1alpha1/notificationrouter_types.go
- controller/api/v1alpha1/zz_generated.deepcopy.go
- controller/config/crd/bases/deployments.plural.sh_notificationrouters.yaml
- controller/internal/controller/notificationrouter_controller.go
- controller/internal/utils/kubernetes.go
- plural/helm/console/crds/deployments.plural.sh_notificationrouters.yaml
This was currently having sinks passed as ids, which is not an optimal experience when configuring manually as yaml.
existing
> Fix some small issues with notification router reconciliation

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/resolvers/deployments/policy.ex
- lib/console/schema/policy_constraint.ex
- lib/kube/models.ex
- lib/kube/parser.ex
- schema/schema.graphql
Also configure crd parsers to use latest crds for plural resources
n/a
> Small query improvements for policies

- .github/workflows/assets.yaml
- assets/package.json
- assets/src/components/contexts.tsx
- assets/src/helpers/auth.js
- assets/src/helpers/client.js
- assets/src/helpers/refreshToken.ts
- assets/yarn.lock
- config/config.exs
- lib/console/services/users.ex
- Decreases the threshold for token renewal to 5 minutes before expiration
> fix: Refreshing tokens too soon

- static/compatibilities/istio.yaml
Updated istio compatibility to the latest. https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases
> feat: updated istio

- assets/src/components/component/ComponentDetails.tsx
- assets/src/components/component/ComponentInfo.tsx
- assets/src/components/component/info/Conditions.tsx
- assets/src/components/component/info/PluralServiceDeployment.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/kubernetes/pluralServiceDeployment.graphql
> feat: Add proper support for ServiceDeployment in components tab

- assets/src/components/component/ComponentDetails.tsx
> fix: Incorrect cluster id in Component page `View service` link

- assets/codegen.yml
- assets/package.json
- assets/src/generated/fragments.json
- assets/src/helpers/auth.ts
- assets/src/helpers/client.ts
- assets/src/helpers/refreshToken.ts
- assets/yarn.lock
- Prevent accidental logout in potentially rare condition where the user loses connection immediately before attempting to refresh their token
- Update some files to typescript
- Update usage of `InMemoryCache` to use `possibleTypes` instead of deprecated `fragmentMatcher` property
> fix: User could get logged out randomly if they temporarily lost connection

- static/compatibilities/cert-manager.yaml
1.14.0 also compatible w/ k8s 1.28
n/a
> Fix cert manager compatibility

- static/compatibilities/jaeger.yaml
- static/compatibilities/manifest.yaml
Added Jaeger, a graduated cncf project. https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md
> feat: Added Jaeger compatibility

- .github/workflows/chart.yaml
Github action to publish chart is failing due to missing dashboard repo config.
> fix(chart): add missing dashboard repo

- static/compatibilities/rook.yaml
Updated rook compatibility to the latest: https://rook.io/docs/rook/v1.14/Getting-Started/quickstart/#kubernetes-version
> feat: updated rook compatibility

- assets/src/components/cd/ContinuousDeployment.tsx
- assets/src/components/cd/pipelines/job/PipelineJobLogs.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdPipelines.graphql
Adds buttons to allow user to force the gate state on a pipeline job
The buttons only appear if the gates state is `RUNNING` or `PENDING`
it also changes the position of the global services tab
[linear task](https://linear.app/pluralsh/issue/ENG-1821/pipeline-gate-force-openclose-ui#comment-68b96bb4)
> Pipeline gate force open/close UI

- assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
Adds icon to global service detail page distribution
> add distro icon to global service detail

- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdServices.graphql
Limits the service list in the service details page to services within the same cluster
> limit service list to same cluster

- assets/src/components/login/Login.tsx
- assets/src/generated/graphql.ts
- lib/console/deployments/helm/repository.ex
- lib/console/graphql/configuration.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/schema/cluster.ex
- rel/config/console.exs
- schema/schema.graphql
Allows people to customize the "Login with ..." string on the login portal
n/a
> Add custom oidc login name

- assets/package.json
- assets/src/components/kubernetes/Kubernetes.tsx
- assets/yarn.lock
> fix: Kubernetes detail views

- static/compatibilities/flux.yaml
- static/compatibilities/manifest.yaml
Added Flux, a graduated cncf project.  https://fluxcd.io/flux/installation/#prerequisites
> feat: Added flux compatibility

- assets/schema/kubernetes-schema.graphql
- assets/src/components/kubernetes/Kubernetes.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql.ts
- assets/src/routes/kubernetesRoutesConsts.tsx
- assets/src/utils/semver.ts
- lib/console/deployments/git.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/schema/cluster.ex
- priv/repo/migrations/20240410220551_add_cluster_upgrade_plan.exs
- schema/schema.graphql
- test/console/graphql/mutations/deployments/git_mutations_test.exs
Will be needed for new upgrade plan view to provide a persistent checklist of todos for the cluster.
n/a
> Add upgrade plan struct

- lib/console/deployments/pipelines.ex
for pr based pipelines, we can actually use the contexts progression to control the promo process, this should be a lot more straightforward overall.
existing unit tests
> use context id for stage promotion

- controller/internal/controller/managenamespace_test.go
- controller/internal/controller/notificationrouter_test.go
- controller/internal/controller/notificationsink_test.go
Add missing controller's unit tests
> feat: add unit tests

- assets/src/components/cd/clusters/runtime/columns.tsx
- lib/console/deployments/compatibilities/schema.ex
Our current version is actually higher than the top of the table, which triggered a minor version search bug.  This should fix.
n/a
> Fix compatibility view for kps

- .github/workflows/helm.yaml
- lib/console/deployments/pubsub/protocols/broadcastable.ex
- lib/console/deployments/pubsub/protocols/notifiable.ex
- lib/console/schema/router_filter.ex
- priv/notifications/slack/stack.run.json.eex
- priv/notifications/teams/cluster.create.json.eex
- priv/notifications/teams/stack.run.json.eex
- priv/repo/migrations/20240413042954_add_stack_notifications.exs
- test/console/deployments/pubsub/broadcast_test.exs
- test/console/deployments/pubsub/notification_test.exs
Also sets up wss notifs for the agent
unit tests
> Implement notifications for stack runs

- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/NamespaceFilter.tsx
- assets/src/components/kubernetes/Navigation.tsx
- assets/src/components/kubernetes/cluster/HorizontalPodAutoscalers.tsx
- assets/src/components/kubernetes/common/DataSelect.tsx
- assets/src/components/kubernetes/common/NameFilter.tsx
- assets/src/components/kubernetes/common/NamespaceFilter.tsx
- assets/src/components/kubernetes/common/ResourceDetails.tsx
- assets/src/components/kubernetes/common/ResourceList.tsx
- assets/src/components/kubernetes/customresources/CustomResource.tsx
- assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
- assets/src/components/kubernetes/customresources/CustomResourceDefinitions.tsx
- assets/src/components/kubernetes/storage/PersistentVolumeClaims.tsx
- assets/src/components/kubernetes/storage/PersistentVolumes.tsx
- assets/src/components/kubernetes/storage/StorageClasses.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/graph-kubernetes/customresourcedefinition.graphql
- assets/src/routes/kubernetesRoute.tsx
- assets/yarn.lock
- Add custom resource object event lists
- Allow adding custom headers to resource details component
- Add name and namespace filters to custom resource object lists
- Show namespace column only for namespaced custom resource objects
- Allow linking to specific namespace in custom resource object lists
- Export duplicated data select inputs into new component
- Few other smaller fixes and improvements
> feat: Custom resource improvements

- lib/console/deployments/global.ex
- lib/console/schema/global_service.ex
- lib/console/schema/managed_namespace.ex
- lib/console/schema/service.ex
- test/console/deployments/global_test.exs
- test/support/factory.ex
Tries to deref nil when checking if a service currently exists
added unit test
> Fix reconciliation bug w/ templated global services

- static/compatibilities/manifest.yaml
- static/compatibilities/opentelemetry.yaml
Added OpenTelemery, an incubated CNCF project.
Compatibility: https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager
> feat: Added Opentelemetry

- .github/workflows/helm.yaml
- charts/console/values.yaml
- lib/console/deployments/events.ex
- lib/console/deployments/pipelines.ex
- lib/console/deployments/pubsub/recurse.ex
- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
- test/console/deployments/pubsub/recurse_test.exs
seems like cert manager is still being used somehow for some users?
helm template
> Fix dashboard rendering cert-manager

- lib/console/deployments/clusters.ex
- lib/console/deployments/pipelines.ex
- lib/console/schema/pipeline_promotion.ex
- lib/console/services/base.ex
- priv/repo/migrations/20240416204627_add_promoted_revision.exs
- test/console/deployments/clusters_test.exs
Prev fix to check contexts start gates a bit too early, this will wait for contexts and all services to be revised.
n/a
> Tweak pipeline promotion logic a bit more

- assets/src/components/component/ComponentMetrics.tsx
- charts/console/templates/prometheusrule.yaml
- plural/helm/console/Chart.yaml
- plural/helm/console/templates/prometheusrule.yaml
- plural/helm/console/templates/runbooks.yaml
- test-runbook.yml
Context: https://discord.com/channels/880830238723047424/1229549563678031893
> Update memory queries to ensure only containers are measured

- lib/console.ex
- lib/console/deployments/pipelines.ex
- lib/console/graphql/resolvers/deployments/service.ex
- lib/console/schema/revision.ex
- lib/console/services/base.ex
- priv/notifications/slack/cluster.create.json.eex
- priv/notifications/slack/pipeline.update.json.eex
- priv/notifications/slack/pr.close.json.eex
- priv/notifications/slack/service.update.json.eex
- priv/notifications/slack/stack.run.json.eex
Need a reliable means of determining all services have been revised after a context was applied, think this does it.
n/a
> Another fix for pipeline logic

- Dockerfile
> Use old agent version until plural cd install is fixed

- static/compatibilities/kyverno.yaml
- static/compatibilities/manifest.yaml
Added Kyverno, a CNCF project. https://kyverno.io/docs/installation/#compatibility-matrix
> feat: Added Kyverno

- charts/console/Chart.yaml
- charts/console/templates/ingress.yaml
Used the wrong schema for the backend service on rewrites
n/a
> Fix helm chart bug

- assets/src/generated/graphql.ts
- lib/console/deployments/observability.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/deployments/observability.ex
- lib/console/graphql/resolvers/deployments/observability.ex
- lib/console/schema/observability_provider.ex
- priv/repo/migrations/20240423003326_add_observability_providers.exs
- schema/schema.graphql
- test/console/deployments/observability_test.exs
- test/console/graphql/mutations/deployments/observability_mutations_test.exs
- test/console/graphql/queries/deployments/observability_queries_test.exs
- test/support/factory.ex
This will be used for auto-cancellation of terraform runs and for observability gates
unit tests
> Add observability provider CRUD

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/schema/gates/job_spec.ex
- lib/console/schema/stack_environment.ex
- lib/console/schema/stack_file.ex
- lib/console/schema/stack_state.ex
- schema/schema.graphql
- test/console/graphql/mutations/deployments/stack_mutations_test.exs
Seems like a lot were due to forgetting to add timestamps to schema and a few typos.
Fix ENG-1996 ENG-1997 ENG-1999 ENG-2001
unit test
> Fix myriad stack bugs

- lib/console/schema/stack_environment.ex
> Fix stack secret persistence

- assets/src/components/pr/automations/PrAutomationsColumns.tsx
> leave role columns empty when there is no role on PR automation table

- assets/package.json
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/components/cd/services/ClusterTagsFilter.tsx
- assets/yarn.lock
> use design system tag multi select in cluster filter

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/policy.ex
- schema/schema.graphql
> Add cluster to policy constraint

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/service.ex
- lib/console/schema/service.ex
- schema/schema.graphql
Need to add follow-on agent+controller changes as well
n/a
> Add release name to helm spec

- assets/src/generated/graphql.ts
- lib/console/deployments/global.ex
- lib/console/deployments/services.ex
- lib/console/graphql/deployments/global.ex
- lib/console/schema/global_service.ex
- lib/console/schema/managed_namespace.ex
- lib/console/schema/service_dependency.ex
- lib/console/schema/service_template.ex
- priv/repo/migrations/20240425230757_dependency_template.exs
- schema/schema.graphql
- test/console/deployments/global_test.exs
Forgot to add this to the list of attributes managed by a global service.  Should now diff and copy dependency records across.
unit tests
> Sync service dependencies in global services

- assets/src/generated/graphql.ts
- lib/console.ex
- lib/console/deployments/cron.ex
- lib/console/deployments/git.ex
- lib/console/deployments/pipelines.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/deployments/pr/impl/gitlab.ex
- lib/console/deployments/pr/utils.ex
- lib/console/deployments/pubsub/recurse.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/pull_request.ex
- lib/console/schema/stack.ex
- lib/console/schema/stack_run.ex
- lib/console_web/controllers/webhook_controller.ex
- priv/repo/migrations/20240427164952_add_pull_request_stack.exs
- schema/schema.graphql
- test/console/deployments/stacks_test.exs
- test/console/graphql/queries/deployments/stack_queries_test.exs
- test/console_web/controllers/webhook_controller_test.exs
Handles mapping incoming PRs to stacks and spawning dry runs for new commits on the branch created for that pr.  This process continues until the pr is closed.
unit tests
> Stack Pull Request workflow

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/graphql/resolvers/deployments/service.ex
- lib/console/schema/pull_request.ex
- lib/console/schema/service.ex
- schema/schema.graphql
Will be used in new homepage designs, only returns services w/ associated errors
n/a
> Add errored filter for services

- assets/src/components/cd/pipelines/nodes/ApprovalNode.tsx
- assets/src/components/cd/pipelines/nodes/StageNode.tsx
- assets/src/components/utils/SplitPane.tsx
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/pipelineRoutes.tsx
The console was getting pretty cluttered with random warnings, this fixes at least the ones that are thrown in every route
> fix dev mode console warnings

- lib/console/deployments/clusters.ex
- lib/console/graphql/exceptions/protocol.ex
- lib/console/graphql/middleware/error_handler.ex
- lib/console/schema/cluster.ex
- lib/console/schema/service.ex
- priv/repo/migrations/20240503234630_nilify_owner_id.exs
- test/console/deployments/clusters_test.exs
- test/console/deployments/global_test.exs
> Better fk constraint error messages

- assets/src/generated/graphql.ts
- lib/console/deployments/global.ex
- lib/console/graphql/deployments/global.ex
- lib/console/schema/global_service.ex
- priv/repo/migrations/20240503234630_nilify_owner_id.exs
- schema/schema.graphql
> fix owner id

- assets/package.json
- assets/src/components/apps/Apps.tsx
- assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/components/cd/clusters/ClustersColumns.tsx
- assets/src/components/cd/pipelines/PipelinePullRequests.tsx
- assets/src/components/cd/pipelines/Pipelines.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/ServicesTable.tsx
- assets/src/components/cd/utils/useFetchPaginatedData.tsx
- assets/src/components/home/Home.tsx
- assets/src/components/home/HomeCard.tsx
- assets/src/components/home/MonthlyClusterCostsCard.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
- assets/src/components/home/clusteroverview/CustomLegend.tsx
- assets/src/components/home/deployments/DeploymentsCard.tsx
- assets/src/components/home/deployments/DeploymentsTable.tsx
- assets/src/components/home/pullrequests/PrCard.tsx
- assets/src/components/home/pullrequests/PrTable.tsx
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/pr/queue/PrQueue.tsx
- assets/src/components/pr/queue/PrQueueColumns.tsx
- assets/src/components/utils/RadialBarChart.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdPrs.graphql
- assets/src/graph/home.graphql
- assets/src/routes/consoleRoutes.tsx
- assets/yarn.lock
Added IC view (only view currently) for the home screen
Also consolidated the pagination logic used by a lot of our tables into a more generic hook (only refactored the tables that shared data with the homepage but it could likely be applied elsewhere)
> added home screen

- assets/src/components/cd/services/service/ServiceErrors.tsx
Will make the service error table a little cleaner
> added pre-formatted code block for service errors

- static/compatibilities/opentelemetry.yaml
Updated Opentelemetry compatibility to latest version
https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager
> feat: updated open telemetry compatibility

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/stack.ex
- schema/schema.graphql
Think this might be confusing the go client
n/a
> Move stack_state_resource.configuration to map type

- assets/src/components/cluster/containers/ContainerShell.tsx
quick fix, bug was preventing pod shell from loading
> fix: pod shell id missing colon

- assets/src/generated/graphql.ts
- lib/console/graphql/kubernetes.ex
- schema/schema.graphql
Only added this to the external gql schema apparently
n/a
> Add group, version, kind to kubernetes unstructured

- assets/src/components/cd/services/ServicesTable.tsx
- assets/src/components/home/HomeCard.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
- assets/src/components/home/deployments/DeploymentsCard.tsx
- assets/src/components/home/pullrequests/PrCard.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/graph-kubernetes/cluster/node.graphql
- assets/src/graph-kubernetes/common/fragments.graphql
Fragments were missing `cpuLimits` and `memoryLimits` which prevented limits from being displayed.
Edit: I have also pushed some smaller fixes for home view tables.
> fix: Fix node limits display

- lib/console/deployments/git/cmd.ex
occasionally this will send nil into the cmd
unit test
> Fix git log

- assets/src/generated/graphql.ts
- lib/console/deployments/cron.ex
- lib/console/graphql/deployments/observability.ex
- schema/schema.graphql
Forgot to expose this in the schema
n/a
> Add newrelic credentials input to gql

- assets/src/components/pr/queue/DeletePr.tsx
- assets/src/components/pr/queue/PrQueueColumns.tsx
- assets/src/components/pr/queue/PrSettings.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdPrs.graphql
Added a dropdown to manually delete a PR or update its status if needed
> added actions to PR table

- assets/src/components/policies/policy/details/PolicyDetails.tsx
- lib/console/deployments/global.ex
Instead of hiding it by default, guide people to setting the right annotation.
n/a
> Better description/recommendation empty state

- assets/src/components/cd/YamlGeneratorModal.tsx
- assets/src/components/cd/globalServices/DeleteGlobalService.tsx
- assets/src/components/cd/globalServices/GlobalService.tsx
- assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
- assets/src/components/cd/globalServices/GlobalServicesColumns.tsx
- assets/src/components/cd/globalServices/GlobalServicesTable.tsx
- assets/src/components/cd/namespaces/Namespaces.tsx
- assets/src/components/cd/namespaces/NamespacesDetailTable.tsx
- assets/src/components/cd/namespaces/NamespacesTable.tsx
- assets/src/components/cd/pipelines/Pipelines.tsx
- assets/src/routes/cdRoutes.tsx
added actions menu to delete a global service manually if needed
also did some cleanup all around CD to clear a few console errors
> add deletion action to global services table

- static/compatibilities/jaeger.yaml
Updated jaeger compatibility
https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md
> feat: updated jaeger compatibility

- assets/src/components/backups/cluster/backups/Backups.tsx
- assets/src/components/backups/cluster/restores/Restores.tsx
- assets/src/components/backups/clusters/Clusters.tsx
- assets/src/components/backups/objectstores/ObjectStores.tsx
- assets/src/components/cd/utils/useFetchPaginatedData.tsx
- assets/src/components/kubernetes/workloads/utils.tsx
- assets/src/components/notifications/routers/NotificationRouters.tsx
- assets/src/components/notifications/sinks/NotificationSinks.tsx
- assets/src/components/policies/Policies.tsx
- assets/src/components/policies/PoliciesTable.tsx
- assets/src/components/pr/automations/PrAutomations.tsx
- assets/src/components/pr/scm/PrScmConnections.tsx
- assets/src/components/pr/scm/ScmWebhooks.tsx
Condensed remainder of the relevant tables to use the useFetchPaginatedData hook
cleaned up a couple more bugs that could cause infinite loops (React was throwing Maximum update depth exceeded)
fixed a few breadcrumbs
> console bug fixes and cleanup

- assets/src/components/policies/PoliciesFilter.tsx
Added chips next to the filters with the violation count
> show counts next to constraint multi-select options

- lib/console/deployments/git/cache.ex
- test/console/deployments/git/agent_test.exs
Slight bug in plumbing in the right sha, added test to cover.
unit test
> Stack runs didn't have messages for first run

- assets/src/components/layout/Sidebar.tsx
- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/stack.ex
- schema/schema.graphql
Forgot to add this before
unit test
> Add support for searching stacks

- assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
- assets/src/components/home/deployments/DeploymentsCard.tsx
- assets/src/components/home/deployments/DeploymentsTable.tsx
- assets/src/components/home/pullrequests/PrCard.tsx
- assets/src/components/home/pullrequests/PrTable.tsx
- assets/src/components/utils/SkeletonLoaders.tsx
for chart and table views. better method to do these repeatably should be investigated
> added skeleton loaders to home screen

- assets/src/components/pr/queue/PrQueueColumns.tsx
Not sure how this was introduced tbh, but this is a trivial fix
local
> Fix bug in pr display on pipelines

- controller/internal/controller/servicedeployment_controller.go
Delete service when cluster doesn't exist
> fix service deletion

- .vscode/settings.json
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/policies/Policies.tsx
- assets/src/components/policies/PoliciesViolationsGauge.tsx
- assets/src/components/policies/usePolicyChartsData.tsx
- assets/src/components/utils/PieChart.tsx
- assets/src/components/utils/SkeletonLoaders.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/policies.graphql
Updated the policy pie chart to reflect data from the new PolicyStatistics query
Also added a couple more charts
> added more policy charts

- static/compatibilities/istio.yaml
Updated istio compatibility 
https://istio.io/latest/news/releases/1.22.x/announcing-1.22/
> feat: updated istio compatibility

- assets/src/components/policies/Policies.tsx
- assets/src/components/policies/PoliciesFilter.tsx
- assets/src/components/policies/PoliciesViolationsGauge.tsx
- assets/src/components/policies/usePolicyChartsData.tsx
- assets/src/routes/policiesRoutes.tsx
Temporarily took out the search bar, fixed up some of the margins, and made the subpages scroll instead of the full page
> update policy page layout

- assets/src/components/policies/usePolicyChartsData.tsx
was referencing the wrong data object
> fix installed clusters policy chart bug

- plural/helm/console/templates/ingress.yaml
- plural/helm/console/values.yaml
This is currently bugged for some users, just get rid of it now that we have the better solve.
n/a
> Default disable kas rewrite in OSS chart

- assets/package.json
- assets/src/components/layout/Sidebar.tsx
- assets/yarn.lock
also hid the notifications button
> fix sidebar spacing

- assets/package.json
- assets/src/components/tracking/CookieSettings.tsx
- assets/yarn.lock
see https://github.com/pluralsh/design-system/pull/594
> fix cookie settings z-index

- assets/src/components/policies/PoliciesViolationsGauge.tsx
- assets/src/components/utils/PieChart.tsx
removed the gap between bars, added the 45-degree tilt to the parent component, changed the legend style
> tweak policy charts styles

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- schema/schema.graphql
Will be needed to polish the stacks UX
n/a
> Add stack kick api

- assets/src/components/stacks/StackRunStatusChip.tsx
- assets/src/generated/graphql.ts
- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/cmd.ex
- lib/console/deployments/stacks.ex
- lib/console/deployments/stacks/commands.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/schema/stack.ex
- lib/console/schema/stack_run.ex
- lib/console/services/users.ex
- schema/schema.graphql
- test/console/deployments/stacks_test.exs
Allows for custom commands to be execution during stack stage runs.
unit test
> Add ability to specify stack hooks

- static/compatibilities/opentelemetry.yaml
Updated: https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager
Also, there's a [PR open](https://github.com/pluralsh/console/pull/973) that i've responded to.
> feat: updated opentelemetry compatibiliity

- assets/src/components/stacks/run/Sidecar.tsx
- assets/src/components/stacks/run/Sidenav.tsx
- assets/src/components/stacks/run/plan/Plan.tsx
- assets/src/components/stacks/run/progress/Progress.tsx
- assets/src/components/stacks/run/progress/Step.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/stacks.graphql
- lib/console/deployments/pubsub/protocols/notifiable.ex
This mutation has been implemented already, and it's very useful for testing
unit test
> Add a restart run button

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/schema/stack_run.ex
- priv/repo/migrations/20240526202656_add_workdir_to_runs.exs
- schema/schema.graphql
Forgot to add these to the stack run schema
n/a
> Backfill workdir/manage state in a few more places

- controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
- controller/internal/controller/infrastructurestack_controller.go
- recreate stack when it was deleted from the API/UI
- adjust the sample
> fix recreate the stack

- charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
- controller/api/v1alpha1/infrastructurestack_types.go
- controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
- controller/internal/controller/infrastructurestack_test.go
- plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Assume that not-present is the same as false
modified tests
> Allow detach to be optional

- static/compatibilities/contour.yaml
- static/compatibilities/manifest.yaml
Added Contour,a graduated CNCF Service proxy Project. 
https://projectcontour.io/resources/compatibility-matrix/
> feat: added contour compatibility

- assets/src/components/builds/build/progress/CommandLog.tsx
- plural/helm/console/Chart.yaml
- plural/helm/console/templates/deployment.yaml
Didn't stringify the port num
n/a
> Fix prometheus port in OSS chart

- charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
- charts/controller/crds/deployments.plural.sh_pipelines.yaml
- controller/api/v1alpha1/pipeline_types.go
- controller/api/v1alpha1/zz_generated.deepcopy.go
- controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
- controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
- controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
- controller/internal/controller/common.go
- controller/internal/controller/infrastructurestack_test.go
- plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
- plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
Use a batchv1.JobSpec for pipelinegate/stacks spec.jobSpec.raw
> feat: use a batchv1.JobSpec for pipelinegate/stacks spec.jobSpec.raw

- assets/src/components/cd/clusters/create/CreateCluster.tsx
- assets/src/components/cd/clusters/create/NameVersionHandle.tsx
guides people to `plural cd clusters bootstrap` instead of `plural cd install`
> changed create cluster modal command suggestions

- lib/console/deployments/policies/policies.ex
- lib/console/deployments/stacks/state.ex
- lib/console/schema/terraform_state.ex
- lib/console_web/controllers/stack_controller.ex
- test/console_web/controllers/stack_controller_test.exs
Smorgasbord of fixes as we test the http state protocol E2E
unit
> Fixes for terraform state api

- static/compatibilities/flux.yaml
Updated compatibility to latest version: https://fluxcd.io/flux/installation/#prerequisites
> feat: updated flux compatibility

- assets/src/components/stacks/StackJob.tsx
- assets/src/components/stacks/run/Header.tsx
- assets/src/components/stacks/run/job/RunJob.tsx
- assets/src/components/stacks/run/job/RunJobPods.tsx
- assets/src/components/stacks/run/job/RunJobSpecs.tsx
Mostly styling/routing changes.
> fix: Few fixes for stack and stack run job views

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/deployments/stacks/commands.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/custom_stack_run.ex
- lib/console/schema/service_error.ex
- lib/console/schema/stack_run.ex
- schema/schema.graphql
- test/console/deployments/stacks_test.exs
- test/console/graphql/mutations/deployments/stack_mutations_test.exs
Needed to be able to execute an ansible type stack (still needs harness changes to execute e2e though)
unit test
> Add ansible stack run commands

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- schema/schema.graphql
> Add get for custom stack runs

- static/compatibilities/keda.yaml
- static/compatibilities/manifest.yaml
Added Keda, a graduated CNCF project.
Keda: https://keda.sh/docs/2.14/operate/cluster/#kubernetes-compatibility
> feat: added Keda compatibility

- assets/src/components/cd/services/DetachService.tsx
- assets/src/generated/graphql.ts
- controller/docs/api.md
- controller/internal/controller/globalservice_controller.go
- lib/console/deployments/global.ex
- lib/console/graphql/deployments/global.ex
- lib/console/graphql/resolvers/deployments/global.ex
- schema/schema.graphql
- test/console/deployments/global_test.exs
- test/console/graphql/mutations/deployments/global_mutations_test.exs
Think we weren't properly handling reparent, controller requeue nuances and more
Fixes PROD-2206
unit
> Fix some global service edge cases

- assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
- assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
- assets/src/components/cd/globalServices/GlobalServiceSidecar.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdGlobalServices.graphql
Also some minor styling changes to global service details screen
> add global service kick button

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/stack.ex
- lib/console/schema/stack.ex
- lib/console/schema/tag.ex
- priv/repo/migrations/20240606213310_add_tag_stacks.exs
- schema/schema.graphql
It's sort of clear we'll need this for proper search/filter on stacks
n/a
> Add stack tags

- assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
- assets/src/components/policies/Policies.tsx
- assets/src/components/policies/policy/Policy.tsx
- assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
- assets/src/components/policies/policy/details/PolicyDetails.tsx
- assets/src/routes/kubernetesRoutesConsts.tsx
> feat: Point to resources in dashboard view from policy affected resources

- assets/src/components/home/HomeCard.tsx
- assets/src/components/home/managerview/violations/ConstraintViolationsCard.tsx
- assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
- assets/src/components/pr/scm/CreateScmWebhook.tsx
also fixed a small flickering issue on the home screen violations table
> add doctexts for create scm webhook

- assets/package.json
- assets/src/components/cd/clusters/ClusterUpgrade.tsx
- assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
- assets/src/components/cd/clusters/ClustersColumns.tsx
- assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
- assets/src/components/cd/clusters/runtime/columns.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
- assets/src/components/policies/PoliciesTable.tsx
- assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
- assets/yarn.lock
UX tweaks mostly on the upgrade plan flyover reflecting the new designs
> upgrade plan visual improvements

- .tool-versions
- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/cluster.ex
- lib/console/schema/stack.ex
- priv/repo/migrations/20240607224921_add_kubelet_vsn.exs
- priv/repo/migrations/20240608041954_add_stack_lock.exs
- schema/schema.graphql
Will be used to visualize the lowest kubelet version on all nodes which can help w/ manual kubernetes upgrades
n/a
> Add kubelet version to cluster schema

- controller/cmd/main.go
- controller/go.mod
- controller/go.sum
- controller/internal/cache/user_group.go
- controller/internal/controller/cluster_controller.go
- controller/internal/controller/common.go
- controller/internal/controller/infrastructurestack_controller.go
- controller/internal/controller/servicedeployment_controller.go
- controller/internal/types/reconciler.go
Extend controller for user/group cache
> add user/group cache

- static/compatibilities/opentelemetry.yaml
https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager
> feat: updated opentelemetry compatibility

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks/commands.ex
- lib/console/schema/run_step.ex
- schema/schema.graphql
Will make it easier to encode specialized logic for destroys
n/a
> Add explicit destroy stage for stack runs

- assets/src/components/cd/cluster/ClusterPermissions.tsx
- assets/src/components/cd/pipelines/DeletePipeline.tsx
- assets/src/components/cd/pipelines/PipelinePermissions.tsx
- assets/src/components/cd/pipelines/PipelinesColumns.tsx
- assets/src/components/cd/services/ServicePermissions.tsx
- assets/src/components/cd/utils/PermissionsModal.tsx
- assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
- assets/src/components/utils/hooks.ts
- assets/src/generated/graphql.ts
- assets/src/graph/cdPipelines.graphql
- assets/src/graph/cdServices.graphql
adds ability to edit pipeline permissions
> add three dot actions to pipelines table

- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/component/ComponentDetails.tsx
- assets/src/components/component/ComponentInfo.tsx
- assets/src/routes/cdRoutesConsts.tsx
made raw yaml the default when there's not much info
also fixed a routing bug when navigating from service -> component details
> change unstructured component default path

- charts/console/Chart.yaml
- charts/controller/Chart.yaml
- charts/controller/templates/manager-rbac.yaml
- plural/helm/console/Chart.yaml
Didn't grant access to the project group, fixing now
n/a
> Fix chart rbac

- assets/package.json
- assets/src/components/cd/ContinuousDeployment.tsx
- assets/src/components/kubernetes/Navigation.tsx
- assets/src/components/kubernetes/workloads/Workloads.tsx
- assets/yarn.lock
bumps design system to reflect https://github.com/pluralsh/design-system/pull/608 (needs to be merged first)
> add new arrow scroll for subtabs

- controller/api/v1alpha1/globalservice_types.go
- controller/internal/controller/common.go
- controller/internal/controller/globalservice_controller.go
> refactor: Refactor global service controller

- assets/src/components/stacks/Stacks.tsx
- assets/src/components/stacks/run/Route.tsx
- Fix stack view scrollbar being always visible on tabs list
Locally
> fix: update stack run view when stack run is deleted

- lib/console/deployments/git/cmd.ex
- lib/console/deployments/pr/git.ex
Forgot to do this in the prior pr
n/a
> Add gh app auth to pr automation flow too

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/git.ex
- schema/schema.graphql
> Need to move connectionId to GitAttributes not ScmConnectionAttributes

- assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
> fix home page math error

- static/compatibilities/velero.yaml
updated velero compatibility
https://github.com/vmware-tanzu/velero?tab=readme-ov-file#velero-compatibility-matrix
> feat: updated velero compatibility

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/kubernetes/rollout.ex
- lib/console/graphql/resolvers/kubernetes.ex
- lib/kube/client.ex
- lib/kube/models.ex
- schema/schema.graphql
- static/crds/rollout.yaml
Will be needed to provide a clear argo-rollout view in service components
n/a
> Add argo rollout types to gql api

- charts/controller/crds/deployments.plural.sh_customstackruns.yaml
- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- controller/api/v1alpha1/prautomation_types.go
- controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
- controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- controller/config/samples/pr_automation.yaml
- plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
> feat: Update PR automation CRD and UI

- static/compatibilities/argo-rollouts.yaml
Updated argo rollout compatibility
https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/e2e.yaml#L40-L44
> feat: updated argo compatibility

- lib/console/graphql/resolvers/deployments.ex
Need to add it to the query whitelist
n/a
> Fix sideload of service imports

- assets/src/components/cd/clusters/ClustersColumns.tsx
Annotate it in the column not the header to match k8s version styling
local
> Change way kubelet vsn is displayed

- .github/workflows/crd-docs.yaml
- controller/docs/api.md
These can be easily forgotten, add gh action to auto-gen them
n/a
> Autogen CRD docs in console repo

- assets/src/generated/graphql.ts
- charts/console/templates/ingress.yaml
- lib/console/graphql/deployments/cluster.ex
- schema/schema.graphql
This got muddled with the now-deprecated rewrite ingress handling.  Just ditch that since we have a more mature solution now anyway.
n/a
> Fix external ingress

- assets/src/generated/graphql.ts
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/stack.ex
- schema/schema.graphql
- test/console/graphql/mutations/deployment_mutations_test.exs
Currently not covered and can make some frontend code simpler
unit test
> Add stacks to `updateRbac`

- charts/console/templates/prometheusrule.yaml
- charts/console/values.yaml
tested in a personal server with a custom console and Prometheus deployment
> enhancement: use prometheus k8s label

- assets/src/generated/graphql.ts
- controller/internal/controller/pipeline_controller.go
- controller/internal/controller/pipeline_controller_attributes.go
- controller/internal/controller/pipeline_controller_test.go
- controller/internal/controller/pipelinecontext_controller.go
- lib/console/deployments/pipelines.ex
- lib/console/deployments/pipelines/stage_worker.ex
- lib/console/deployments/pr/utils.ex
- lib/console/deployments/pubsub/recurse.ex
- lib/console/deployments/stacks.ex
- lib/console/exceptions.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/exceptions/protocol.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/pipeline_stage.ex
- lib/console/schema/service_error.ex
- priv/pr/succeeded.md.eex
- priv/repo/migrations/20240626190945_add_pipeline_errors.exs
- schema/schema.graphql
- test/console/deployments/pipeline_test.exs
- test/console/deployments/stacks_test.exs
I'm not sure we'd trigger comments appropriately w/ current logic, this should improve it
unit test fix
> Add stack pr comments on StackUpdated events

- assets/package.json
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/component/ComponentDetails.tsx
- assets/src/components/component/ComponentInfo.tsx
- assets/src/components/component/ComponentMetadata.tsx
- assets/src/components/component/directory.tsx
- assets/src/components/component/info/Canary.tsx
- assets/src/components/component/info/Certificate.tsx
- assets/src/components/component/info/CronJob.tsx
- assets/src/components/component/info/Daemonset.tsx
- assets/src/components/component/info/Deployment.tsx
- assets/src/components/component/info/Job.tsx
- assets/src/components/component/info/PluralServiceDeployment.tsx
- assets/src/components/component/info/Service.tsx
- assets/src/components/component/info/StatefulSet.tsx
- assets/src/components/component/info/common.tsx
- assets/src/components/component/info/rollout/Rollout.tsx
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/cdRoutesConsts.tsx
- assets/yarn.lock
frees up a lot of space in the info view on structured components
also cleaned up and standardized other info view layouts
> move component metadata to separate tab

- assets/src/utils/cmdLineParse.test.ts
- assets/src/utils/cmdLineParse.ts
Just uses two-pointer lookaheads to accomplish this
unit test
> Add mutli-line script parsing

- assets/src/components/stacks/Stacks.tsx
> feat: Add icons to stack menu items

- assets/package.json
- assets/src/components/account/audits/AuditsList.tsx
- assets/src/components/apps/app/runbooks/runbook/RunbookExecutions.tsx
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/pr/automations/PrConfigurationFields.tsx
- assets/src/components/stacks/Stacks.tsx
- assets/src/components/stacks/customrun/StackCustomRun.tsx
- assets/src/components/stacks/customrun/StackCustomRunChooseTemplate.tsx
- assets/src/components/stacks/customrun/StackCustomRunCommands.tsx
- assets/src/components/stacks/customrun/StackCustomRunModal.tsx
- assets/src/components/stacks/customrun/StackCustomRunSettings.tsx
- assets/src/components/stacks/run/progress/Progress.tsx
- assets/src/components/utils/table/StackedText.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/automation.graphql
- assets/src/graph/stacks.graphql
- assets/src/utils/cmdLineParse.test.ts
- assets/src/utils/cmdLineParse.ts
- assets/src/utils/graphql.ts
- assets/yarn.lock
also added support for blank lines and comments to script parser
> add custom stack run ui

- assets/index.html
quick fix, took out "Web site created using create-react-app"
> fix open embed

- assets/src/components/component/tree/ComponentTreeNode.tsx
- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/Navigation.tsx
also fixed a bug where user couldn't go back after navigating to the K8s dashboard
> add k8s dashboard link to service component tree view

- lib/console_web/endpoint.ex
- lib/console_web/plugs/secure_headers.ex
to check some mostly needless security boxes
regression
> Add iframe headers

- charts/controller/templates/manager-rbac.yaml
This wasn't regenerated prior to release, causing some issues
n/a
> Fix controller chart rbac

- charts/controller/templates/manager-rbac.yaml
I think it might be a pluralization bug
n/a
> Another stab at fixing chart rbac

- .vscode/settings.json
- assets/index.html
- assets/package.json
- assets/src/App.tsx
- assets/src/components/help/DocSearchStyles.tsx
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/layout/Subheader.tsx
- assets/src/components/stacks/state/StackStateGraph.tsx
- assets/yarn.lock
updated DS and made a couple small tweaks accordingly
> light mode fixes

- controller/go.mod
- controller/go.sum
- controller/internal/client/console.go
- controller/internal/client/project.go
- controller/internal/controller/namespace_credentials_controller.go
- controller/internal/controller/project_controller.go
- controller/internal/controller/service_account_controller.go
- controller/internal/test/mocks/ConsoleClient_mock.go
The api supports this now for fully emptied projects, so integrate it w/ the operator as well.
e2e
> Delete project via operator

- assets/src/components/cd/globalServices/details/GlobalServiceServices.tsx
switched the list of services associated with a global service to be displayed with the standard services table columns
> update global service services table component

- assets/src/components/kubernetes/workloads/Pod.tsx
- assets/src/routes/kubernetesRoute.tsx
> feat: Add shell view for pods in k8s dashboard

- assets/src/generated/graphql.ts
- lib/console/deployments/settings.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/project.ex
- schema/schema.graphql
> Add ability to `updateRbac` projects

- assets/src/components/profile/AccessTokens.tsx
- assets/src/components/profile/MyProfile.tsx
- assets/src/components/profile/Permissions.tsx
- assets/src/components/profile/Profile.tsx
- assets/src/components/profile/Security.tsx
- assets/src/components/settings/Settings.tsx
- assets/src/routes/settingsRoutes.tsx
also fixed up a few breadcrumb issues
> add access tokens view to settings

- charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
- charts/controller/templates/manager-rbac.yaml
- controller/api/v1alpha1/managednamespace_types.go
- controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
- controller/config/samples/deployments_v1alpha1_managednamespace.yaml
- controller/go.mod
- controller/go.sum
- controller/internal/client/console.go
- controller/internal/client/namespace.go
- controller/internal/controller/managednamespace_controller.go
- controller/internal/test/mocks/ConsoleClient_mock.go
- plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
- add namespace field
- display status ID
- improve getting existing namespaces
> improve manage namespace controller

- charts/controller/crds/deployments.plural.sh_globalservices.yaml
- charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
- charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
- controller/api/v1alpha1/servicedeployment_types.go
- controller/api/v1alpha1/zz_generated.deepcopy.go
- controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
- controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
- controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
- controller/internal/controller/common.go
- controller/internal/controller/globalservice_test.go
- controller/internal/controller/servicedeployment_controller_test.go
- plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
- plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
- plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
add support for enforceNamespace in:
- servicedeployments
- global services
- manage namespaces
> add support for enforceNamespace

- assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
- assets/src/components/utils/layout/ResponsiveLayoutSidecarContainer.tsx
- assets/src/routes/settingsRoutes.tsx
typo in global service details
sidecars weren't vertically scrollable
> small cd ui bugs

- assets/src/components/cd/globalServices/details/GlobalService.tsx
- assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
- assets/src/components/cd/namespaces/details/ManagedNamespace.tsx
- assets/src/components/cd/namespaces/details/ManagedNamespaceInfo.tsx
> fix: Fix styling of namespaces and global services details

- assets/src/components/kubernetes/common/ResourceDetails.tsx
> fix: tabs scrollbar on kubernetes resource details views

- assets/src/generated/graphql.ts
- controller/go.mod
- controller/go.sum
- controller/internal/controller/globalservice_controller.go
- controller/internal/controller/managednamespace_controller.go
- controller/internal/controller/project_controller.go
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/stack.ex
- lib/console/schema/tag.ex
- priv/repo/migrations/20240718195049_add_stack_parent_id.exs
- schema/schema.graphql
- test/console/graphql/queries/deployments/stack_queries_test.exs
Also added logic to infer parent ids for global services + managed namespaces
added a unit test
> Fix stack queries for tags

- assets/src/generated/graphql.ts
- controller/go.mod
- controller/go.sum
- controller/internal/controller/infrastructurestack_controller.go
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/tag.ex
- schema/schema.graphql
This should round out all the important objects to track parents on.  Will allow us to flesh out the tree view fully
n/a
> Add parent id to stacks

- charts/controller/crds/deployments.plural.sh_scmconnections.yaml
- controller/api/v1alpha1/prautomation_types.go
- controller/api/v1alpha1/scmconnection_types.go
- controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
- controller/docs/api.md
- lib/console/deployments/pr/impl/bitbucket.ex
- plural/helm/console/crds/deployments.plural.sh_scmconnections.yaml
This is the last important step for bitbucket support
n/a
> Add BitBucket to SCM Connection types

- assets/src/components/CommandPalette.tsx
- assets/src/components/help/HelpLauncher.tsx
- assets/src/components/help/HelpLauncherBtn.tsx
- assets/src/components/help/HelpMenu.tsx
some styling tweaks, removed "ask Plural AI" for the time being
> cleanup help widget

- lib/console/deployments/git/cache.ex
- lib/console/deployments/git/cmd.ex
- test-apps/branch-test/.helmignore
- test-apps/branch-test/Chart.yaml
- test-apps/branch-test/templates/NOTES.txt
- test-apps/branch-test/templates/_helpers.tpl
- test-apps/branch-test/templates/deployment.yaml
- test-apps/branch-test/templates/hpa.yaml
- test-apps/branch-test/templates/ingress.yaml
- test-apps/branch-test/templates/service.yaml
- test-apps/branch-test/templates/serviceaccount.yaml
- test-apps/branch-test/templates/tests/test-connection.yaml
- test-apps/branch-test/values.yaml
- test/console/deployments/git/agent_test.exs
- test/console/graphql/queries/deployments/stack_queries_test.exs
still not sure how this can be repro'ed but it's possible the `pull --rebase` done by the regular fetch interval can cause stray writes in the working dir of a git repository
n/a
> Improved git agent branch handling

- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- charts/controller/templates/manager-rbac.yaml
- controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
We keep getting this happening, just allow controller to handle all resources/verbs w/in our resource api group
> Fix stupid rbac bug

- lib/console/schema/service.ex
> Need to fix the embed config to support updating namespace metadata

- go/client/.gitignore
- go/client/client.go
- go/client/graph/users.graphql
- go/client/graphql.config.yml
- go/client/groups.graphql
Also added `graphql.config.yml` as it will be the same for everyone I think.
> enhancement: Add group queries to client

- assets/package.json
- assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
- assets/src/components/cd/clusters/create/provider/NodeGroup.tsx
- assets/src/components/cd/services/ClusterTagsFilter.tsx
- assets/src/components/help/HelpLauncher.tsx
- assets/src/components/help/HelpLauncherBtn.tsx
- assets/src/components/home/pullrequests/PrCard.tsx
- assets/src/components/kubernetes/common/NamespaceFilter.tsx
- assets/src/components/policies/Policies.tsx
- assets/src/components/policies/PoliciesFilter.tsx
- assets/src/components/pr/scm/EditScmConnection.tsx
- assets/src/components/stacks/create/CreateStackModalFormBasic.tsx
- assets/src/components/stacks/prs/PrStackRunsAccordion.tsx
- assets/src/components/stacks/prs/StackPrs.tsx
- assets/src/components/utils/IconExpander.tsx
- assets/yarn.lock
translates old accordions to use the new version (keeping design/styles intact)
> migrate accordions to new API

- assets/src/generated/graphql.ts
- charts/controller/templates/manager-rbac.yaml
- lib/console/deployments/events.ex
- lib/console/deployments/pipelines.ex
- lib/console/deployments/pubsub/protocols/pipelineable.ex
- lib/console/deployments/pubsub/rtc.ex
- lib/console/deployments/services.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/topic.ex
- mix.exs
- schema/schema.graphql
- test/console/deployments/services_test.exs
Could help make pipeline ui more responsive, but think the bottleneck might be FE graph updates actually
local
> Add pipeline subscription delivery

- Dockerfile
Make sure all recent features incorporated
unit test
> Bump cli vsn to 0.9.13

- go/client/client.go
- go/client/graph/deployment.graphql
> fetch service revision ID and sha

- go/controller/internal/controller/prautomation_controller.go
- go/controller/internal/types/reconciler.go
PR Automation controller doesn't resolve user email or group name bindings
> fix: ensure bindings

- go/client/client.go
- go/client/graph/deployment.graphql
Make sha nullable for updateServiceComponents
> feat: Make sha nullable

- .github/workflows/publish.yaml
We spawn both simultaneously, so can't trample the name
n/a
> Differentiate branch in rapid pr creation

- .github/workflows/publish.yaml
- Makefile
was still referencing console chart a few other places
n/a
> Fix rapid charrt action

- .github/workflows/publish.yaml
> fix gh action issue

- go/controller/internal/types/reconciler.go
- lib/console/deployments/metrics/provider/datadog.ex
- lib/console/deployments/stacks/worker.ex
Some things to address:
* stack definition reconciler not whitelisted ...
* datadog queries needed to be fixed
e2e
> Getting custom stacks working

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments.ex
- schema/schema.graphql
Will be more natural for managing custom stacks
n/a
> Make `configuration` optional in StackAttributes

- go/client/client.go
- go/client/graph/git.graphql
> add identifier to CreatePullRequest mutation

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/pubsub/recurse.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments.ex
- schema/schema.graphql
Also fix dataloader resolver for observable metrics
e2e
> Add cancellation reason to stack run

- go/controller/internal/client/prautomation.go
- go/controller/internal/controller/infrastructurestack_controller.go
- go/controller/internal/controller/prautomation_controller.go
> fix: PR automation bindings

- static/compatibilities/contour.yaml
Updated to latest contour version and fixed wrong wrong compatibility version.
https://projectcontour.io/resources/compatibility-matrix/
> feat: updated contour compatibility

- static/compatibilities/cilium.yaml
- static/compatibilities/contour.yaml
Updated cilium compatibility to latest.
https://docs.cilium.io/en/v1.16/network/kubernetes/requirements/#kubernetes-version
> feat: Updated cilium compatibility

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/helm/agent.ex
- lib/console/graphql/deployments/git.ex
- lib/console/schema/helm_repository.ex
- lib/helm/interface/oci.ex
- priv/repo/migrations/20240805144159_add_helm_repository_error.exs
- schema/schema.graphql
It currently doesn't persist errors in the agent, this will help out there.
n/a
> Add error messaging to native helm repositories

- Dockerfile
secret key was being put in after the build
> fix secret in dockerfile

- assets/src/components/commandpalette/commands.ts
small tweaks and also adds shift key to the main ones
> reconfigure command palette shortcuts

- charts/console-rapid/Chart.yaml
- charts/console/Chart.yaml
Forgot to add this to the prior fix
> Bump chart versions

- lib/console/graphql/resolvers/deployments/git.ex
- test/console/deployments/settings_test.exs
- test/console/graphql/queries/deployments/git_queries_test.exs
This is not sensitive info, and shouldn't have a restrictive authz policy as a result
n/a
> De-authz git fetch

- go/controller/internal/controller/project_controller.go
- lib/console/deployments/pipelines.ex
- lib/console/schema/stage_service.ex
- test/console/deployments/clusters_test.exs
- test/console/deployments/pipelines_test.exs
* Need to fix authz for project pipelines
* others
n/a
> Pre-release fixups

- charts/console/Chart.yaml
- charts/console/templates/secrets.yaml
> Fix formatting of postgres cert secret

- charts/console/Chart.yaml
- charts/console/templates/secrets.yaml
> Fix secret formatting

- charts/console-rapid/Chart.yaml
- charts/console/templates/ingress.yaml
- charts/console/templates/rolebinding.yaml
- config/config.exs
- lib/console/cached/supervisor.ex
- lib/console/policies/users.ex
- rel/config/console.exs
So far:
* disable k8s watchers that aren't rbac-able
n/a
> Fixup loose ends w/ cloud provisioning

- go/controller/internal/controller/cluster_controller.go
- go/controller/internal/controller/deploymentsettings_controller.go
- go/controller/internal/controller/infrastructurestack_controller.go
- go/controller/internal/types/reconciler.go
> fix: Bindings for all resources

- go/client/client.go
- go/client/graph/stack.graphql
> feat(client): add TriggerRun mutation support to the console client

- go/client/client.go
- go/client/graph/stack.graphql
> feat(client): add support for tag entry to stack configuration

- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- lib/console/deployments/pr/dispatcher.ex
- lib/console/deployments/services.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- schema/schema.graphql
The prior implementation of this technically supported liquid-ified values, defer to only using static
n/a
> Fix helm values injection

- priv/pr/stack_summary.md.eex
Github code blocks don't love ANSI text, this will presumably help
n/a
> Wrap tf plans in tf blocks to show properly formatted output

- assets/src/components/apps/app/components/AppComponents.tsx
- assets/src/components/apps/app/components/Components.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
change so all kinds will be deselected by default, but will show everything if no kinds are selected (so user will see all their at first and then can filter if desired)
> tweak service component filtering

- go/client/client.go
- go/client/graph/observabilityprovider.graphql
> feat(client): add optional name arg to observability provider query

- .vscode/settings.json
- assets/src/components/cd/services/ServiceRevisionColumns.tsx
- assets/src/components/cd/services/service/ServiceRevisions.tsx
- assets/src/components/cluster/TableElements.tsx
adds the "current revision" box
> service revision improvements

- lib/helm/interface/http.ex
- test/console/deployments/helm/agent_test.exs
I've just seen this pattern for the first time with Azure Service Operator, so need to support it
n/a
> Support helm relative urls

- assets/src/components/kubernetes/common/DataSelect.tsx
- assets/src/components/utils/IconExpander.tsx
adds a border around the k8s dashboard search and filter components if they currently have values (otherwise you can't tell when the component is collapsed)
> improve discoverability of active search/filters

- assets/src/components/stacks/StackDeletedEmptyState.tsx
- assets/src/components/stacks/Stacks.tsx
> add stack deletion empty state

- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/cmd.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/git_repository.ex
Noticed a few things
* encrypted repos can flap because of failing to decrypt via a bad encryption key, this will not cause it to overclone
n/a
> Minor cloud fixes

- go/controller/api/v1alpha1/cluster_types.go
- go/controller/go.mod
- go/controller/internal/controller/cluster_controller_test.go
- cluster controller can update bindings and name
- fix compilation error
> cluster controller can update bindings and name

- go/client/client.go
- go/client/graph/stack.graphql
> enhancement(client): Allow getting stacks by name

- assets/src/components/stacks/environment/StackEnvironment.tsx
- assets/src/components/stacks/files/StackFiles.tsx
- assets/yarn.lock
> fix: Make stack env and files tables scrollable

- go/client/client.go
- go/client/graph/stack.graphql
Simple client change to expose reading variables via queries. Required by harness to create a file.
> feat(client): add stack variables support

- assets/package.json
- assets/src/components/commandpalette/CommandPaletteDialog.tsx
- assets/yarn.lock
uses the DS modal wrapper but with a lighter background than other modals
closes PROD-2513
> add animation to cmdk modal

- assets/src/generated/graphql.ts
- go/client/client.go
- go/client/models_gen.go
- lib/console/graphql/deployments/stack.ex
- schema/schema.graphql
> change stackrun variables type to Map and regenerate client

- assets/src/components/component/info/rollout/CanarySpecTableColumns.tsx
> add json expander component to canary rollout info

- assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
- assets/src/components/help/HelpLauncherBtn.tsx
- assets/src/components/kubernetes/workloads/Pod.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/graph-kubernetes/workloads/pod.graphql
Also fixes logs scrolling and makes help icon clickable (cursor + hover effect).
> fix: Fix Kubernetes Dashboard pod logs container switching

- assets/src/generated/graphql.ts
- lib/console/deployments/git.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/resolvers/deployments/git.ex
- schema/schema.graphql
- test/console/graphql/mutations/deployments/git_mutations_test.exs
> Add scm webhook delete mutation

- assets/package.json
- assets/src/components/pr/scm/ScmWebhooksColumns.tsx
- assets/src/components/utils/Confirm.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/automation.graphql
- assets/yarn.lock
> add actions menu with delete option to scm webhooks

- go/client/client.go
- go/client/graph/cluster.graphql
Small client change required by the virtual cluster controller in the operator.
> feat(client): add upsertVirtualCluster mutation

- charts/console-rapid/Chart.yaml
- charts/console/templates/deployment.yaml
> Fix helm chart deployment

- charts/console-rapid/Chart.yaml
- charts/console/templates/migration.yaml
- charts/console/values.yaml
inferring from the app version is too annoying
n/a
> Fix oci-auth image tag

- go/client/client.go
- go/client/graph/cluster.graphql
> feat(client): update upsert virtual cluster mutation

- assets/src/components/cd/services/ServicesTableErrors.tsx
- assets/src/components/cd/services/service/ServiceErrors.tsx
new behavior wraps text while still preserving whitespace
> service error text wrap

- lib/console/deployments/cron.ex
- lib/console/schema/app_notification.ex
- test/console/deployments/cron_test.exs
- test/test_helper.exs
the query was not streamed before running
n/a
> fix observer cron

- lib/console_web/router.ex
apparently pipeline views exceed 500
n/a
> Complexity check needs to be increased

- go/client/client.go
- go/client/graph/sharedsecret.graphql
> feat(client): add share secret mutation

- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- go/controller/.golangci.yml
- go/controller/api/v1alpha1/prautomation_types.go
- go/controller/api/v1alpha1/zz_generated.deepcopy.go
- go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- go/controller/docs/api.md
- go/controller/internal/controller/prautomation_attributes.go
- go/controller/internal/utils/kubernetes.go
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
- Add project ref support to pr automation
- Fix lint by refactoring vulnerable method
> feat(controller): add projectref to prautomation crd

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/pipelines/stage_worker.ex
- lib/console/graphql/deployments/git.ex
- lib/console_web/router.ex
- schema/schema.graphql
> Bump complexity

- go/client/client.go
- go/client/graph/cluster.graphql
It will be used by the upgrade insights controller to figure out the correct distro if the user does not provide it.
> feat(client): add distro to mycluster query

- go/client/client.go
- go/client/graph/upgradeinsights.graphql
Required by the upgrade insights controller.
> feat(client): add saveUpgradeInsights mutation

- assets/src/components/settings/global/observability/ObservabilitySettings.tsx
> don't force both loki and prometheus settings to be set

- lib/console/deployments/stacks.ex
- test/console/deployments/stacks_test.exs
It seems to over-run occasionally, will fix in next release
> Drop autospawn behavior

- assets/src/components/login/Login.tsx
> fix: Fix login flash

- lib/console/deployments/observability/metrics.ex
I found this in the console logs when trying to test it.
> fix: prometheus query typo

- go/controller/internal/controller/clusterrestore_controller.go
- go/controller/internal/controller/common.go
- go/controller/internal/controller/customstackrun_controller.go
- go/controller/internal/controller/gitrepository_controller.go
- go/controller/internal/controller/globalservice_controller.go
- go/controller/internal/controller/managednamespace_controller.go
- go/controller/internal/controller/notificationrouter_controller.go
- go/controller/internal/controller/observer_controller.go
- go/controller/internal/controller/pipeline_controller.go
- go/controller/internal/controller/pipeline_controller_attributes.go
- go/controller/internal/controller/prautomation_controller.go
unify handling situation when a referenced object is not found or not ready
> unify handling referenced objects

- go/client/client.go
- go/client/graph/gates.graphql
extend JobSpecFragment with ContainerResources
> feat: extend JobSpecFragment

- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/runtime_service.ex
- lib/console/schema/upgrade_insight_detail.ex
- priv/repo/migrations/20241003160915_insight_detail.exs
- schema/schema.graphql
will be used to enhance the info in some of our scrapers
existing
> add upgrade insights client info and runtime services count

- assets/package.json
- assets/yarn.lock
Contains latest [design system fix](https://github.com/pluralsh/design-system/pull/653) from @jsladerman and fixes kubernetes view tree nav.
Locally
> fix: bump design system to the latest version

- go/client/client.go
- go/client/graph/oauth.graphql
> feat(client): Add OIDC provider mutations

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/oauth.ex
- lib/console/graphql/deployments/oauth.ex
- lib/console/plural/models.ex
- lib/console/plural/queries.ex
- schema/schema.graphql
forgot about this, but it's a required arg for the main oidc apis
n/a
> Add `auth_method` to oidc provider mutations/queries

- go/client/client.go
- go/client/graph/oauth.graphql
> feat(client): Add auth method to OIDC provider fragment

- lib/console/deployments/oauth.ex
fixes auth method default, delete mutaiton, and fetching the auth method (i believe)
n/a
> Fix console-side oidc queries

- assets/src/components/cd/clusters/UpgradeInsights.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
> feat: Show client info for upgrade insights 

- go/client/client.go
- go/client/graph/deployment.graphql
> extend service deployment with imports

- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/settings.ex
- lib/console/schema/deployment_settings.ex
- lib/console/schema/pull_request.ex
- priv/notifications/plural/pr.close.json.eex
- priv/notifications/slack/pr.close.json.eex
- priv/repo/migrations/20241015165546_add_ai_settings.exs
- schema/schema.graphql
Will allow central config of ai settings, defaulting to disabled.  We'll then use it for some troubleshooting and debugging tools throughout the ui.
n/a
> Add ai provider configuration

- assets/package.json
- assets/src/components/apps/app/components/ComponentList.tsx
- assets/src/components/apps/app/components/Components.tsx
- assets/src/components/apps/app/components/misc.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/yarn.lock
> add state filter to service components

- go/client/client.go
- go/client/graph/deployment.graphql
extend service deployment with ignoreHooks
> feat: extend service deployment with ignoreHooks

- assets/src/generated/graphql.ts
- go/client/client.go
- go/client/graph/models.graphql
- go/client/models_gen.go
- lib/console/graphql/deployments/settings.ex
- schema/schema.graphql
- Added missing ai settings to deployment settings gql schema
> feat: update gql schema: add ai settings to deployment settings

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/ai/memoizer.ex
- lib/console/ai/provider.ex
- lib/console/deployments/pubsub/protocols/notifiable.ex
- lib/console/external_graphql.ex
- lib/console/graphql.ex
- lib/console/graphql/ai.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/ai.ex
- lib/console/schema/ai_insight.ex
- lib/console_web/controllers/webhook_controller.ex
- lib/console_web/plugs/token.ex
- lib/console_web/router.ex
- priv/notifications/plural/service.insight.json.eex
- priv/notifications/plural/stack.insight.json.eex
- priv/notifications/slack/service.insight.json.eex
- priv/notifications/slack/stack.insight.json.eex
- priv/notifications/teams/service.insight.json.eex
- priv/notifications/teams/stack.insight.json.eex
- priv/repo/migrations/20241017164615_add_insight_summary.exs
- schema/schema.graphql
- test/console/ai/cron_test.exs
- test/console/graphql/queries/ai_queries_test.exs
- test/console_web/controllers/webhook_controller_test.exs
it can be somewhat annoying having these redeliver constantly, this will prevent them w/in a fixed ttl
unit tests
> deduplicate stack insight notifications

- assets/src/components/apps/app/components/ComponentCard.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/cd/services/service/ServiceInsights.tsx
- assets/src/components/component/ComponentDetails.tsx
- assets/src/components/component/ComponentInsights.tsx
- assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
- assets/src/components/stacks/Stacks.tsx
- assets/src/components/stacks/StacksEntry.tsx
- assets/src/components/stacks/common/StackObservabilityMetrics.tsx
- assets/src/components/stacks/insights/StackInsights.tsx
- assets/src/components/stacks/run/Header.tsx
- assets/src/components/stacks/run/Route.tsx
- assets/src/components/stacks/run/Sidecar.tsx
- assets/src/components/stacks/run/insights/StackRunInsights.tsx
- assets/src/components/stacks/run/job/RunJob.tsx
- assets/src/components/stacks/run/output/Output.tsx
- assets/src/components/stacks/run/plan/Plan.tsx
- assets/src/components/stacks/run/progress/Progress.tsx
- assets/src/components/stacks/run/repository/Repository.tsx
- assets/src/components/stacks/runs/StackRunsEntry.tsx
- assets/src/components/utils/AiInsights.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- assets/src/graph/stacks.graphql
Some small improvements as almost everything was done already.
- Added gradient to insights summary tooltip border
- Added refresh buttons for stack, service and component insights (should it be there for components?)
- Moved stack insights icons before statuses to avoid preserving empty space (it was done to align icons)
- Marked access token as required if AI is enabled
- Fix stack run types
> enhancement: AI UI improvements

- go/client/client.go
- go/client/graph/cluster.graphql
- go/client/graph/deployment.graphql
- go/client/graph/models.graphql
- go/controller/internal/client/cluster.go
- go/controller/internal/client/console.go
- go/controller/internal/test/mocks/ConsoleClient_mock.go
strip down cluster and service sideloads
> feat: strip down cluster and service sideloads

- lib/console/ai/memoizer.ex
- lib/console/graphql/resolvers/ai.ex
- test/console/ai/cron_test.exs
This will prevent new records from being created in subsequent insight runs
unit test
> Stabilize insight id

- README.md
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- config/prod.exs
- go/client/models_gen.go
- lib/console/ai/chat.ex
- lib/console/ai/cron.ex
- lib/console/ai/fixer.ex
- lib/console/ai/policy.ex
- lib/console/ai/provider.ex
- lib/console/graphql.ex
- lib/console/graphql/ai.ex
- lib/console/graphql/resolvers/ai.ex
- lib/console/schema/chat.ex
- lib/console/schema/chat_sequence.ex
- lib/console/services/base.ex
- lib/console/services/users.ex
- priv/repo/migrations/20241026141533_ai_chats.exs
- schema/schema.graphql
- test/console/ai/chat_test.exs
- test/console/graphql/mutations/ai_mutations_test.exs
- test/console/graphql/queries/ai_queries_test.exs
- test/support/factory.ex
Begin implementing apis to persist ai chats, alongside expiration and rollup summarization to keep dataset size clean.
unit tests
> Persisted AI chats

- assets/src/components/kubernetes/Navigation.tsx
- assets/src/components/kubernetes/common/DataSelect.tsx
- assets/src/components/utils/IconExpander.tsx
> feat: Add indicators to dashboard filters

- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/utils/FractionalChip.tsx
> fix service component chip coloring

- .github/workflows/ai-proxy-cd.yaml
- .github/workflows/ai-proxy-ci.yaml
It should only create ai proxy releases when `go/ai-proxy/vX.X.X` tag is created.
> fix: ai-proxy-cd.yaml

- lib/console/ai/provider/anthropic.ex
- lib/console/ai/provider/openai.ex
- lib/console/deployments/init.ex
- lib/console/schema/deployment_settings.ex
- test/console/ai/chat_test.exs
- test/console/ai/cron_test.exs
- test/console/deployments/init_test.exs
- test/console/graphql/mutations/ai_mutations_test.exs
This will make the feature automatically visible to users in their first experience w/ the product which i think could be compelling.
unit test
> Add default setup for ollama on cloud clusters

- assets/src/components/ai/AIPanelOverlay.tsx
- assets/src/components/ai/AISuggestFix.tsx
- assets/src/components/cd/services/service/ServiceInsights.tsx
- assets/src/components/component/ComponentInsights.tsx
- assets/src/components/stacks/insights/StackInsights.tsx
- assets/src/components/stacks/run/insights/StackRunInsights.tsx
- Fixed an issue where suggest a fix panel was not fully displayed due to the parent having `overflow: hidden`.
- Updated suggest a fix button display logic to not show it if there is no actual insight available.
Dev/Boot env
> fix: suggest a fix panel/button

- assets/src/components/ai/ExplainWithAI.tsx
- assets/src/components/ai/ExplainWithAIContext.tsx
- assets/src/components/ai/ExplainWithAIPanel.tsx
- assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- assets/src/graph/aiInsights.graphql
It adds AI verbosity toggle to the AI provider view.
> feat: AI verbosity toggle

- static/compatibilities/cert-manager.yaml
- utils/compatibility/scrapers/cert-manager.py
update cert manager scraper to the new format used on the docs site
> update cert manager scraper

- assets/src/components/ai/AI.tsx
- assets/src/components/ai/AIPinsTable.tsx
- assets/src/components/ai/AIThreadsTable.tsx
- assets/src/components/ai/chatbot/Chatbot.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/stacks/Stacks.tsx
- assets/src/components/utils/SkeletonLoaders.tsx
also fixes horizontal width bug on stacks pages, and a bug with the refetching logic after pinning/unpinning
> add optimistic updating to ai chat messages

- assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
- assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
> feat: add base url to openai settings

- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- lib/console/graphql/ai.ex
- lib/console/graphql/resolvers/ai.ex
- lib/console/schema/ai_pin.ex
- priv/repo/migrations/20241104211145_add_pin_uniq.exs
- schema/schema.graphql
- test/console/graphql/queries/ai_queries_test.exs
can help a few ui views
unit tests
> Add ai pin query by insight/thread id

- go/client/client.go
- go/client/graph/stack.graphql
> feat: stacks improvements

- assets/src/components/ai/AI.tsx
> fix: fix ai tab breadcrumbs

- assets/src/components/cd/clusters/ClustersColumns.tsx
> enhancement: cluster sorting by name, version, health and status (upgrades)

- assets/src/components/ai/AI.tsx
- assets/src/components/ai/explain/ExplainWithAI.tsx
> fix: show explain with ai only if ai is enabled

- go/client/client.go
- go/client/graph/vulnerabilities.graphql
add UpsertVulnerabilities mutation
> feat: add UpsertVulnerabilities mutation

- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/ai.ex
- schema/schema.graphql
Looks like this was just an oversight in schema definition
regression
> Sideload cluster on cluster insight components

- lib/console/ai/chat.ex
- lib/console/ai/fixer.ex
- lib/console/ai/goth_manager.ex
- lib/console/deployments/pubsub/protocols/notifiable.ex
- lib/console/retrier.ex
> Prerelease touchups

- lib/console/retrier.ex
Fix some basic errors being thrown
n/a
> Fix retrier logic

- go/controller/api/v1alpha1/deploymentsettings_types.go
- lib/console/ai/evidence/base.ex
- lib/console/ai/evidence/stack_run.ex
- lib/console/ai/fixer.ex
- lib/console/ai/fixer/base.ex
- lib/console/ai/fixer/parent.ex
- lib/console/ai/fixer/service.ex
- lib/console/ai/fixer/stack.ex
- lib/console/ai/provider.ex
- lib/console/ai/provider/anthropic.ex
* tweak some prompts
* code prompts didn't include source folders
* ...
n/a
> Incremental AI improvements

- static/compatibilities/kyverno.yaml
https://kyverno.io/docs/installation/#compatibility-matrix
> feat: updated kyverno compatibility

- static/compatibilities/keda.yaml
https://keda.sh/docs/2.16/operate/cluster/#kubernetes-compatibility
> feat: updated keda compatibility

- assets/src/components/ai/AITableEntry.tsx
- lib/console/ai/chat.ex
- lib/console/services/users.ex
* email santization
* websocket fixes
unit tests
> Prep release 0.10.40

- assets/src/helpers/client.ts
There are some conditions when these aren't kept alive, manually reconnect on close to ensure that doesn't happen.
e2e
> Manually reconnect closed sockets

- go/client/client.go
- go/client/graph/users.graphql
> feat(client): Add update user mutation

- assets/src/components/home/AiThreads.tsx
> enhancement: Load only three most recent chat threads on the home page

- go/client/client.go
- go/client/graph/models.graphql
Extend service deployment console go client with status
> feat: extend service deployment with status

- .github/workflows/publish.yaml
> Fix cd action

- assets/src/components/layout/Sidebar.tsx
- assets/src/generated/graphql.ts
- charts/console-rapid/Chart.yaml
- charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- go/client/client.go
- go/client/graph/users.graphql
- go/client/models_gen.go
- go/controller/api/v1alpha1/catalog_types.go
- go/controller/api/v1alpha1/deploymentsettings_types.go
- go/controller/api/v1alpha1/prautomation_types.go
- go/controller/api/v1alpha1/zz_generated.deepcopy.go
- go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
- go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- go/controller/docs/api.md
- go/controller/internal/controller/prautomation_attributes.go
- lib/console/ai/provider.ex
- lib/console/ai/provider/anthropic.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/deployments/settings.ex
- lib/console/graphql/resolvers/deployments/policy.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/schema/deployment_settings.ex
- lib/console/schema/vulnerability_report.ex
- plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
- schema/schema.graphql
- test/console/graphql/mutations/user_mutations_test.exs
- test/console/graphql/queries/deployments/policy_queries_test.exs
* tweaks for service catalog
* need to add catalogRef to PRA crd
* add some more necessary queries for vuln view
e2e
> prep next release

- assets/src/components/catalog/CatalogsGrid.tsx
> fix: Catalog column sizing

- lib/console/ai/provider/anthropic.ex
- lib/console/ai/provider/azure.ex
- lib/console/ai/provider/vertex.ex
didn't handle streamed outputs properly, also need to investigate vertex ai issues.
n/a
> potentially fix anthropic

- lib/console/deployments/global.ex
- lib/console/deployments/statistics.ex
- lib/console/prom/plugin.ex
- lib/console/schema/stack.ex
- test/console/deployments/global_test.exs
Also added metrics for stack failures
n/a
> Make global service delete cascade by default

- assets/src/generated/graphql.ts
- config/prod.exs
- go/client/models_gen.go
- lib/console/application.ex
- lib/console/cost/ingester.ex
- lib/console/deployments/global.ex
- lib/console/deployments/statistics.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/prom/plugin.ex
- lib/console/schema/cluster_namespace_usage.ex
- lib/console/schema/cluster_scaling_recommendation.ex
- lib/console/schema/cluster_usage.ex
- lib/console/schema/stack.ex
- lib/console/schema/vulnerability.ex
- priv/repo/migrations/20241212155818_more_cost_schemas.exs
- priv/repo/migrations/20241212172141_add_vulnerability_report_id.exs
- schema/schema.graphql
- test/console/cost/loader_test.exs
- test/console/deployments/global_test.exs
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
> Add gs defaults

- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- lib/console/utils/vuln.ex
Will help develop the vulnerability ui
n/a
> Auto-parse cvss vectors and present in gql

- Dockerfile
Bump plural cli version to v0.10.3.
Waiting for https://github.com/pluralsh/plural-cli/actions/runs/12313608733
> chore: bump used CLI version to v0.10.3

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/policy.ex
- lib/console/schema/vulnerability.ex
- schema/schema.graphql
I don't know how this didn't make it into the prior pr, but this will externalize the info into gql schema
n/a
> Add parsed vulnerability schemas

- assets/src/components/component/info/IngressCertificates.tsx
> add k8s dashboard link to ingress certs

- go/client/client.go
- go/client/graph/kubecost.graphql
- go/client/models_gen.go
add ingestClusterCost mutation
> add ingestClusterCost mutation

- assets/src/generated/graphql.ts
- charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
- go/client/models_gen.go
- go/controller/api/v1alpha1/deploymentsettings_types.go
- go/controller/api/v1alpha1/zz_generated.deepcopy.go
- go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
- go/controller/docs/api.md
- go/controller/internal/controller/deploymentsettings_controller.go
- lib/console/deployments/pr/dispatcher.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/deployments/settings.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster_namespace_usage.ex
- lib/console/schema/cluster_scaling_recommendation.ex
- lib/console/schema/cluster_usage.ex
- lib/console/schema/deployment_settings.ex
- plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
- priv/repo/migrations/20241218145152_add_mgmt_repo_setting.exs
- schema/schema.graphql
Will (hopefully) meet current specs for cost analysis views
n/a
> Add search/filter queries for cost data

- static/compatibilities/cert-manager.yaml
- utils/compatibility/scrapers/cert-manager.py
Ran the scraper locally and verified output
> add upcoming releses for cert-manager scraper

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/ai/provider/ollama.ex
- lib/console/cost/ingester.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/cluster_scaling_recommendation.ex
- priv/repo/migrations/20250106200605_add_recommendation_utils.exs
- schema/schema.graphql
- test/console/cost/ingester_test.exs
Was using the wrong field to determine the recommendation
unit test
> Fix cpu recommendation inference

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/cluster.ex
- schema/schema.graphql
forgot to add these to recommendation attributes
n/a
> Add memory util fields to schema

- lib/console/cost/ingester.ex
- test/console/cost/ingester_test.exs
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
> Scaling recommendations based off utilization

- charts/console-rapid/Chart.yaml
- charts/controller/Chart.yaml
- charts/controller/templates/manager-rbac.yaml
- lib/console/logs/provider/victoria.ex
- lib/console/logs/stream/exec.ex
small issues w/ the victoria logs log providr
e2e
> Fix victoria logs provider

- assets/src/components/ai/AITableEntry.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/cost-management/CostManagement.tsx
- assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
- assets/src/components/utils/AiInsights.tsx
boosts cost management table height (closes PROD-3069)
improves styling on chat thread tables and fixes a bug with optimistically updating the thread after sending a message (closes PROD-2989)
adds "last updated" time to insights tooltip (closes PROD-2883)
> various QA

- charts/console-rapid/Chart.yaml
> bump console rapid chart

- charts/controller/templates/manager-rbac.yaml
Fix controller manager RBAC for GeneratedSecretReconciler
Delete destination secrets when CRD is deleted
> fix: controller manager RBAC

- go/client/client.go
- go/client/graph/edge.graphql
> feat(client): add cluster registration queries

- assets/src/generated/graphql.ts
- charts/ai-proxy/Chart.yaml
- lib/console/deployments/clusters.ex
- lib/console/deployments/init.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- schema/schema.graphql
- test/console/deployments/init_test.exs
- test/console/graphql/queries/deployments/cluster_queries_test.exs
Simply bump the versions, includes the new openai endpoint
> Release ai-proxy v1.2.0

- go/client/client.go
- go/client/graph/edge.graphql
> feat: add machine id to cluster registration queries

- assets/src/generated/graphql.ts
- charts/controller/crds/deployments.plural.sh_customstackruns.yaml
- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- go/client/models_gen.go
- go/controller/api/v1alpha1/prautomation_types.go
- go/controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
- go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- go/controller/docs/api.md
- lib/console/schema/embeds.ex
- plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
- schema/schema.graphql
Will help with some ux goofiness
n/a
> Add cluster/project pr automation config types

- go/controller/internal/controller/project_controller.go
It should not try to remove a project if it is marked as readonly.
> fix: project controller trying to delete readonly project

- lib/console/deployments/pr/validation.ex
- test/console/deployments/git_test.exs
Forgot to add these and w/o the automation cannot proceed
unit tests
> Add validations for project/cluster pr config types

- go/client/client.go
- go/client/graph/deployment.graphql
> extend GetServiceDeploymentForAgent with the cluster distro

- lib/console/deployments/policies/bootstrap_policies.ex
- lib/console/deployments/policies/policies.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- test/console/deployments/policies/bootstrap_policies_test.exs
- test/console_web/controllers/gql_test.exs
This is blocking edge setup currently
unit tests
> Bootstrap tokens should be able to query deploy tokens

- lib/console/deployments/pr/validation.ex
Will lead to unexpected behavior otherwise
existing
> Don't validate optional fields

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/clusters.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cloud_addon.ex
- lib/console/schema/cluster.ex
- priv/repo/migrations/20250123223446_add_cloud_addons.exs
- schema/schema.graphql
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
This will be used to visualize the eks addons (primarily) provisioned for a cluster and use that info to guide upgrade plans too.
unit test
> Implement cloud addon scraping gql CRUD

- go/controller/internal/controller/bootstraptoken_controller.go
Fixed an issue where existing bootstrap token was marked as not ready/synchronized.
> fix: bootstrap token status not handled properly

- go/client/client.go
- go/client/graph/upgradeinsights.graphql
Allows UpgradeInsights addons to be provided in the save mutation.
> feat: update saveUpdateInsights mutation

- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/cd/services/service/component/ComponentList.tsx
- assets/src/components/cd/services/service/component/Components.tsx
- assets/src/components/kubernetes/common/DataSelect.tsx
- assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
- assets/src/components/utils/IconExpander.tsx
- assets/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
- assets/src/routes/kubernetesRoute.tsx
also makes some improvements to IconExpander components (makes the X clear the input instead of just closing the expander)
> add frontend filtering to service components

- .dockerignore
- .github/workflows/k8s-versions-updater.yaml
- .gitignore
- Makefile
It will keep `KUBE_VERSION` file in sync with latest K8s version (major.minor). First PR: #1811
PR for GCP versions: #1816
TODO: Addon version sync?
> enhancement: Sync K8s versions

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/dataloader.ex
- lib/console/graphql/resolvers/deployments/policy.ex
- lib/console/schema/cluster_scaling_recommendation.ex
- lib/console/schema/pr_automation.ex
- lib/console/schema/service.ex
- lib/console/schema/vulnerability_report.ex
- schema/schema.graphql
- test/console/graphql/queries/deployments/policy_queries_test.exs
This could be expensive but will do it for now.
unit test
> Add query to aggregate vuln reports by cluster

- assets/package.json
- assets/src/components/settings/global/observability/EditObservabilityWebhook.tsx
- assets/src/components/settings/global/observability/Observability.tsx
- assets/src/components/settings/global/observability/ObservabilityProviders.tsx
- assets/src/components/settings/global/observability/ObservabilityProvidersColumns.tsx
- assets/src/components/settings/global/observability/ObservabilityWebhooks.tsx
- assets/src/components/settings/global/observability/ObservabilityWebhooksColumns.tsx
- assets/src/components/utils/CopyButton.tsx
- assets/src/components/utils/SubTabs.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdGlobalSettings.graphql
- assets/src/routes/settingsRoutes.tsx
- assets/yarn.lock
> add ui for observability webhooks settings

- assets/src/components/edge/Edge.tsx
- assets/src/components/edge/clusters/Clusters.tsx
- assets/src/components/edge/clusters/CompleteClusterRegistrationModal.tsx
- assets/src/components/edge/context.tsx
- assets/src/components/edge/hooks.ts
- assets/src/components/edge/images/Images.tsx
- assets/src/components/edge/images/hooks.ts
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- assets/src/graph/cdClusters.graphql
- assets/src/routes/edgeRoutes.tsx
> feat: add tabs to edge view

- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/common/DataSelect.tsx
> fix: Deselect namespace on cluster change

- go/client/client.go
- go/client/graph/stack.graphql
add ListClusterMinimalStacks query
> chore: add ListClusterMinimalStacks query

- Dockerfile
Use latest CLI version with PRAutomation condition expression support
> chore: bump CLI version in console dockerfile

- go/client/client.go
- go/client/graph/cluster.graphql
- go/client/graph/edge.graphql
- extend RegisterRuntimeServices mutation
- add CRUD for ClusterIsoImage
> extend RegisterRuntimeServices mutation

- charts/console-rapid/Chart.yaml
- charts/console/Chart.yaml
- charts/console/templates/migration.yaml
- charts/console/templates/secrets.yaml
- plural/helm/kas/Chart.yaml
- plural/helm/kas/templates/deployment.yaml
- plural/helm/kas/templates/secrets.yaml
- plural/helm/kas/values.yaml
* adds ability to set additional volumes/env for migration job
* adds opt-out to secrets in kas
n/a
> Minor chart changes

- go/client/client.go
- go/client/graph/edge.graphql
> add query GetClusterIsoImage

- go/client/client.go
- go/client/graph/audit.graphql
Extend GQL client with `addClusterAuditLog` mutation
> feat(client): add cluster audit log mutation

- assets/src/generated/graphql.ts
- charts/ai-proxy/Chart.yaml
- charts/ai-proxy/templates/deployment.yaml
- charts/ai-proxy/templates/serviceaccount.yaml
- charts/ai-proxy/values.yaml
- go/client/models_gen.go
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/cluster_audit_log.ex
- priv/repo/migrations/20250206161947_add_log_response_code.exs
- schema/schema.graphql
- test/console/graphql/queries/deployments/cluster_queries_test.exs
Seeing some sporadic issues with repo naming and other stuff, going to investigate in a test account
unit test
> Debug ai cost management prs, fix cluster audit logs

- assets/src/components/cd/logs/LogContextPanel.tsx
- assets/src/components/cd/logs/LogsCard.tsx
- assets/src/components/notifications/NotificationsLauncher.tsx
- assets/src/components/notifications/NotificationsPanel.tsx
tightens up the css a bit
also fixes PROD-3184
> make notifications panel scrollable

- assets/src/components/cd/cluster/ClusterNodes.tsx
> fix(console): vertical scroll on cluster nodes list

- Makefile
> fix make dependencies

- assets/src/components/kubernetes/common/ResourceDetails.tsx
fixes the width on large screens from:
to:
> fix k8s dashboard detail views width

- go/client/client.go
- go/client/graph/stack.graphql
> feat: extend infrastructure stack with violation/policy field

- charts/network-observability-operator/Chart.yaml
- charts/network-observability-operator/templates/certificate.yaml
- charts/network-observability-operator/templates/certificates.yaml
- charts/network-observability-operator/templates/configmap.yaml
- charts/network-observability-operator/templates/deployment.yaml
- charts/network-observability-operator/templates/flows.netobserv.io_flowcollectors.yaml
- charts/network-observability-operator/templates/flows.netobserv.io_flowmetrics.yaml
- charts/network-observability-operator/templates/roles.yaml
- charts/network-observability-operator/templates/services.yaml
> fix: Fix netobserv chart

- charts/network-observability-operator/Chart.yaml
- charts/network-observability-operator/templates/flows.netobserv.io_flowcollectors.yaml
- charts/network-observability-operator/templates/flows.netobserv.io_flowmetrics.yaml
> fix: Fix network-observability-operator chart

- .github/workflows/cron.yaml
- assets/src/generated/graphql.ts
- charts/console/templates/_helpers.tpl
- charts/console/templates/deployment.yaml
- charts/console/templates/migration.yaml
- config/config.exs
- config/test.exs
- lib/console/ai/policy.ex
- lib/console/ai/service.ex
- lib/console/cache.ex
- lib/console/deployments/clusters.ex
- lib/console/deployments/cron.ex
- lib/console/deployments/global.ex
- lib/console/graphql/ai.ex
- lib/console/graphql/resolvers/ai.ex
- lib/console/schema/cluster.ex
- plural/helm/kas/templates/deployment.yaml
- plural/helm/kas/values.yaml
- priv/repo/migrations/20250218061443_optimization_indices.exs
- schema/schema.graphql
- static/addons/eks.yaml
- test/console/deployments/cron_test.exs
- test/console/graphql/queries/ai_queries_test.exs
This will prevent an annoying job immutability check from firing.
template locally
> Don't set replicas env var in helper template

- go/client/client.go
- go/client/graph/users.graphql
> enhancement(client): add upsert user mutation

- templates/values.yaml.liquid
- templates/values.yaml.tpl
This will help the dashboard work properly
n/a
> Fix console templates

- go/client/Makefile
- go/client/client.go
- go/client/graph/stack.graphql
Also fixes a typo (`:`) in client makefile
> feat(client): add dryRun flag to stackrun

- assets/src/components/cd/clusters/runtime/columns.tsx
- assets/src/components/kubernetes/cluster/Nodes.tsx
> feat: Add EKS icon next to EKS addon names

- .github/workflows/cron.yaml
> Allow ability to manually run  cron gh actions

- go/demo/flaky-service/api/behavior_modifiers.go
This will help us e2e test vector store integration
n/a
> Tune flaky service error logs

- .github/workflows/ai-proxy-cd.yaml
- .github/workflows/ai-proxy-ci.yaml
- .github/workflows/assets.yaml
- .github/workflows/codeql.yml
- .github/workflows/controller-cd.yaml
- .github/workflows/controller-ci.yaml
- .github/workflows/demo-cd.yaml
- .github/workflows/oci-auth-cd.yaml
- .github/workflows/oci-auth-ci.yaml
- .github/workflows/pr-labels.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- go/demo/flaky-service/api/behavior_modifiers.go
- lib/console/ai/evidence/context.ex
- lib/console/ai/evidence/vector.ex
- lib/console/ai/provider.ex
- lib/console/ai/pubsub/vector/consumer.ex
- lib/console/ai/pubsub/vector/protocol.ex
- lib/console/ai/vector/content.ex
- lib/console/ai/vector/elastic.ex
- lib/console/ai/vector_store.ex
- lib/console/deployments/pr/impl/github.ex
- test-apps/flaky-service/flaky-service.yaml.liquid
- test/console/ai/cron_test.exs
- test/console/ai/pubsub/vector/consumer_test.exs
Need to figure out what's going on while e2e testing
n/a
> Troubleshoot vector indexing

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- go/demo/flaky-service/api/behavior_modifiers.go
- lib/console/ai/cron.ex
- lib/console/ai/evidence/vector.ex
- lib/console/ai/vector/utils.ex
- lib/console/ai/vector_store.ex
- lib/console/deployments/settings.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/deployment_settings.ex
- lib/console/schema/operational_layout.ex
- priv/repo/migrations/20250305170252_add_service_mesh.exs
- priv/tools/vector.json
- schema/schema.graphql
- test/console/ai/pubsub/vector/consumer_test.exs
* fixes the marking of a vector store as initialized
* tunes the prompt a bit
e2e
> More pr indexing fixes

- go/demo/flaky-service/api/behavior_modifiers.go
- lib/console/ai/evidence/vector.ex
- lib/console/ai/fixer.ex
- lib/console/ai/fixer/alert.ex
- lib/console/ai/fixer/base.ex
- lib/console/ai/fixer/service.ex
- lib/console/ai/tools/pr.ex
- lib/console/ai/vector/elastic.ex
- lib/console/ai/vector/storable.ex
- lib/console/ai/vector_store.ex
- lib/console/deployments/pr/file.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/schema/ai_insight_evidence.ex
* small tweaks to alert resolution formatting
* add timestamp to ES vector indexes
* alert fix prs
e2e
> Begin prepping the release

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/events.ex
- lib/console/deployments/flows.ex
- lib/console/deployments/policies/rbac.ex
- lib/console/deployments/pr/utils.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/deployments/flow.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/deployments/flow.ex
- lib/console/schema/flow.ex
- lib/console/schema/pipeline.ex
- lib/console/schema/pull_request.ex
- lib/console/schema/service.ex
- priv/repo/migrations/20250306201348_add_flows.exs
- schema/schema.graphql
- test/console/deployments/flows_test.exs
- test/console/graphql/mutations/deployments/flow_mutations_test.exs
- test/console/graphql/queries/deployments/flow_queries_test.exs
- test/support/factory.ex
This implements the most basic CRUD for flows, once it's fully wired up, will work on doing the integrations with things like vector indexing and other workflows
unit test
> Flow CRUD endpoints

- go/controller/internal/controller/catalog_controller_test.go
- go/controller/internal/controller/clusterrestore_controller_test.go
- go/controller/internal/controller/customstackrun_test.go
- go/controller/internal/controller/gitrepository_controller_test.go
- go/controller/internal/controller/managenamespace_test.go
tests focused on error handling and queueing.
> Improve console controller tests

- charts/console-rapid/Chart.yaml
- charts/console/templates/git-server.yaml
> Fix git server enabled logic

- charts/console-rapid/Chart.yaml
> Accidentally dropped rapid chart app version

- .github/workflows/publish-ollama.yaml
[PROD-3296](https://linear.app/pluralsh/issue/PROD-3296/drop-ollama-gh-action)
> chore: disable ollama gh action

- go/ai-proxy/args/args.go
> return empty string if no region bedrock

- charts/ai-proxy/Chart.yaml
> bump app version (bedrock aws region bugfix)

- assets/src/generated/graphql.ts
- charts/controller/crds/deployments.plural.sh_observers.yaml
- go/client/models_gen.go
- go/controller/api/v1alpha1/observer_types.go
- go/controller/api/v1alpha1/zz_generated.deepcopy.go
- go/controller/config/crd/bases/deployments.plural.sh_observers.yaml
- lib/console/ai/vector/storable.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/graphql/deployments/git.ex
- lib/console/schema/git_repository.ex
- lib/console/schema/observer.ex
- plural/helm/console/crds/deployments.plural.sh_observers.yaml
- schema/schema.graphql
- test/console/ai/pubsub/vector/consumer_test.exs
- test/console/deployments/git_test.exs
This was only matching on https urls, fixing it to handle http
regression
> Fix auth method inference for git repositories

- charts/controller/crds/deployments.plural.sh_pipelines.yaml
- charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
- go/controller/api/v1alpha1/pipeline_types.go
- go/controller/api/v1alpha1/servicedeployment_types.go
- go/controller/api/v1alpha1/zz_generated.deepcopy.go
- go/controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
- go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
- go/controller/internal/controller/pipeline_controller_attributes.go
- go/controller/internal/controller/servicedeployment_controller.go
- plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
- plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
This rounds out the most important parts of the crd reconcilers for flows (at least for now)
n/a
> Add flowRef to ServiceDeployment and Pipeline CRDs

- go/controller/internal/controller/pipeline_controller_attributes.go
- go/controller/internal/controller/servicedeployment_controller.go
- lib/console/deployments/git.ex
- lib/console/deployments/observability/webhook/base.ex
- lib/console/deployments/observability/webhook/raw.ex
- test/console_web/controllers/webhook_controller_test.exs
* auto-infer namespace from associated resource namespace
n/a
> Improve flow reconciliation

- assets/src/components/cd/services/ServicesTableErrors.tsx
- assets/src/components/cd/services/service/ServiceErrors.tsx
> fix: Fix service errors table scaling issues

- lib/console/ai/pubsub/vector/protocol.ex
- lib/console/ai/vector/elastic.ex
- lib/console/schema/alert.ex
- test/console_web/controllers/webhook_controller_test.exs
just figuring out any bugs in the new flow based pr indexing
n/a
> Index PRs for flows

- assets/src/components/security/vulnerabilities/VulnReportDetails.tsx
- assets/src/components/security/vulnerabilities/VulnReportsTable.tsx
- assets/src/components/security/vulnerabilities/VulnReportsTableCols.tsx
also adds url to the details page
> don't linkify vuln report image urls

- go/controller/internal/controller/scmconnection_controller.go
> fix: Fix default SCM connection update

- charts/console/values.yaml
- go/demo/flaky-service/go.mod
- go/go.work
- go/helmchartutils/args/args.go
- go/helmchartutils/fileutils/fileutils.go
- go/helmchartutils/go.mod
- go/helmchartutils/main.go
- go/helmchartutils/yaml/yaml_parser.go
- Add missing references into values.yaml for console helm chart (defaulting to null ~ since that will allow the value to be in the chart without effectively changing anything)
- Add documentation for values in values.yaml
Wrote a CLI util in go to do the file parsing and comparison
> Fully fleshed out values.yaml for console helm chart

- assets/package.json
- assets/yarn.lock
> fix: Bump design system version

- assets/src/generated/graphql.ts
- charts/controller/crds/deployments.plural.sh_flows.yaml
- charts/controller/crds/deployments.plural.sh_mcpservers.yaml
- charts/controller/crds/deployments.plural.sh_prautomations.yaml
- go/client/models_gen.go
- go/controller/api/v1alpha1/flow_types.go
- go/controller/api/v1alpha1/mcpserver_types.go
- go/controller/api/v1alpha1/zz_generated.deepcopy.go
- go/controller/config/crd/bases/deployments.plural.sh_flows.yaml
- go/controller/config/crd/bases/deployments.plural.sh_mcpservers.yaml
- go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
- go/controller/internal/controller/mcpserver_controller.go
- lib/console/commands/plural.ex
- lib/console/deployments/clusters.ex
- lib/console/deployments/pubsub/protocols/notifiable.ex
- lib/console/graphql/deployments/flow.ex
- lib/console/schema/notification_router.ex
- plural/helm/console/crds/deployments.plural.sh_flows.yaml
- plural/helm/console/crds/deployments.plural.sh_mcpservers.yaml
- plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
- priv/notifications/plural/stack.pending.json.eex
- priv/notifications/slack/stack.pending.json.eex
- priv/notifications/teams/stack.pending.json.eex
- schema/schema.graphql
- test/console/deployments/clusters_test.exs
- test/console/deployments/pubsub/notification_test.exs
This was originally relying on the cli's internal code but it's probably safer for us to just wire it in directly since all the information is deterministically available w/in the console.
existing
> Directly specify agent values in self-install process

- .github/workflows/ai-proxy-cd.yaml
- .github/workflows/controller-cd.yaml
- .github/workflows/oci-auth-cd.yaml
- .github/workflows/publish.yaml
- .github/workflows/softserve-cd.yaml
It looks like google has fully deprecated gcr, so drop it from our release config until we have a replacement
> Drop gcr for now

- .github/workflows/ai-proxy-cd.yaml
- .github/workflows/controller-cd.yaml
- .github/workflows/oci-auth-cd.yaml
- .github/workflows/publish.yaml
- .github/workflows/softserve-cd.yaml
- assets/src/generated/graphql.ts
- go/client/client.go
- go/client/models_gen.go
- lib/console/deployments/git.ex
- lib/console/deployments/observer/discovery.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/schema/observer.ex
- schema/schema.graphql
- test/console/graphql/mutations/deployments/git_mutations_test.exs
I did the container registry to artifact registry migration so the push failures should be resolved now
n/a
> Bring back gcr to out container build setups

- lib/console/ai/chat/engine.ex
- lib/console/ai/tools/logs.ex
- lib/console/ai/tools/pipelines.ex
- lib/console/schema/cluster.ex
- priv/tools/logs.json
- priv/tools/pipelines.json
This adds time filtering to the logs tool, so the ai can fetch logs before and after a possibly suspicious log line.
Fixes PROD-3393
existing
> Improve logs tool (and other flow chat tool changes)

- assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
> fix: Cost management graph curve

- config/config.exs
small typo from copying from plural codebase
unit test
> Fix base hydra conf

- go/client/client.go
- go/client/graph/oauth.graphql
> feat: Update OIDC provider fragment

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- go/controller/internal/controller/servicedeployment_controller.go
- lib/console/graphql/deployments/service.ex
- schema/schema.graphql
just didn't add it to the schema
n/a
> Support flow id on updates

- .github/workflows/controller-cd.yaml
> chore: Split builds between ARM and AMD64

- charts/controller/crds/deployments.plural.sh_flows.yaml
- go/controller/api/v1alpha1/deploymentsettings_types.go
- go/controller/api/v1alpha1/flow_types.go
- go/controller/config/crd/bases/deployments.plural.sh_flows.yaml
- lib/console/deployments/flows.ex
- lib/console/graphql/observability.ex
- plural/helm/console/crds/deployments.plural.sh_flows.yaml
This is honestly more to simply trigger the controller ci process to have a fresh image build
cd go/controller && make test
> Add some flow crd docs

- lib/console/deployments/observability.ex
- lib/console/mesh/provider.ex
- lib/console/mesh/provider/ebpf.ex
- lib/console/mesh/schema.ex
- test/console/graphql/queries/deployments/cluster_queries_test.exs
- test/console/mesh/provider/istio_test.exs
Also adds some logging to help debug issues w/ the istio graph
n/a
> Add support for ebpf network data extraction

- assets/src/generated/graphql.ts
runs codegen for changes from #2137 to update ObservabilityWebhookType
> update with new schema

- lib/console_web/controllers/webhook_controller.ex
- test/console_web/controllers/webhook_controller_test.exs
Verify webhook signature as shown here https://developer.pagerduty.com/docs/verifying-webhook-signatures
Previously was using basic auth (same as grafana) but for pagerduty we shouldn't do that
Fixed unit tests so new verification gets tested.
> fix auth handling for pagerduty webhook

- assets/src/components/ai/AIThreads.tsx
> fix: Fix view layout

- config/test.exs
- lib/console/deployments/observability/webhook.ex
- lib/console/deployments/observability/webhook/datadog.ex
- lib/console_web/controllers/webhook_controller.ex
- test/console_web/controllers/webhook_controller_test.exs
> Datadog observability webhook

- go/client/client.go
- go/client/graph/cluster.graphql
> extend RegisterRuntimeServices with deprecated arg

- .github/workflows/controller-cd.yaml
- .github/workflows/test.yaml
- assets/src/generated/graphql.ts
- lib/console/deployments/pr/impl/github.ex
- lib/console/graphql/deployments/service.ex
- lib/console/schema/pull_request.ex
- lib/console_web/channels/user_socket.ex
- priv/repo/migrations/20250422203453_pr_commit_sha.exs
- schema/schema.graphql
The with chain was doing a full match which can cause it to throw.  Not a huge deal but nice to avoid
n/a
> Fix socket context bug

- assets/package.json
- assets/public/mitm.html
- assets/public/sw.js
- assets/src/components/security/Security.tsx
- assets/src/components/security/policies/CreatePolicyReportModal.tsx
- assets/src/components/security/policies/PastReportsModal.tsx
- assets/src/components/security/policies/Policies.tsx
- assets/src/components/security/policies/PoliciesFilter.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/policies.graphql
- assets/yarn.lock
> feat: Compliance reports

- charts/console/values.yaml
- plural/helm/console/values.yaml
This is required by the new create secret dialog since all dashboard API POST requests have csrf protection enabled by default.
> fix(chart): disable csrf protection for dashboard API

- assets/package.json
- assets/src/components/cd/services/ServiceSettings.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
- assets/src/components/cd/services/service/settings/ServiceGitSettings.tsx
- assets/src/components/cd/services/service/settings/ServiceHelmSettings.tsx
- assets/src/components/cd/services/service/settings/ServiceSettings.tsx
- assets/src/components/utils/SubTabs.tsx
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/cdRoutesConsts.tsx
- assets/yarn.lock
- Added loading state indication to the helm chart form fields
- Updated design system to be able to use `Remeasure Fonts` action in the code editor to fix cursor position
- Split `Settings` -> `Repository` tab into `Git` and `Helm`. If `Git` is not available it will autoredirect to `Helm`.
It was a quick change to split `Repository` into 2 tabs. It can definitely be refactored to use shared component as base.
Locally
> feat: improve helm chart loading state and upgrade design system

- go/client/client.go
- go/client/graph/deployment.graphql
This one actually extends the dedicated query used by agent.
> feat: extend kustomize with enableHelm field for agent

- go/client/client.go
- go/client/graph/automation.graphql
> feat: Add create SCM webhook pointer mutation

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/flow.ex
- schema/schema.graphql
referenced the wrong service object
n/a
> Fix preview environment schemas

- lib/console/mesh/provider.ex
- lib/console/mesh/provider/linkerd.ex
- test/console/mesh/provider/ebpf_test.exs
- test/console/mesh/provider/linkerd_test.exs
implementation of Linkerd service mesh.
Also added tests for EBPF service mesh since it didn't have a unit test file.
mix test
> linkerd impl + ebpf unit test

- assets/src/components/cd/providers/DeleteCluster.tsx
- assets/src/components/cd/providers/DetachCluster.tsx
> feat: add confirmation prompt with cluster name for DeleteCluster and DetachCluster modals

- lib/console/mesh/provider.ex
- lib/console/mesh/provider/cilium.ex
- lib/console/mesh/provider/linkerd.ex
- test/console/mesh/provider/cilium_test.exs
similar to other service mesh impls
https://linear.app/pluralsh/issue/PROD-3343/add-support-for-cilium
unit tests
> cilium service mesh impl + unit test

- assets/src/components/ai/McpServers.tsx
- assets/src/components/ai/insights/InsightEvidence.tsx
- assets/src/components/flows/flow/Flow.tsx
- assets/src/components/flows/flow/previews/FlowPreviews.tsx
- assets/src/components/flows/flow/previews/PreviewInstancesTableCols.tsx
- assets/src/components/flows/flow/previews/PreviewTemplatesTable.tsx
- assets/src/components/flows/flow/previews/PreviewTemplatesTableCols.tsx
- assets/src/components/flows/flow/previews/SpawnPreviewModal.tsx
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- assets/src/graph/ai/mcp.graphql
minor ux touchups
also adds jwt generation on the mcp servers page (closes PROD-3485)
> preview environment qa

- assets/src/components/utils/network-graph/NetworkGraphStatistics.tsx
- assets/src/components/utils/reactflow/layouting.tsx
the dynamic import was unreliable
> include elk in bundle

- .github/workflows/test.yaml
- lib/console/deployments/flows.ex
- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/cmd.ex
- lib/console/deployments/helm/agent.ex
- lib/console/deployments/oauth.ex
- lib/console/graphql/deployments/oauth.ex
- lib/console/schema/git_repository.ex
- lib/console/schema/preview_environment_template.ex
- lib/console/schema/revision.ex
- lib/console/schema/service_dependency.ex
- test/console/deployments/flows_test.exs
- test/console/deployments/git/agent_test.exs
- test/console/graphql/queries/deployments/oauth_queries_test.exs
Forgot to add the on_replace setting there
unit test
> Fix preview environment template upserts

- lib/console/graphql/deployments/oauth.ex
- test/console/graphql/mutations/deployments/oauth_mutations_test.exs
Need to properly return an ok tuple
n/a
> Fix oidc backwards compat

- assets/src/components/ai/chatbot/Chatbot.tsx
- assets/src/components/flows/flow/previews/FlowPreviews.tsx
- lib/console/deployments/flows.ex
- lib/console/deployments/flows/preview.ex
- lib/console/deployments/pubsub/recurse.ex
- lib/console/graphql/resolvers/deployments/service.ex
- lib/console/schema/preview_environment_instance.ex
- test/console/deployments/flows_test.exs
- test/console/deployments/pubsub/recurse_test.exs
Bypasses some of the complexity around fetching helm values w/in service templates (which shouldn't be insecure)
n/a
> Fix helm values extraction

- static/compatibilities.yaml
- utils/compatibility/main.py
Github api limits have gotten much more restrictive, this will prevent our live syncs from hitting snags
Fixes PROD-3595
n/a
> Compile compatibility matrices to a single file

- Makefile
- utils/versions/main.py
only used for release process, so not a major concern
n/a
> Minor change to latest-version

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/graphql/deployments/service.ex
- lib/console/schema/service_component.ex
- priv/repo/migrations/20250520134234_add_component_uid.exs
- schema/schema.graphql
will be needed for component tree setup
n/a
> add service component uid

- priv/repo/migrations/20250520004950_add_vuln_report_uniq.exs
have to remove possibility of dupes, and it's not a big deal since it'll be reuploaded anyway
> truncate vulnerability reports before migration

- go/client/client.go
- go/client/graph/models.graphql
> feat(graphql): add `uid` field to ServiceDeployment components

- .github/workflows/compatability-matrices.yaml
https://linear.app/pluralsh/issue/PROD-3598/upload-compatibility-matrices-to-s3
https://github.com/pluralsh/console/actions/runs/15146927945 - test run
> upload compatibility matricies to s3 bucket

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/ai/evidence/component/resource.ex
- lib/console/ai/evidence/service_component_child.ex
- lib/console/graphql/deployments/service.ex
- lib/console/schema/ai_insight_evidence.ex
- lib/console/schema/cluster.ex
- lib/console/schema/cluster_insight_component.ex
- lib/console/schema/service_component_child.ex
- priv/repo/migrations/20250521002356_add_component_children_insight.exs
- schema/schema.graphql
- test/console/ai/pubsub/consumer_test.exs
This can add a ton of useful info to the insight generation, and also gives a much fuller picture of overall health of the component
n/a
> Add insight generation for service component children

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- go/controller/api/v1alpha1/deploymentsettings_types.go
- lib/console/schema/deployment_settings.ex
- schema/schema.graphql
golang and schema changes to fully support opensearch as an alternate to elastic.
updated schema using `make update-schema`
> Opensearch Schema/GoLang Changes

- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/services/Services.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/cd/services/service/ServiceComponentsTree.tsx
- assets/src/components/cd/services/service/component/ComponentList.tsx
- assets/src/components/cd/services/service/component/Components.tsx
- assets/src/components/utils/ButtonGroup.tsx
also adds some types that were missing, and tooltips to the list/tree view switchers
> add filtering to service component tree

- lib/console/ai/chat/engine.ex
- lib/console/ai/tools/alerts_resolutions.ex
- priv/tools/alerts_resolutions.json
- test/console/ai/chat_test.exs
Since alerts resolutions are indexed in vector DB, other than matching the flow id we want to rely purely on semantic search (i.e. no additional filters).
> Alerts resolution tool implementation.

- config/config.exs
- lib/console/services/users.ex
- rel/runtime.exs
- test/console/services/users_test.exs
> Org email suffix as env var

- go/client/client.go
- go/client/graph/deployment.graphql
> extend service with helm values

- go/client/client.go
- go/client/graph/cloud.graphql
- go/controller/internal/client/cloud.go
- go/controller/internal/client/console.go
- go/controller/internal/test/mocks/ConsoleClient_mock.go
> chore: add CloudConnection client

- assets/src/components/stacks/output/StackOutput.tsx
> fix: Make stack outputs section scrollable

- charts/console-rapid/Chart.yaml
- charts/console/templates/cloud.yaml
- lib/console/deployments/global.ex
* need to add monitor perms for es license check
* fix contexts_equal?
* better route gen for vmuser
n/a
> o11y fixes

- lib/console/deployments/local/server.ex
- lib/console_web/controllers/git_controller.ex
There is a fringe possibility when a cluster isn't properly established that the following happens:
* digest fetch hits one pod, sees new commit and subfolder change
* tarball fetch hits another pod, which is running a duplicate git agent because of splitbrain, and hasn't fetched from upstream yet and serves old tarball
* next digest fetch can hit either pod and since both fetched it will report the new data
this will return the currently viewed sha back so the agent can decide that it matches its expectation and fail the current run if it doesn't
existing
> Add splitbrain detection header

- charts/console-rapid/Chart.yaml
- charts/console/templates/database.yaml
- charts/console/values.yaml
- lib/console/deployments/pubsub/protocols/previewable.ex
Needs to be namespaced properly, and use new naming schema
n/a
> Minor chart fixes for postgres creds setup

- charts/console-rapid/Chart.yaml
- charts/console/templates/cloud-query/deployment.yaml
- charts/console/templates/cloud-query/service.yaml
* names are a bit goofy, and need to be predictable to register with console pods
* incorrect docker tag
n/a
> Fix chart templating

- assets/package.json
- assets/src/components/ai/chatbot/Chatbot.tsx
- assets/src/components/ai/chatbot/ChatbotHeader.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
- assets/src/components/ai/explain/ExplainWithAIButton.tsx
- assets/src/components/commandpalette/commands.ts
- assets/src/components/flows/FeatureFlagContext.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/ai/chat.graphql
- assets/yarn.lock
adds a new "start a chat" button to the chatbot header, which creates an agent session with a cloud connection attached
> migrate ai chats to new apis

- assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/ai/agents/terraform.ex
- lib/console/ai/chat/system.ex
- lib/console/ai/chat/tools.ex
- lib/console/ai/provider/azure.ex
- lib/console/ai/provider/openai.ex
- lib/console/ai/tools/agent/coding/stack_files.ex
- lib/console/graphql/deployments/settings.ex
- lib/console/schema/deployment_settings.ex
- priv/prompts/terraform_commit.md
- priv/prompts/terraform_pr.md
- schema/schema.graphql
- test/console/ai/tools/agent/coding/stack_files_test.exs
Modify docs, add some validations
n/a
> Azure schema fixes

- assets/src/components/cost-management/CostManagementChartView.tsx
- assets/src/components/cost-management/ProjectCostUsageSeries.tsx
- assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
- assets/src/components/utils/NivoLineForecastingLayer.tsx
- assets/src/utils/datetime.ts
creates a generalized custom layer for nivo line charts to overlay trendlines, adds to cost management view
> add forecasting to cost management

- go/client/client.go
- go/client/graph/models.graphql
> chore: add SyncConfig

- go/client/client.go
- go/client/graph/deployment.graphql
> extend DiffNormalizerFragment with backfill flag

- assets/src/components/kubernetes/common/DeleteResource.tsx
> add type-to-confirm for dashboard namespace deletion

- lib/console/graphql/resolvers/deployments.ex
- test/console/graphql/queries/ai_queries_test.exs
needs to use AI dataloader
n/a
> Fix dataloader fetch for agent session connection

- .github/workflows/chart.yaml
- lib/console_web/controllers/ingest_controller.ex
- test/console/graphql/queries/ai_queries_test.exs
need to use the inferred proc ref
Fixes PROD-3811
n/a
> Fix bytes ingest collection

- .github/workflows/chart.yaml
split action needs a conditional
> Fix chart gh action

- go/client/client.go
- go/client/graph/deployment.graphql
- lib/console/deployments/pubsub/recurse.ex
Needed to move to agent code change for this
n/a
> Add agent fetch of lua folder

- go/client/client.go
- go/client/graph/deployment.graphql
> extend syncConfig with deleteNamespace flag

- charts/console/templates/cloud-query/deployment.yaml
- go/cloud-query/db.Dockerfile
- go/cloud-query/hack/init.sh
- go/cloud-query/hack/init.sql
Fixed an issue with db container initialization causing crashloop.
Tested PR image on our new demo env.
> fix(db-init): enhance PostgreSQL initialization and readiness checks

- go/ai-proxy/proxy/openai/embeddings.go
I think this was incorrectly chosing the embeddings backend endpoint
n/a
> Fix ai proxy

- charts/ai-proxy/Chart.yaml
will deploy embeddings fix
n/a
> Bump ai proxy helm chart to 1.3.2

- .github/workflows/chart.yaml
> Switch helm publishes to gcr (#2573)

- .github/workflows/test.yaml
- README.md
tested by running action, seems to make progress towards not hitting rate limit.
Timing increase is somewhat marginal (only ~2 min faster, from 8 to 6 mins)
For now doesn't seem like there is a way to make build times very much faster, might revisit if any ideas come up. Still probably worth making this change to avoid having to re-run PR actions due to rate limit failures.
> use registry cache

- go/client/client.go
- go/client/graph/cluster.graphql
> feat(client): add distro field to ClusterFragment

- assets/src/components/ai/chatbot/ChatMessage.tsx
- assets/src/components/ai/chatbot/ChatMessageContent.tsx
- assets/src/components/ai/chatbot/Chatbot.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/ai/chatbot/input/ChatInput.tsx
- assets/src/components/utils/VirtualList.tsx
fixes bugs related to streaming not showing on a new chat's first message, page loader row showing more than necessary, and VList quirks when deleting messages in a short thread
> chat ui bug fixes

- .github/workflows/publish.yaml
- .github/workflows/test-pr.yaml
- lib/console/deployments/services.ex
- priv/repo/migrations/20250821180844_add_template_id_index.exs
These are unnecessary and cause a bit of spam/slow releases
n/a
> Drop a few gh actions

- lib/console/ai/chat/engine.ex
- lib/console/ai/chat/system.ex
- lib/console/ai/provider.ex
- lib/console/ai/provider/anthropic.ex
- lib/console/ai/provider/openai.ex
- lib/console/ai/stream/exec.ex
- lib/console/ai/stream/result.ex
- lib/console/deployments/compatibilities/schema.ex
- lib/console/schema/chat.ex
- priv/prompts/kubernetes_pr.md
- priv/prompts/provisioning.md
- priv/prompts/terraform_pr.md
- static/compatibilities/cilium.yaml
- test/console/deployments/clusters_test.exs
think there might be some bad logic around keeping call ids in place
n/a
> Work on fixing dupe tool use

- Dockerfile
- lib/console/deployments/cron.ex
- lib/console/deployments/services.ex
> Prep v0.11.41

- assets/src/components/cd/clusters/ClusterHealthChip.tsx
- assets/src/components/cd/clusters/ClusterUpgradeButton.tsx
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/components/cd/clusters/ClustersColumns.tsx
> feat: Change health score and cluster upgrades color when agent is unhealthy

- go/client/utils.go
- lib/console/ai/memoizer.ex
- lib/console/deployments/clusters.ex
- lib/console/graphql/persisted_query.ex
- lib/console/prom/plugin.ex
Pretty sure the agent is sending these in a goofy way, this should solve for some of those issues
e2e
> Work around insight component goofiness
