- README.md
The README explanation of compilation of tests is missing a few steps. Also added troubleshooting for cases in which our version of erlang breaks because of systems with an unsupported version of Openssl
No relevant change to tests
> fix: better elixir/erlang install steps in README

- assets/src/components/Installations.js
Adds support for searching for installed apps in the toolbar of Console.
Closes #27
> support searching for apps

- lib/console/graphql/helpers.ex
- lib/console/graphql/middleware/allow_jwt.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/guardian.ex
- lib/console/pubsub/protocols/recurse.ex
- lib/console/schema/command.ex
- lib/console/services/builds.ex
- lib/console/services/observability.ex
- test/console/pubsub/recurse/builds_test.exs
We want visibility into the failure of deployments via the console, creating incidents is a quick way to do this, and we likely should create a dedicated way to track this as well in app.plural.sh
Added unit testing
Close #44
> Auto-Create Incidents on failed console builds

- lib/console/pubsub/protocols/webhook.ex
- lib/console/services/plural.ex
- lib/console/services/webhooks/slack.ex
- lib/kube/client.ex
- test/console/pubsub/webhook/notifications_test.exs
We currently send notifications for build statuses to slack from console, but we don't actually send notifs for new in-app notifications.  Seems like an oversight we ought to fix.
Wrote unit tests
Close #46
> slack notif sync

- assets/src/components/Login.js
This is a relic from when there were some annoying boot-time issues with the console, which are now far more robust.  So we don't have to be as noisy with these errors.
test locally
> Console log auth failure, don't print to screen

- lib/console/plural/models.ex
- lib/console/plural/queries.ex
- lib/console/services/plural.ex
This provides console support for multi-url oidc setup
Regression on existing unit tests
> Allow for multi-url recipes to be used for installation

- .gitignore
- assets/src/components/Socials.js
- assets/src/components/incidents/Incidents.js
- assets/src/components/users/Directory.js
- Use optional chaining to avoid null errors (fixes account view for non-admin users)
- Fix potential security issue (warning during build)
- Remove unused import (warning during build)
- Add more IDE files to .gitignore
- Manually checked `me` object and it contains `null` for non-admin users. This should not impact admin users at all.
- Manually checked social links.
> Fix account view

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
It bumps version in Helm chart to complete testing process from https://github.com/pluralsh/console/pull/62#issuecomment-1184456307. I've used `make bump-version` script without any other manual changes.
> Bump version

- assets/src/components/graphql/plural.js
- assets/src/components/kubernetes/StatefulSet.js
- assets/src/components/repos/Configuration.js
- assets/src/setupProxy.js
We previously only used updated pods to visualize statefulset deployment progress because zalando pg didn't have readiness probes and were most statefulsets in the wild.   Fixing the probe placement there should enable this also to be fixed.
viewed using `make web`
> Fix readiness graph

- assets/src/components/repos/Configuration.js
We need to at least always provide an empty map when installing recipes, otherwise plural build will trip up
tested locally
> Auto populate empty configuration in recipe install

- .github/workflows/publish.yaml
- .github/workflows/push-to-plural.yaml
- .github/workflows/test.yaml
With the new Release process `plural apply` was only set to run when new git tags are created. However, that workflow is mainly aimed at creating a new build of the console and not the necessarily the artifact (which Renovate will do). So `plural apply` should be run on the master branch when the plural artifact is updated with the new container tag.
> run plural apply on pushes to master

- .github/release.yml
- .github/workflows/publish.yaml
Adds an action to create a GitHub release when a new release tag is created.
> add action to generate github release

- Dockerfile
Changes the dockerfile so Renovate gets the kubectl version from the kubernetes repository since the kubectl repo doesn't have good tagging.
> fix dockerfile for renovate

- assets/src/components/Logs.js
- assets/src/components/graphql/dashboards.js
Loki in distributed mode is pretty slow, fetching a lot at once will help reduce total query count and keep it relatively sane
local
> Bump logs fetch limit to help loki

- README.md
- lib/console/graphql/users.ex
- lib/console/schema/notification.ex
- lib/console/services/alertmanager.ex
- priv/repo/migrations/20221118165510_add_notification_status.exs
- test/console/services/alertmanager_test.exs
We don't sync in alertmanager's firing/resolved state on the notification text, should do that now
modified unit tests
> Add notification status

- lib/console/deployer.ex
- lib/console/plural/context.ex
- lib/console/schema/leader.ex
- lib/console/services/leader_election.ex
- lib/console/services/plural.ex
- lib/console/storage.ex
- lib/console/storage/git.ex
- priv/repo/migrations/20221128153822_add_leaders.exs
- test/console/plural/context_test.exs
- test/console/services/leader_election_test.exs
- test/support/factory.ex
Currently we allow git updates to occur on any node in the console's cluster.  This can easily split brain and is not ideal, but needed to devise a specific leader election system to improve it. This uses postgres as coordinator, and allows for electing deployer pids as cluster leaders using a simple mechanism:
* any deployer requests leadership, first wins
* leader emits a heartbeat that expires after three missed beats
* on deployer teardown, force delete leader records to speed up reelection
* follower nodes rpc to the leader using distributed erlang, with fallback to themselves if none exists
Also added some more git cleaning logic
added unit tests, will test new release heavily as well
> Console leader election

- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml
- plural/helm/console/values.yaml.tpl
If you've shared a repo, we don't template in the enc key anymore, which can be a weird state if someone's shared prior to a deploy
local link
> Add better templating for repo encryption key

- .github/workflows/assets.yaml
- .github/workflows/codeql.yml
- .github/workflows/firebase-hosting-pull-request.yml
- .github/workflows/pr-labels.yaml
- .github/workflows/publish-cypress.yaml
- .github/workflows/publish.yaml
- .github/workflows/push-to-plural.yaml
- .github/workflows/test.yaml
- .tool-versions
The setup of Erlang 23 will fail if `ubuntu-latest` is used in the actions. This PR pins the ubuntu version for all the tests so they are consistent. It also has the CI setup Erlang and Elixir based on the `.tool-versions` file, so that the version run by CI is consistent with the version used during development.
> fix: CI by reading .tool-versions and pin ubuntu

- lib/console/deployer.ex
- lib/console/deployer/operations.ex
- lib/console/graphql/resolvers/plural.ex
- lib/console/runbooks/action.ex
- lib/console/runner.ex
- lib/console/services/runbooks.ex
- test/console/deployer_test.exs
- test/console/runner_test.exs
- test/support/test_helpers.ex
This makes some changes to the deployer and runner in the console, responsible for build execution:
* moves some helper functions to a separate function to clean up the code
* moves execution of build operations to sequential callbacks instead of a single one
* this makes cancellation easier because it can get in-between messages
added unit tests
> Refactor deployer and runner

- lib/console/graphql/resolvers/kubernetes.ex
- mix.exs
- mix.lock
- test/support/kubernetes_scaffolds.ex
The ingress deprecation broke ingress views on newer k8s versions, we need to bump our supported client to handle this
existing tests, will test on our console as well before release
> Use updated elixir k8s client

- lib/console/commands/command.ex
- lib/console/graphql/build.ex
- lib/console/schema/command.ex
- lib/console/services/builds.ex
- test/console/commands/command_test.exs
- test/console/commands/tee_test.exs
We currently only persist command output per-line, which works except that a lot of commands have very long pauses per-line.  Use in-memory caching to save overusing the database for this, and have a fallback when the cache misses to what's currently persisted to approximate a continuous db-write.
existing tests pass, will try a live test after merge
> Cache command output locally

- lib/console/graphql/plural.ex
- lib/console/plural/models.ex
- test/console/graphql/queries/plural_queries_test.exs
It is needed by the installer to properly determine if input fields should be required or not.
Locally
> feat: Expose optional field on the recipe configuration

- lib/console/graphql/build.ex
- lib/console/graphql/resolvers/build.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/schema/build.ex
- lib/console/schema/user.ex
- lib/console/services/users.ex
- priv/repo/migrations/20230125163535_add_build_timestamp.exs
- test/console/graphql/mutations/user_mutations_test.exs
- test/console/graphql/queries/build_queries_test.exs
Counts all builds and breaks out the count by build type, from your last read timestamp
unit test
> Add build info query

- plural/terraform/aws/deps.yaml
- plural/terraform/aws/node-group.tf
- plural/terraform/aws/variables.tf
Add a variable to potentially remove this and a moved block to make applies painless
local link
> Make console node group optional

- lib/console/plural/context.ex
- lib/console/services/builds.ex
- test/console/services/builds_test.exs
Imitate the plural cli here and don't create destroy builds if the repo is protected
unit test
> Add protection support for destroy builds

- lib/console/services/plural.ex
- test/console/services/plural_test.exs
I think the change to implement leader election w/ console deployers screwed with this logic a bit causing us to try to call the genserver w/in its own callback, effectively deadlocking.  This should unblock.
fixed unit test
> Fix SMTP update

- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/schema/role.ex
- test/console/graphql/queries/user_queries_test.exs
Simply imitate the other search queries
added test
> Add role search

- assets/src/components/apps/app/components/component/info/Ingress.tsx
- assets/src/components/cluster/constants.ts
- assets/src/components/cluster/containers/ContainersList.tsx
- assets/src/components/cluster/pods/Pods.tsx
- assets/src/components/cluster/queries.js
- assets/src/components/graphql/kubernetes.js
- assets/src/generated/graphql.ts
- lib/console/plural/queries.ex
- lib/console/plural/repositories.ex
- test/console/graphql/queries/plural_queries_test.exs
I think a lot of the performance here is getting drained at the graphql layer, at which point we just need to paginate, but this should shave a few seconds off.  Two main things are:
* use the cached pods endpoint
* don't query the raw field on each pod, which causes gql to serialize the full yaml structure for each one which adds up
local
> Speed up pods view

- assets/src/components/repos/installer/Installer.tsx
- assets/src/components/repos/installer/query.ts
Used custom repositories query for the installer to get an actually full list of repositories (`SEARCH_REPOS` only gets first 20). Since wizard does not support proper pagination/virtual scrolling right now, we can't benefit from using query param in the GQL query.
Locally
---
- https://app.asana.com/0/0/1203911145305919
> Get a full list of repos for the installer

- lib/console/graphql/kubernetes/vpn.ex
- lib/console/services/vpn.ex
- lib/kube/client.ex
- test/console/graphql/queries/kubernetes_queries_test.exs
- test/support/kubernetes_scaffolds.ex
k8s labels don't permit special chars, so need to use annotations unfortunately
modified unit tests
> Use annotations instead of labels

- .github/workflows/test.yaml
- Makefile
- assets/codegen.yml
- assets/package.json
- assets/src/generated/graphql.ts
- schema/schema.graphql
Similarly to what we do on the main app now, this PR uses a local version of the GraphQL schema to generate the TS types and functions. This removes the need to release the console for an API change before the frontend work can continue. It also ensures that API changes that would break the frontend can be caught and fixed in the same PR.
> Use local GraphQL schema for TS generation

- assets/src/components/apps/app/config/ConfigurationSettings.tsx
- assets/src/components/apps/app/runbooks/runbook/display/DisplayButton.tsx
- assets/src/helpers/url.js
most runbooks specify redirect url to '/' which was the builds page on legacy console but not anymore, this will autowire it and not require all runbooks to be rewritten as a result.
Also fix redirect for config overlay updates
local
> Fix redirect urls for builds and configuration

- assets/src/components/account/groups/GroupsList.tsx
- assets/src/components/account/roles/RolesList.tsx
- assets/src/components/account/users/UsersList.tsx
- assets/src/components/account/webhooks/WebhooksList.tsx
- assets/src/components/apps/app/logs/LogContent.tsx
- assets/src/components/apps/app/logs/LogLine.tsx
- assets/src/components/incidents/Incident.jsx
Updated all `mapper` functions in `<StandardScroller>` components to have `key` props set. This fixes issue with component states getting out of sync with the underlying data.
> fix: Data syncing issue with virtualized lists

- assets/src/components/apps/app/logs/LogContent.tsx
- assets/src/components/apps/app/logs/Logs.tsx
- assets/src/components/apps/app/logs/LogsCard.tsx
- assets/src/components/apps/app/logs/LogsFullScreen.tsx
- assets/src/components/cluster/pods/Pod.tsx
- assets/src/components/cluster/pods/PodInfo.tsx
- assets/src/components/cluster/pods/PodLogs.tsx
- assets/src/components/cluster/pods/PodSideNav.tsx
- assets/src/components/cluster/pods/PodsList.tsx
- assets/src/components/hooks/useNamespaceIsApp.tsx
- assets/src/components/layout/AppNav.tsx
- assets/src/routes/clusterRoutes.tsx
Created a new 'Logs' tab for Pods pages that have no associated apps. Pods without an associated apps will have the 'View logs' button direct to this tab while pods with apps will still be linked to the App page's logs tab.
---
- https://app.asana.com/0/0/1203951917789151
> fix: Console Pod Logs broken if not in a plural application

- plural/plural/recipe/console-aws-cluster-api.yaml
- plural/plural/recipe/console-azure-cluster-api.yaml
- plural/plural/recipe/console-gcp-cluster-api.yaml
- plural/terraform/aws/deps.yaml
- plural/terraform/azure/deps.yaml
- plural/terraform/gcp/deps.yaml
This PR updates the recipes to allow for testing with CAPI and modifies the TF to make it compatible for the testing.
> feat(capi): add recipes and modify tf to make compatible with CAPI testing

- assets/src/components/repos/installer/Installer.tsx
- assets/src/components/repos/installer/helpers.tsx
- assets/src/generated/graphql.ts
- schema/schema.graphql
When building dependency steps already installed apps will not be visible.
Locally by installing few apps via dev console.
> feat: Hide installer steps for already installed apps

- lib/console/services/users.ex
- test/console/services/users_test.exs
Sync admin state from id tokens on console logins.  Users keep tripping up on this so just auto-sync it for now.  If requested, we can killswitch this functionality.
n/a
> feat: Sync admin state in console logins

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/deployment.yaml
- plural/helm/console/templates/migration.yaml
- plural/helm/console/values.yaml
The last PR to set the default image tag wasn't set on the migration container. This adds that back as well as templating in the init container image.
> fix: set missing image tag for migration

- lib/console/services/plural.ex
- lib/loki/client.ex
- lib/prometheus/client.ex
- plural/helm/console/Chart.yaml
- plural/helm/console/values.yaml.tpl
- rel/config/config.exs
- test/console/graphql/queries/observability_queries_test.exs
- test/console_web/controllers/log_controller_test.exs
Allows console to be compatible w/ trace shield clusters. Can work on multitenancy later.
n/a
> Allow tenant headers to be injected into grafana stack clients

- assets/src/components/cluster/containers/Container.tsx
> fix: Width of container select dropdown too large

- docker-compose.yml
- lib/console/services/users.ex
- test/console/services/users_test.exs
This used to be able to happen (should be fixed in plural core) due to account transfers.  There are still some users out there with dupe groups so should make console handle it explicitly.
unit test
> Make bootstrap_user robust to duplicate groups

- plural/helm/console/Chart.yaml
- plural/helm/console/templates/deployment.yaml
- plural/helm/console/values.yaml
This change allows us to easily swap baked-in CLI in the console with a custom CLI from our docker image pushed by every PR.
To replace CLI with a new version simply add to the `values.yaml`:
```yaml
console:
cliContainer:
enabled: true
image:
tag: pr-455
```
Manually with a console link on our cd-demo cluster.
> feat: allow overriding CLI version used by console via helm config

- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/services/ServiceSelector.tsx
- assets/src/components/cd/services/Services.tsx
- assets/src/components/cd/services/ServicesFilters.tsx
- assets/src/components/cd/services/component/ServiceComponent.tsx
- assets/src/components/cd/services/service/ServiceComponents.tsx
- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
- assets/src/components/cd/services/service/ServiceSecrets.tsx
- assets/src/components/component/ComponentDetails.tsx
- assets/src/components/component/info/CronJob.tsx
- assets/src/components/component/info/Pods.tsx
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/cdRoutesConsts.tsx
- updated services overview to be a single view and use `clusterId` instead of `clusterName`
- service details view is now a child view of a cluster since every service belongs to a cluster
- clusters filter on services overview is now local and filters services by refetching instead of navigating to a separate view
- fixed pod details view accessible from cluster service component details view
Locally
> feat: update cluster/services routes and fix cluster pod detail view

- assets/src/components/cd/ContinuousDeployment.tsx
- assets/src/components/cd/GitScaffoldTabs.tsx
- assets/src/components/cd/PrepareGitStep.tsx
- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/cd/clusters/Clusters.tsx
- assets/src/components/cd/clusters/create/ImportClusterContent.tsx
- assets/src/components/cd/scaffoldTabs.tsx
- assets/src/components/cd/utils/demoData.ts
- assets/src/components/cd/utils/useCDEnabled.tsx
- assets/src/components/utils/MakeInert.tsx
- assets/src/components/utils/layout/FullHeightTableWrap.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/users.graphql
- assets/src/routes/cdRoutesConsts.tsx
- Now shows appropriate messaging on Clusters page for when CD is disabled or no clusters exist yet, along with a disabled table fully of fake data. 
- Scaffolds messaging has been removed from git import. 
- Better scrolling behavior on certain Cluster tabs.
TODO: Add extra instructions and demo video below fake table for empty cluster list
> feat: Clusters demo page

- assets/src/components/cd/ContinuousDeployment.tsx
The wrong intial scroll behavior was set for CD pages, such that scrolling is wrong until the user navigates to `cd/clusters`
> fix: Inconsistent scrolling behavior on CD pages

- assets/src/generated/graphql.ts
- charts/console/Chart.yaml
- charts/console/templates/_helpers.tpl
- charts/console/templates/ingress.yaml
- charts/console/values.yaml
- lib/console/deployments/pipelines.ex
- lib/console/deployments/policies/policies.ex
- lib/console/external_graphql.ex
- lib/console/graphql/deployments.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/schema/gates/job_spec.ex
- lib/console/schema/pipeline_gate.ex
- priv/repo/migrations/20231116182334_add_job_status.exs
- schema/schema.graphql
- test/console/deployments/pipeline_test.exs
- test/console/graphql/mutations/deployment_mutations_test.exs
- test/console/graphql/queries/deployment_queries_test.exs
Adds the data schema for simplified and full complexity job gates, and the apis needed for the agent to:
* poll for new eligible gates to execute
* update status based on the results
unit tests added throughout
> Basic Job Gate specification

- assets/src/components/cd/clusters/create/CreateClusterContent.tsx
- assets/src/components/cd/clusters/create/NameVersionHandle.tsx
- assets/src/components/cd/clusters/runtime/ExpandedColumn.tsx
- assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/utils/semver.ts
Small tweak to version selector to sort versions using semver comparison by descending order (newest first).
Locally
> fix: use semver sort for cluster version

- lib/console.ex
- lib/console/deployments/services.ex
- lib/console/schema/revision.ex
- lib/console/schema/service.ex
- priv/repo/migrations/20231201032016_add_kustomize_revisions.exs
- test/console/deployments/services_test.exs
helm services can partial update the helm struct which then doesn't get fully persisted in revisions
n/a
> fix small revision history bug

- lib/console/schema/cluster.ex
- test/console/deployments/clusters_test.exs
- test/console/graphql/mutations/deployment_mutations_test.exs
This can mess with the terraform provider in weird ways, will keep the api from auto-reconciling it (but will likely also need a frontent change to also respect that this is the new api behavior)
unit tests
> Don't autoreconcile eks semvers

- assets/src/components/cd/pipelines/Pipeline.tsx
- assets/src/components/cd/pipelines/Pipelines.tsx
- assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
- assets/src/routes/cdRoutes.tsx
- assets/src/routes/cdRoutesConsts.tsx
- Fixed: Every time you loaded a new Pipeline, the dagre layout engine wouldn't forget the previous pipelines, so the layout would get progressively pushed down the page. Now properly resetting dagre for each new Pipeline.
- Feature: Added urls to link directly to specific pipelines
> feat: Pipeline routing + layout fix

- lib/console.ex
- rel/config/console.exs
This is to improve the ux of plural up, making the console still "byok" but the console's provider registered according to its cloud.
n/a
> Add a basic byok override

- controller/config/samples/cluster_azure.yaml
- controller/config/samples/cluster_gcp.yaml
- controller/internal/client/cluster.go
- controller/internal/controller/cluster_controller.go
When errors appeared before assigning readonly status but after resource creation in Console, then in second reconcile loop resource was marked as readonly. Now this will no longer happen.
> fix: Fix cluster reconciler error handling

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster.ex
- lib/console/schema/tag.ex
- schema/schema.graphql
- test/console/graphql/queries/deployments/cluster_queries_test.exs
Allows users to multiselect tag pairs, then chose if they want to and or or them.
unit tests
> Add conjunctive tag queries

- lib/console/deployments/helm/cache.ex
- lib/console/deployments/helm/server.ex
There seem to be head-of-line blocking issues with the current cache, this model will basically do the following:
* read from cache if found directly, never hit HTTP if so
* if not present, read from http, write to disk, then defer a cast to the server to write a touch pointer
* use same hourly timeout to expire using the touch pointers
This should remove all serialization via the genserver on the chart read path
unit
> Migrate helm chart cache to write-after

- assets/.gitignore
- assets/package.json
- assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
- assets/src/components/hooks/useUpdateState.tsx
- assets/src/utils/isNonNullable.ts
- assets/src/utils/isSubsetEqual.test.ts
- assets/src/utils/isSubsetEqual.ts
- assets/yarn.lock
Service pages could get stuck in an infinite render loop when the chart version didn't match any of the versions in the selected chart. I fixed this by preventing `useUpdateState` from updating its internal state when the update would result in an equivalent state, thus preventing the `setVersion('')` call in `ChartForm` from causing re-renders that trigger that call again (and again (and again (...)).
> fix: Infinite render on some Service Settings pages

- lib/console/deployments/compatibilities/schema.ex
- test/console/graphql/queries/deployments/cluster_queries_test.exs
we actually determine blocking for the current k8s vsn not the next one (which is more relevant for upgrades)
units
> Check if an add-on is blocking for next not current k8s version

- assets/src/components/builds/build/progress/Command.tsx
- assets/src/components/builds/build/progress/CommandExitStatus.tsx
- assets/src/components/builds/build/progress/CommandLog.tsx
- Move exit status next to the timer, so it's always in the same place
- Use design system icons instead of text symbols, move exit status to tooltip
- Highlight command lines and add more padding to make them move visible
- Force constant width on the line number column
Before: 
After:
> feat: Build progress improvements

- assets/src/generated/graphql.ts
- lib/console/deployments/git.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/schema/pipeline.ex
- schema/schema.graphql
- test/console/deployments/git_test.exs
- test/console/graphql/mutations/deployments/services_mutations_test.exs
Should simplify the onboarding process for renovate a lot, inferring all the main inputs from either the servers config itself, or created access tokens or other db objects.
unit tests
> Consolidated renovate setup api

- assets/src/generated/graphql.ts
- lib/console/deployments/git.ex
- lib/console/deployments/pr/dispatcher.ex
- lib/console/deployments/pr/impl/github.ex
- lib/console/deployments/pr/impl/gitlab.ex
- lib/console/deployments/pr/impl/pass.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/graphql/schema/base.ex
- lib/console/schema/pipeline_gate.ex
- lib/console/schema/scm_webhook.ex
- lib/console_web/controllers/webhook_controller.ex
- lib/console_web/router.ex
- priv/repo/migrations/20240209225431_add_scm_webhook_owner.exs
- schema/schema.graphql
- test/console/deployments/git_test.exs
- test/console/graphql/mutations/deployments/git_mutations_test.exs
- test/console/graphql/queries/deployments/git_queries_test.exs
- test/test_helper.exs
Use the access token we've already been issued to create the webhook entry to watch for statuses.
unit tests
> Auto-create SCM webhooks when registering connections

- lib/console/graphql/kubernetes/job.ex
- lib/kube/models.ex
Pods/logs don't have the error handler middleware attached
> Add error handlers appropriately

- .tool-versions
- README.md
- assets/src/generated/graphql.ts
- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/discovery.ex
- lib/console/deployments/services.ex
- lib/console/graphql/configuration.ex
- lib/console/graphql/deployments/backup.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/kubernetes/config.ex
- lib/console/graphql/middleware/cd_authed.ex
- lib/console/graphql/resolvers/deployments/service.ex
- lib/console/schema/object_store.ex
- lib/console/schema/service.ex
- priv/repo/migrations/20240216001533_add_services_templated.exs
- schema/schema.graphql
- test/console/graphql/queries/kubernetes_queries_test.exs
- test/console/graphql/queries/user_queries_test.exs
Need the latter for velero setup.  Also realized service secret fetching is very effectively cacheable, so doing that.
regression
> Add support for toggling templating on a service, and azure resource group config

- assets/src/generated/graphql.ts
- lib/console/deployments/backups.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster.ex
- schema/schema.graphql
- test/console/deployments/backups_test.exs
Currently we (correctly) set deletion protection on velero services, but that also makes the delink api break.  This fixes this in one transaction.
modify test
> Fix service delinking for deletion protected svcs, enable backup filtering

- assets/src/generated/graphql.ts
- controller/api/v1alpha1/prautomation_types.go
- lib/console/deployments/services.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/schema/persona.ex
- lib/console/services/users.ex
- priv/repo/migrations/20240217015346_add_personas.exs
- priv/repo/seeds/06_personas.exs
- schema/schema.graphql
- test/console/graphql/mutations/user_mutations_test.exs
- test/console/graphql/queries/user_queries_test.exs
- test/support/factory.ex
Defines core graphql schemas for user personas. These will allow us to reconfigure the ui in an orderly way at scale for teams that want to hide specific functionality as needed.
unit tests
> Add schemas for personas

- assets/src/components/contexts/DeploymentSettingsContext.tsx
- assets/src/components/layout/Sidebar.tsx
Looks like one of global contexts had cd check that forced user redirect to clusters view. This should fix it.
Locally
> fix: do not always redirect to CD page 

- assets/src/components/pr/queue/PrQueueColumns.tsx
Fixes external link in this modal:
> fix: Link to PR not working when PR list is inside modal

- assets/src/components/pr/queue/PrQueueColumns.tsx
OPEN → 'warning' (yellow)
MERGED → 'success' (green)
CLOSED → 'danger' (red)
https://linear.app/pluralsh/issue/ENG-1883/pr-status-color-map-is-off
> fix: PR status chip colors

- assets/src/components/pr/automations/CreatePrModal.tsx
Split PR Automation creation into a stepper w/ two steps
- first step is the inputs wizard, and we should have a description header explaining what's going on, eg "Provide some basic configuration for this PR:"
- Second step should confirm prior inputs (can just be a code block with the json of the context from prior step) and an input w/ the branch name of the PR
> feat: PR automation modifications

- assets/src/components/notifications/routers/CreateNotificationRouterModal.tsx
- assets/src/components/notifications/routers/EditNotificationRouterModal.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/notifications.graphql
**_Note:_** Still need docs link for Create Notification Router modal (currently links to root of docs.plural.sh)
- Fix typeahead search in Sink combobox not working
- Remove some unneeded dev code
> fix: Sink search not working when editing notification router

- assets/src/components/apps/app/components/ComponentList.tsx
- assets/src/components/apps/app/components/Components.tsx
- assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
- assets/src/components/cd/services/service/ServiceKick.tsx
- assets/src/components/component/info/Service.tsx
- New sort order for components
-   'deployment', 'statefulset', 'daemonset', 'ingress', 'cronjob',  'job',  'service', 'certificate',  'secret', 'configmap', then alphabetical
- Fix margins on `Resync Service` button
- Update formatting for port ranges
---
---
> fix: UI/UX layout issues

- assets/src/components/PluralApi.jsx
I think a change to `buildClient` is causing us to always redirect to / on the accounts page, this should fix.
local
> Fix annoying redirect bug

- Dockerfile
- assets/src/generated/graphql.ts
- lib/console/deployments/events.ex
- lib/console/deployments/pubsub/protocols/broadcastable.ex
- lib/console/deployments/services.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments/service.ex
- rel/config/console.exs
- schema/schema.graphql
- test/console/deployments/services_test.exs
- test/console/graphql/mutations/deployments/services_mutations_test.exs
- test/console/graphql/queries/deployments/service_queries_test.exs
There's a meaningful usecase to understand the generated yaml for a service post-templating.  Think of it as being able to run `helm template` from within our ui instead of locally. Our dry run experience somewhat accomplishes this but will fail for misformatted yaml or other edge cases.
unit tests
> Add apis for managing template viewing in-ui

- assets/src/generated/graphql.ts
- lib/console/deployments/global.ex
- lib/console/graphql/deployments/global.ex
- lib/console/graphql/resolvers/deployments/global.ex
- lib/console/schema/revision.ex
- lib/console/schema/service_template.ex
- priv/repo/migrations/20240330214528_add_service_template_secrets.exs
- schema/schema.graphql
- test/console/deployments/global_test.exs
- test/console/graphql/mutations/deployments/global_mutations_test.exs
- test/console/graphql/queries/deployments/service_queries_test.exs
This makes them fully at parity with global services spawned by another service.
unit test
> Allow setting secrets on template global services

- assets/src/generated/graphql.ts
- lib/console/deployments/clusters.ex
- lib/console/deployments/policies/rbac.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/pinned_custom_resource.ex
- priv/repo/migrations/20240328143552_add_pinned_custom_resources.exs
- schema/schema.graphql
- test/console/deployments/clusters_test.exs
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
- test/console/graphql/queries/deployments/cluster_queries_test.exs
- test/support/factory.ex
Useful for customizing the dashboard CRD view, can be pinned globally or by cluster
unit tests
> Add pinned custom resources api

- assets/src/components/cd/services/ServicesColumns.tsx
- assets/src/components/cd/services/ServicesResyncDeployment.tsx
Add a refresh button to the services table action column
> add resync button to services table action column

- assets/src/components/pr/scm/EditScmConnection.tsx
Switched from `InputRevealer` component to `Input` component in order to use it's `multiline` feature. We lost the hide/show feature though.
I also checked and it does keep the new lines in the text.
> use multiline input for smc connection private key

- assets/src/components/cd/YamlGeneratorModal.tsx
[as requested by @zreigz in `cd` channel](https://plural-labs.slack.com/archives/C05SRM1JEM8/p1713194287831209)
It fixes wrong fields in the global service generated yaml
- distro instead of distribution,
- all provider names in capital letters: GENERIC,EKS,AKS,GKE,RKE,K3S
- remove distro field in case of all providers
> fix generated global service yaml

- lib/console/deployments/global.ex
- test/console/deployments/global_test.exs
We were overmarking services as different because of a bool logic error
unit test
> Fix reconciliation logic for managed namespace

- controller/internal/client/cluster.go
- controller/internal/client/console.go
- controller/internal/client/pipeline.go
- controller/internal/client/prautomation.go
- controller/internal/client/provider.go
- controller/internal/client/restore.go
- controller/internal/client/scmconnection.go
- controller/internal/controller/cluster_controller.go
- controller/internal/controller/cluster_controller_test.go
- controller/internal/controller/clusterrestore_controller.go
- controller/internal/controller/clusterrestore_controller_test.go
- controller/internal/controller/pipeline_controller.go
- controller/internal/controller/pipeline_controller_test.go
- controller/internal/controller/prautomation_controller.go
- controller/internal/controller/prautomation_controller_test.go
- controller/internal/controller/provider_controller.go
- controller/internal/controller/provider_controller_test.go
- controller/internal/controller/scmconnection_controller.go
- controller/internal/test/mocks/ConsoleClient_mock.go
Some controllers assumed that when there is an error different than not found it means that the resource does not exist. It was not always the case, i.e. on network error or timeout.
> fix(controller): existence checks now return error instead of false

- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/Navigation.tsx
- assets/src/components/kubernetes/customresources/CustomResourceDefinitions.tsx
- assets/src/components/kubernetes/customresources/PinCustomResourceDefinition.tsx
- assets/src/components/kubernetes/customresources/PinCustomResourceDefinitionModal.tsx
- assets/src/components/kubernetes/customresources/PinnedCustomResourceDefinitions.tsx
- Allow specifying display name for pinned CRDs
- It can be done in a simple modal
- CRD kind is used as default value
- Organize code in separate files
- Add error handling for Kubernetes clusters query
- Fix issue with broken links on Chrome
> feat: Allow specifying display name for pinned CRDs

- plural/helm/kas/Chart.yaml
- plural/helm/kas/templates/configmap.yaml
- plural/helm/kas/templates/deployment.yaml
- plural/helm/kas/templates/ingress.yaml
- plural/helm/kas/templates/service.yaml
- plural/helm/kas/values.yaml
Added simple nginx sidecar container to rewrite websocket traffic on a subpath to kas agent server.
Locally with kind
> feat: use nginx sidecar to allow exposing grpc agent server on a subpath

- lib/console/graphql/exceptions/protocol.ex
- lib/console/graphql/middleware/safe_resolution.ex
Looks like the k8s controller likes to feed the api lots of empty strings, which we're currently throwing 400-like errors for because they can't be cast as guids.  Treat them like not-founds instead.
n/a
> Fix error handling for query cast errors

- lib/console/deployments/stacks.ex
- lib/console/schema/stack_environment.ex
- test/console/deployments/stacks_test.exs
- test/console/graphql/mutations/deployments/stack_mutations_test.exs
Wasn't in the schema
Also fixes the stack environment duplication bug.
unit
> Fix stack secret persistence

- charts/console/Chart.yaml
- charts/console/templates/deployment.yaml
- charts/console/templates/migration.yaml
- charts/console/values.yaml
- charts/controller/Chart.yaml
- charts/controller/templates/deployment.yaml
- charts/controller/values.yaml
The new sidecar nginx rewrite should take precedence, and can now deprecate the old rewrite ingress solution.
tested on boot-aws
> Remove rewrite ingress by default

- lib/console/deployments/cron.ex
- lib/console/schema/stack_file.ex
- test/console/deployments/cron_test.exs
This is why stacks/stack runs aren't dequeueing.  Will add test in a second.
> Need to actually run streams in crons

- assets/src/generated/graphql.ts
- lib/console/deployments/services.ex
- lib/console/graphql/deployments/service.ex
- lib/console/schema/service.ex
- lib/console/schema/service_dependency.ex
- lib/console_web/controllers/git_controller.ex
- priv/repo/migrations/20240423154912_add_service_dependencies.exs
- schema/schema.graphql
- test/console/deployments/services_test.exs
- test/console_web/controllers/git_controller_test.exs
- test/support/factory.ex
Our current mechanism is only enforced by the operator, which is not easily compatible with global services and other subsystems.  This will be able to globally enforce dependencies.  The general flow is:
* declare a service dependency (within the same cluster and by name, so it can anticipate a service spawned by global services, etc)
* manifest rendering will error until all dependencies are ready, preventing service actualization
* when the dependency becomes ready, it marks all associations with a ready state to enable manifest rendering
unit tests
> Implement api-level service dependencies

- assets/src/generated/graphql.ts
- lib/console/deployments/services.ex
- lib/console/graphql/deployments/service.ex
- lib/console/schema/service.ex
- schema/schema.graphql
This would enable a user to specify a git repo for the chart and another git repo for the values.
existing tests
> Add support for git repositories as a helm chart source.

- assets/package.json
- assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
- assets/yarn.lock
Also noticed we were actually overfetching runtime service + deprecation data for each cluster on load, small refactor + added a skip arg to the query to prevent apollo from fetching unless necessary.
local
> Add empty states for cluster flyover accordions

- assets/src/components/cd/clusters/ClustersColumns.tsx
- lib/console/deployments/stacks.ex
- lib/console/external_graphql.ex
This fixes a small agent bug caused by sideloading the approver in the agent's stack fetch client calls
Fixes ENG-2037
n/a
> Need to add user dataloader to ext gql api

- charts/controller/crds/deployments.plural.sh_globalservices.yaml
- charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
- controller/api/v1alpha1/globalservice_types.go
- controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
- controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
- controller/docs/api.md
- plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
- plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Used a . accidentally for a separator
n/a
> Fix detach in crd typing

- assets/src/generated/graphql.ts
- lib/console/deployments/cron.ex
- lib/console/deployments/git/cache.ex
- lib/console/deployments/git/cmd.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/policy.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/policy.ex
- lib/console/schema/stack.ex
- lib/console/schema/stack_run.ex
- lib/console/schema/stack_state.ex
- priv/repo/migrations/20240506193611_add_run_message.exs
- schema/schema.graphql
- test/console/deployments/cron_test.exs
- test/console/deployments/pubsub/recurse_test.exs
- test/console/deployments/stacks_test.exs
We were keeping the run id when adding state to the owning stack (not just the run) which led to a unique constraint violation
unit test
> Fix stack state persistence bug

- assets/src/components/account/personas/PersonaAttributesEdit.tsx
- assets/src/components/account/personas/PersonaCreate.tsx
- assets/src/generated/graphql.ts
- lib/console/deployments/cron.ex
- lib/console/deployments/global.ex
- lib/console/deployments/services.ex
- lib/console/graphql/kubernetes.ex
- lib/console/graphql/users.ex
- lib/console/schema/persona.ex
- schema/schema.graphql
Configures whether a user should see manager/security views for the home screen
n/a
> Add homepage persona settings

- controller/internal/controller/cluster_controller.go
Fix cluster deletion when the cluster is in an error state
> fix cluster deletion

- lib/console/deployments/global.ex
- lib/console/deployments/pubsub/recurse.ex
- lib/console/schema/global_service.ex
- lib/console/schema/service.ex
- test/console/deployments/global_test.exs
- test/console/deployments/pubsub/recurse_test.exs
- test/console/graphql/queries/deployments/policy_queries_test.exs
We did this well when the global service was deleted but not on cluster tag changes or on global service spec changes.  This solves for both.
unit tests
> Proper draining of attached global services on non-delete actions

- assets/src/generated/graphql.ts
- lib/console.ex
- lib/console/deployments/policies/policies.ex
- lib/console/deployments/stacks/state.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/schema/stack.ex
- lib/console/schema/terraform_state.ex
- lib/console_web/controllers/stack_controller.ex
- lib/console_web/router.ex
- priv/repo/migrations/20240526120358_add_terraform_state.exs
- priv/repo/migrations/20240526201015_add_workdir.exs
- schema/schema.graphql
- test/console_web/controllers/stack_controller_test.exs
- test/support/factory.ex
This along with a agent-specified `_override.tf` file will allow us to serve as a built-in state store for terraform.
unit tests
> Implement terraform http state remote backend

- assets/src/components/stacks/StackRun.tsx
- assets/src/components/stacks/StackRunStatusChip.tsx
- assets/src/components/stacks/run/Sidecar.tsx
At the moment it shows a lot of these prematurely, having harness set this state appropriately solves for that.
n/a
> Use PENDING_APPROVAL state to control approve displays

- controller/internal/controller/cluster_controller.go
The crd should spin until it finds the cluster it references in byok mode
n/a
> Requeue not found clusters

- assets/src/components/stacks/run/Header.tsx
- assets/src/components/stacks/run/Route.tsx
- assets/src/components/stacks/run/job/RunJob.tsx
- assets/src/components/stacks/run/job/RunJobLogs.tsx
- assets/src/components/stacks/run/job/RunJobPods.tsx
- assets/src/components/stacks/run/job/RunJobSpecs.tsx
- assets/src/components/stacks/run/job/RunJobStatus.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/stacks.graphql
- assets/src/routes/stacksRoutes.tsx
- assets/src/routes/stacksRoutesConsts.tsx
- lib/console/deployments/policies/rbac.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/custom_stack_run.ex
- lib/console/schema/stack_run.ex
- priv/repo/migrations/20240528200501_add_custom_stack_runs.exs
- schema/schema.graphql
- test/console/deployments/stacks_test.exs
- test/console/graphql/mutations/deployments/stack_mutations_test.exs
- test/support/factory.ex
This can be really useful in case you need to do one-off tasks like repair terraform state or run a bash script.  The run still will occur in the exec environment of the stack, ensuring consistency w/ the terraform run itself.
Also adds a CustomStackRun schema which adds a self-service layer on top of this.
unit tests
> Implement the ability to trigger custom stack runs

- lib/console/cache.ex
- lib/console/deployments/settings.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- test/console/graphql/queries/deployments/stack_queries_test.exs
If we can't find a valid job spec, we should try to return the global settings job spec.
n/a
> Fallback to global settings for stack job spec

- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/common/DeleteResource.tsx
- Properly display delete error response in the delete resource dialog
- Improve k8s dashboard zerostate handling when there are no clusters
Locally
> fix: handle delete resource error better

- assets/src/components/account/groups/GroupCreate.tsx
- assets/src/components/account/groups/Groups.tsx
- assets/src/components/account/groups/GroupsColumns.tsx
- assets/src/components/account/groups/GroupsList.tsx
- assets/src/components/cd/utils/useFetchPaginatedData.tsx
apollo was throwing errors when trying to update the cache after creating or deleting new groups. recent update added a page size variable to the groups query so needed to fix the cache lookup to reflect that
> fix group mutation false errors

- lib/console/deployments/global.ex
- lib/console/schema/group.ex
- test/console/deployments/global_test.exs
- test/console/deployments/pubsub/recurse_test.exs
Noticed this happened with a recent change to the global services business logic.  This fix should resolve plus added tests to catch the regression in the future
unit tests
> Fix thrashing of templated global services

- assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
- assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
- assets/src/components/cd/globalServices/GlobalServicesTable.tsx
empty states were hiding the whole view instead of being rendered within the table
> fixed global service empty states

- assets/src/generated/graphql.ts
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/deployments/stack.ex
- schema/schema.graphql
Need to add `projectId` arg to `serviceDeployments` and `connectionId` field to `InfrastructureStackAttributes`
n/a
> Add minor schema oversights

- assets/src/components/cd/pipelines/job/PipelineJobPods.tsx
- assets/src/components/cluster/pods/PodsList.tsx
- assets/src/components/component/info/Pods.tsx
- assets/src/components/stacks/run/job/RunJobPods.tsx
all component pod lists were linking to the K8s dashboard, now only job and cron job lists will
(logic stays the same for pipeline and stack job tables, flag was just added to reflect the change to PodsList component)
> fix service component pod links

- assets/src/generated/graphql.ts
- lib/console/cron/job.ex
- lib/console/deployments/settings.ex
- lib/console/graphql/deployments/git.ex
- lib/console/schema/embeds.ex
- lib/console/schema/stack.ex
- schema/schema.graphql
- test/console/deployments/stacks_test.exs
Using the previous next run at to benchmark the next one has a possibility to off-by-one it seems, try to just always use current time.
n/a
> Fix cron next run at inference

- assets/src/components/pr/automations/PrConfigurationInput.tsx
Used an integer key instead of the actual string value
n/a
> The value for selects in the pr automation config was incorrect

- assets/src/generated/graphql.ts
- assets/src/graph/stacks.graphql
apollo wasn't correctly caching data from sub-queries within infrastructure stack objects. needed to add top-level stack's id so that it can track correctly
> fix caching issue with stack prs/runs

- lib/console/deployments/clusters.ex
- test/console/deployments/clusters_test.exs
We were not actually dropping runtime services when they were no longer found.  This logic will strip them out appropriately.
unit test
> Prune unfound runtime services

- assets/src/components/stacks/run/Header.tsx
A small change to hide some stack run tabs in case data is not available. Some tf/ansible versions might never have a proper state/output available.
Locally
> feat: hide state/plan/output tabs if data is not available

- assets/src/utils/cmdLineParse.test.ts
- assets/src/utils/cmdLineParse.ts
parses a string into an object with form {cmd: string, args: string[]}
> add command parser

- assets/src/components/pr/automations/CreatePrModal.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/cdPrs.graphql
- lib/console/deployments/git.ex
- lib/console/deployments/pipelines.ex
- lib/console/graphql/deployments/git.ex
- lib/console/graphql/deployments/pipeline.ex
- lib/console/graphql/resolvers/deployments/git.ex
- lib/console/schema/promotion_criteria.ex
- priv/repo/migrations/20240627005403_add_repository_promo_criteria.exs
- schema/schema.graphql
This will help users DRY up their automation code, which can be useful for when you want to stamp out repos alongside common lines
unit test
> Allow repository to be parameterized in pr automations

- assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
CSS.escape is only needed to wrap around the variable itself, rather than the whole selector. was causing nothing to get returned by the query
> fix flow layout bug

- assets/src/components/kubernetes/common/ResourceList.tsx
- assets/src/components/kubernetes/workloads/Pods.tsx
Fix for fetch policy on k8s dashboard resource list views. It will now get data from the cache if available to show immediately and at the same time make an API request to get the latest data.
Locally
> fix: properly cache-and-network on k8s dashboard resource lists

- assets/src/generated/graphql.ts
- lib/console/deployments/pipelines/stage_worker.ex
- lib/console/deployments/policies/policies.ex
- lib/console/deployments/stacks.ex
- lib/console/deployments/stacks/commands.ex
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/deployments/stack.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/deployments/stack.ex
- lib/console/schema/pull_request.ex
- lib/console/schema/run_step.ex
- lib/console/schema/service.ex
- lib/console/schema/stack.ex
- lib/console/schema/stack_definition.ex
- priv/repo/migrations/20240628202415_add_stack_definitions.exs
- priv/repo/migrations/20240630124210_add_polled_sha.exs
- schema/schema.graphql
- test/console/deployments/stacks_test.exs
- test/console/graphql/mutations/deployments/stack_mutations_test.exs
- test/support/factory.ex
This builds the backbone for custom stacks, a definition basically:
* defines the command workflow to be executed by a stack
* also sets common configuration for things like the base image to use.
also added a `triggerRun` mutation as I could see it being useful to programmatically execute these stacks via other tools
unit tests
> Custom Stack Definitions CRUD

- lib/console/commands/plural.ex
- lib/console/schema/pr_automation.ex
- test/console/deployments/git_test.exs
This was preventing repository fks from being set.
unit test
> Add repository id to pr automation changeset

- assets/src/components/stacks/run/state/State.tsx
- assets/src/components/stacks/state/StackStateGraph.tsx
also adds the react flow view to stack runs
> add fullscreen option to stack state

- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/cache.ex
- lib/console/deployments/git/discovery.ex
- lib/console/deployments/pipelines/stage_worker.ex
- lib/console/deployments/stacks.ex
Stacks need to query git for changes each poll interval to determine if 1. there's a new sha and 2. if there's a file that it's tracking that changed in that new sha.  This can theoretically lead to a lot of contention in the git cache.  this has already been partially solved by adding a tracking column to determine if a sha has already been polled, this change cache will also solve for many stacks polling against the same folder and thus reduce duplicate work there as well.
existing tests
> Add caching for change detection w/ stacks

- lib/console_web/plugs/cached_body_reader.ex
Think this might be new plug behavior, but regardless needs to be handled
n/a
> Need to handle {:more, _, _} clauses in cached body reader

- charts/controller/templates/manager-rbac.yaml
- lib/console_web/controllers/webhook_controller.ex
- lib/console_web/plugs/cached_body_reader.ex
Looks like this might be goofed due to fixing another thing w/ the cached body reader implementation
have to test on sandbox
> Fix broken webhook verifier

- controller/internal/controller/pipeline_controller.go
- controller/internal/controller/pipelinecontext_controller.go
- lib/console/graphql/deployments/service.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/service.ex
- test/console/graphql/mutations/deployments/services_mutations_test.exs
- test/console/graphql/queries/deployments/service_queries_test.exs
Pretty sure this is causing forbidden errors when using namespace credentials.  This feature isn't actively used, so disable for now.
n/a
> Scope evaluation is interfering with serviceaccount crd creds

- assets/src/components/cd/pipelines/PipelineContexts.tsx
- assets/src/components/cd/pipelines/PipelineDetails.tsx
- assets/src/components/cd/pipelines/context/PipelineContextDetails.tsx
- assets/src/components/cd/pipelines/job/PipelineJob.tsx
- assets/src/components/cd/pipelines/job/PipelineJobLogs.tsx
handful of queries related to pipelines were defaulting to cache-first instead of cache-and-network
> update pipeline queries fetch policies

- assets/src/generated/graphql.ts
- config/config.exs
- controller/internal/controller/servicedeployment_controller.go
- lib/console/deployments/policies/policies.ex
- lib/console/deployments/policies/rbac.ex
- lib/console/graphql/resolvers/user.ex
- lib/console/graphql/users.ex
- lib/console/schema/managed_namespace.ex
- lib/console/schema/service.ex
- lib/console/services/users.ex
- priv/repo/migrations/20240709123933_drop_parent_id_fkey.exs
- schema/schema.graphql
- test/console/graphql/mutations/user_mutations_test.exs
- test/support/factory.ex
This will let us generate a service tree view in the ui.  Also added a impersonateServiceAccount mutation.
Fixes PROD-2398
unit tests
> Add parentId to reconciled service deployments

- lib/console.ex
- lib/console/deployments/git.ex
- lib/console/deployments/git/agent.ex
- lib/console/deployments/git/discovery.ex
- lib/console/deployments/helm/agent.ex
- lib/console/deployments/helm/agent_cache.ex
- lib/console/deployments/helm/cache.ex
- lib/console/deployments/helm/charts.ex
- lib/console/deployments/helm/discovery.ex
- lib/console/deployments/services.ex
- lib/console_web/controllers/git_controller.ex
- lib/console_web/endpoint.ex
- lib/console_web/router.ex
- test/console/deployments/services_test.exs
- test/console_web/controllers/git_controller_test.exs
This will allow the agent to determine if downloading manifests can be bypassed, hopefully giving another meaningful increase in overall throughput for the agent.  It is annoyingly complex due to the fact we source manifests from many locations, but it should mirror the manifest tar logic and incorporate all information into a consistently compiled sha.
unit tests
> Implement manifest digest api

- assets/src/components/kubernetes/network/Service.tsx
causes some bugs on weird selector-less services (only seen w/ postgres operators)
n/a
> fix null entries call

- assets/src/components/pr/scm/EditScmConnection.tsx
was still sending a default struct for github attributes when using token auth
> fix scm connection updates

- controller/internal/controller/globalservice_controller.go
- controller/internal/controller/globalservice_test.go
- lib/console/deployments/git/cmd.ex
This toys around with trying to remove git pulls from the agent cache entirely.  Since it's been refactored to use local remote refs to find head commits, I think this is possible, and removes fringe possibilities of disturbing the working tree entirely.
n/a
> Pull-less git agent

- assets/src/components/cd/cluster/ClusterServices.tsx
- assets/src/components/cd/services/Services.tsx
certain scenarios were causing the service tables to trigger infinite render loops on scroll since the outlet context object wasn't memoized
this was also causing polling and refetching to be blocked
> fix service table infinite render

- assets/src/generated/graphql.ts
- lib/console/deployments/clusters.ex
- lib/console/deployments/git.ex
- lib/console/deployments/global.ex
- lib/console/deployments/pipelines.ex
- lib/console/deployments/policies/policies.ex
- lib/console/deployments/settings.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/observability.ex
- lib/console/graphql/resolvers/deployments/observability.ex
- lib/console/schema/helm_repository.ex
- rel/config/console.exs
- schema/schema.graphql
- test/console/deployments/clusters_test.exs
- test/console/deployments/services_test.exs
- test/console/deployments/settings_test.exs
- test/console/deployments/stacks_test.exs
The prior version accidentally used the configuration from a later version of Postgrex, this will work for our current pinned version
n/a
> Properly communicate ssl_opts in releases

- go/controller/internal/controller/infrastructurestack_controller.go
- go/controller/internal/controller/project_controller.go
Fixes:
- InfrastructureStack requeue time is too short
- Project CRD seems to not be updating bindings
> fix: update bindings and requeue time

- lib/console/deployments/services.ex
The prior implementation of this technically supported liquid-ified values, defer to only using static
n/a
> Fix helm values injection

- charts/controller/crds/deployments.plural.sh_prautomationtriggers.yaml
- go/controller/api/v1alpha1/prautomationtrigger_types.go
- go/controller/config/crd/bases/deployments.plural.sh_prautomationtriggers.yaml
- go/controller/docs/api.md
- go/controller/internal/client/console.go
- go/controller/internal/client/prautomation.go
- go/controller/internal/controller/prautomationtrigger_controller.go
- go/controller/internal/test/mocks/ConsoleClient_mock.go
- plural/helm/console/crds/deployments.plural.sh_prautomationtriggers.yaml
It was not aligned with the latest schema of the `createPullRequest` mutation. I have aligned the logic with the same resource in our terraform provider.
> fix(prautomationtrigger): pass identifier to the create pull request mutation

- assets/src/components/apps/app/runbooks/runbook/RunbookDisplay.tsx
- assets/src/components/apps/app/uninstall/Uninstall.tsx
- assets/src/components/billing/BillingFeatureBlockBanner.tsx
- assets/src/components/builds/build/changelog/Changelog.tsx
- assets/src/components/cd/cluster/node/NodeInfo.tsx
- assets/src/components/cd/clusters/create/provider/NodeGroupContainer.tsx
- assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
- assets/src/components/cluster/ScalingRecommender.tsx
- assets/src/components/cluster/nodes/ClusterMetrics.tsx
- assets/src/components/cluster/nodes/NodeInfo.tsx
- assets/src/components/cluster/nodes/Nodes.tsx
- assets/src/components/cluster/pods/PodMetadata.tsx
- assets/src/components/component/ComponentMetrics.tsx
- assets/src/components/stacks/create/CreateStackModalFormFiles.tsx
- assets/src/components/stacks/job/StackJob.tsx
- assets/src/components/stacks/overview/StackConfiguration.tsx
- assets/src/components/stacks/overview/StackMetadata.tsx
- assets/src/components/stacks/overview/StackRepository.tsx
- assets/src/components/utils/List.tsx
css properties set with honorable props seem to be getting overwritten by styled-components (strange side effect of removing Grommet). unclear what's causing this, but for now just fixed all the cards to use styled for their css instead of honorable in cases where this is a problem
> fix cards with missing padding

- go/controller/internal/client/observabilityprovider.go
A change in the client schema broke this
n/a
> Fix controller compilation

- Makefile
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/clusters.ex
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster.ex
- lib/console/services/base.ex
- lib/helm/interface/http.ex
- priv/repo/migrations/20240817162941_add_vclusters.exs
- schema/schema.graphql
- test/console/deployments/clusters_test.exs
- test/console/deployments/helm/agent_test.exs
- test/console/deployments/stacks_test.exs
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
The idea here is to write some slightly more restrictive upsert/deletion api that could be executed from CRDs reconciled by the deployment operator to install new vclusters, also tracks parentage of the cluster so we can viz it in the UI properly.
n/a
> Virtual Cluster APIs

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/clusters.ex
- lib/console/graphql/deployments/stack.ex
- lib/kube/client.ex
- lib/kube/client/base.ex
- schema/schema.graphql
We periodically fetch these to expose metrics data, we should bound these to support larger cluster sizes properly.
n/a
> Limit cluster node and node metrics fetches

- charts/console-rapid/Chart.yaml
- charts/console/templates/deployment.yaml
apparently it's `--token-file=...` instead of space separated
n/a
> wrong format for file arg

- lib/console/deployments/clusters.ex
- lib/console/schema/cluster.ex
- lib/console/services/base.ex
- lib/console/watchers/upgrade.ex
- test/console/deployments/clusters_test.exs
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
* didn't register a deploy operator service in the cluster by default
* handle binding merge properly
n/a
> Fix minor virtual cluster bugs

- Dockerfile
- README.md
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/clusters.ex
- lib/console/deployments/pr/config.ex
- lib/console/graphql/configuration.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster.ex
- lib/console/schema/upgrade_insight.ex
- lib/console/schema/upgrade_insight_detail.ex
- priv/repo/migrations/20240828200406_add_upgrade_insights.exs
- schema/schema.graphql
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
- test/console/graphql/queries/deployments/cluster_queries_test.exs
Adds a `saveUpgradeInsights` mutation, and sideloads for upgradeInsights on the cluster object. This should be sufficient enough for the console server to integrate with EKS et al upgrade insights apis.
unit test
> Upgrade insight CRUD

- lib/console/graphql/deployments/notification.ex
This was causing errors in the crd reconciliation for notif syncs, should fix
n/a
> Fix unloaded notif bindings on sinks

- assets/src/components/login/Login.tsx
this was likely causing unnecessary logouts, and we don't necessarily need a logout when LoginError is rendered
> reduce unnecessary log outs

- lib/console/deployments/pr/validation.ex
- test/console/deployments/git_test.exs
We were passing those for string types even though it's prob invalid.  Rejecting them here.
unit test
> Handle empty strings in string pr automation context

- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/Navigation.tsx
also fixes a bug where it would incorrectly display "no clusters found" when a project that doesn't contain the mgmt cluster is selected
> persist last viewed cluster id in k8s dashboard

- assets/src/components/pr/automations/prConfigurationUtils.tsx
- assets/src/components/settings/global/GlobalSettingsSMTP.tsx
smtp and pr automation forms were both having issues capturing toggle values (smtp form wasn't actually setting the default to "false" so it would register undefined if there was no toggle, and conversely pr automation form was treating false as undefined)
> fix form toggles

- assets/src/components/settings/usermanagement/personas/PersonaActions.tsx
- assets/src/components/settings/usermanagement/personas/PersonasList.tsx
Personas list was not being displayed correctly on Safari. No matter how many items were on it, it had 1px height (basically just a border). This pull request updates it to use table component.
I tested creating and updating persona objects with manager and security roles but found no issues with it. Looks like this issue is already solved.
> fix: Fix personas view

- lib/console/schema/notification_router.ex
We introduced this notification event, but you currently can't create routers that filter on it.
regression
> Add `stack.run` to event list

- go/controller/internal/controller/prautomation_attributes.go
- go/controller/internal/controller/prautomation_controller.go
- go/controller/internal/controller/prautomation_controller_test.go
pr automation CRD doesn't requeue effectively when waiting for referenced objects
> requeue when referenced object is not found

- lib/console/deployments/observability.ex
- lib/prometheus/client.ex
Might help w/ prometheus troubleshooting
n/a
> Log prometheus queries

- assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
- assets/src/components/cd/clusters/UpgradeInsights.tsx
> fix: Minor bug fixes on detected by cloud deprecations

- lib/console/deployments/clusters.ex
Looks like EKS is really pessimistic with their statuses, think we can say things are upgradeable if not failed.
existing
> Only fail upgrade insights on `:failed` statuses

- assets/src/components/sharesecret/ConsumeSecret.tsx
- assets/src/components/sharesecret/ShareSecretModal.tsx
makes it so the user has to explicitly click "consume secret" instead of consuming on render, which seemed to be causing some issues
also fixes a bug that was causing new secrets to generate every time the URL copy button was clicked
> fix secret sharing bugs

- assets/src/components/component/ComponentMetrics.tsx
- assets/src/utils/prometheus.ts
- Updated component-level metric units
- CPU metrics are now adjusted to the millicores base unit (1000 m == 1 core)
- Memory metrics are now adjusted to the power of 2 base (1024 bytes == 1 KiB)
Locally
> feat: use cores/bytes as the base unit for component-level metrics

- Makefile
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/ai/fixer/parent.ex
- lib/console/ai/fixer/service.ex
- lib/console/ai/fixer/stack.ex
- lib/console/deployments/clusters.ex
- lib/console/graphql/ai.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/schema/ai_insight.ex
- lib/console/schema/cluster.ex
- lib/console/schema/cluster_insight_component.ex
- priv/repo/migrations/20241024163504_cluster_insight_components.exs
- schema/schema.graphql
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
- test/console/graphql/queries/ai_queries_test.exs
the idea is the agent will periodically gather these and provide them in cluster ping mutations
unit test
> Add apis to persist insight components at cluster level

- config/prod.exs
- lib/console/deployments/pipelines.ex
- test/console/deployments/pipelines_test.exs
We were using the wrong timestamp comparison to determine if gates are stale
unit test
> Fix pipeline gate logic

- test/console/graphql/queries/deployments/git_queries_test.exs
One of the helm tests made the wrong assumptions about the console helm repository, broken by the new ai-proxy chart added.  This will be more robust going forward.
fix test
> Fix brittle helm repo test

- assets/src/components/ai/AI.tsx
- assets/src/components/ai/chatbot/Chatbot.tsx
Also controls chatbot rendering based on whether ai has been enabled for a given console.
This looks like the only major gap to fill before releasing, will try to do that this weekend.
local
> Provide basic empty state for ai tab

- assets/src/components/kubernetes/cluster/Namespace.tsx
- assets/src/components/kubernetes/cluster/Node.tsx
- assets/src/components/kubernetes/common/ResourceDetails.tsx
- assets/src/components/kubernetes/configuration/ConfigMap.tsx
- assets/src/components/kubernetes/customresources/CustomResource.tsx
- assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
- assets/src/components/kubernetes/network/Ingress.tsx
- assets/src/components/kubernetes/network/IngressClass.tsx
- assets/src/components/kubernetes/network/NetworkPolicy.tsx
- assets/src/components/kubernetes/network/Service.tsx
- assets/src/components/kubernetes/rbac/ClusterRole.tsx
- assets/src/components/kubernetes/rbac/ClusterRoleBinding.tsx
- assets/src/components/kubernetes/rbac/Role.tsx
- assets/src/components/kubernetes/rbac/RoleBinding.tsx
- assets/src/components/kubernetes/rbac/ServiceAccount.tsx
- assets/src/components/kubernetes/storage/PersistentVolume.tsx
- assets/src/components/kubernetes/storage/PersistentVolumeClaim.tsx
- assets/src/components/kubernetes/storage/StorageClass.tsx
- assets/src/components/kubernetes/workloads/CronJob.tsx
- assets/src/components/kubernetes/workloads/DaemonSet.tsx
- assets/src/components/kubernetes/workloads/Deployment.tsx
- assets/src/components/kubernetes/workloads/Job.tsx
- assets/src/components/kubernetes/workloads/Pod.tsx
- assets/src/components/kubernetes/workloads/ReplicaSet.tsx
- assets/src/components/kubernetes/workloads/ReplicationController.tsx
- assets/src/components/kubernetes/workloads/StatefulSet.tsx
In Kubernetes Dashboard API raw objects are not part of resource details. To fetch raw objects we are using separate query. Because of that we can reduce number of `useExplainWithAI` calls to just two. One for CD components and one for all Kubernetes resource details.
> enhancement: pass raw kubernetes object to explain w/ ai prompt

- assets/src/components/cd/services/ClusterTagsFilter.tsx
> fix: /cd/clusters page prefetches tags even if tag selector isn't interacted w/

- assets/package.json
- assets/src/components/ai/chatbot/ChatMessage.tsx
- assets/src/components/ai/chatbot/ChatbotHeader.tsx
- assets/src/components/ai/chatbot/ChatbotPanelInsight.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
- assets/src/components/hooks/useCanScroll.ts
- assets/yarn.lock
changes progress bar to use this effect instead:
replaces thread scroll bar with top and bottom gradient effects
replaces the form textarea with a more flexible editor pattern, makes styling more possible among other things
> ai chat thread improvements

- assets/package.json
- assets/src/components/ai/AITable.tsx
- assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
- assets/src/components/home/deployments/DeploymentsTable.tsx
- assets/src/components/home/pullrequests/PrTable.tsx
- assets/src/components/home/violations/ConstraintViolationsCard.tsx
- assets/src/components/kubernetes/common/ResourceList.tsx
- assets/src/components/policies/PoliciesTable.tsx
- assets/yarn.lock
> enhancement: Tables improvements

- charts/console/Chart.yaml
- charts/console/values.yaml
Some cloud provider default nodes/node pools could not schedule the dashboard API due to high resource requests/limits. With caching enabled by default we can lower them.
> fix: decrease dashboard api resource requests/limits

- .github/workflows/controller-ci.yaml
- go/controller/api/v1alpha1/prautomation_types.go
> feat: CRD docs check

- assets/src/components/cd/cluster/Cluster.tsx
- assets/src/components/utils/ButtonGroup.tsx
- assets/src/generated/graphql-kubernetes.ts
- assets/src/generated/graphql-plural.ts
- assets/src/generated/graphql.ts
simplified the component a bit and fixed to align with design spec
also adds sparkle icon to cluster insights
> improve tree/table switch

- assets/src/components/cost-management/CostManagement.tsx
- assets/src/components/cost-management/details/CostManagementDetails.tsx
- assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
was too crammed on smaller screens before
> make cost management tables bigger and allow y scroll

- assets/src/components/kubernetes/rbac/Rbac.tsx
- assets/src/components/pr/automations/CreatePrModal.tsx
- assets/src/components/utils/KickButton.tsx
> fix: UI tweaks

- assets/src/components/cost-management/ClusterUsagesTableCols.tsx
- assets/src/components/cost-management/CostManagement.tsx
- assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/costManagement.graphql
- config/prod.exs
- go/client/models_gen.go
- lib/console/cost/cron.ex
- lib/console/cost/ingester.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster_namespace_usage.ex
- lib/console/schema/cluster_usage_history.ex
- priv/repo/migrations/20241220191210_add_storage_cost.exs
- priv/repo/migrations/20241220202012_cluster_usage_history.exs
- schema/schema.graphql
- test/console/cost/cron_test.exs
- test/console/graphql/queries/deployments/cluster_queries_test.exs
- test/support/factory.ex
* Add more of the cost dimensions to our graphs
> Final pre-release touches

- go/controller/internal/controller/infrastructurestack_controller.go
- go/controller/internal/controller/servicedeployment_controller.go
- Set condition `repository is not healthy` instead of just logging it for both stacks and services
- Set requeue time for services when referenced repo was not found (stacks already have it set)
> fix: Backoff issues for stacks and services

- assets/src/components/ai/AI.tsx
- assets/src/components/ai/InsightDisplay.tsx
- assets/src/components/contexts/DeploymentSettingsContext.tsx
- assets/src/components/home/AiThreads.tsx
- show spinner/loading indicator while loading deployment settings (previously it was defaulting to disabled view)
- fix empty state handling on AI view
> enhancement: AI empty state improvements

- assets/package.json
- assets/src/components/ai/chatbot/ChatMessage.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
- assets/src/components/ai/chatbot/useCurrentPageChatContext.tsx
- assets/src/components/contexts/NavigationContext.tsx
- assets/src/components/pr/scm/EditScmConnection.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/ai.graphql
- assets/yarn.lock
adds page context and create PR actions to chat
> add new actions to ai chat

- go/controller/config/samples/deployments_v1alpha1_generatedsecret.yaml
- go/controller/internal/controller/generatedsecret_controller.go
Initially, I assumed the secrets would be created in the same namespace as CRD.
I can't use a controller reference to monitor dependent secrets because secrets can be created in a different namespace than the GeneratedSecret CRD object (cross-namespace references error). I had to use another approach, `EnqueueRequestsFromMapFunc,` to watch newly created secrets. Secrets and CRD object are connected via annotation.
> fix: GeneratedSecret reconciler

- assets/src/generated/graphql.ts
- go/client/client.go
- go/client/models_gen.go
- lib/console/deployments/stacks.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/guardian.ex
- lib/console/schema/cluster_registration.ex
- lib/console/schema/stack.ex
- priv/repo/migrations/20250120165507_add_machine_id_uniq_constraint.exs
- schema/schema.graphql
- test/console/deployments/clusters_test.exs
- test/console/deployments/stacks_test.exs
This will make it impossible to exfil the token after the run (eg via terraform outputs)
unit tests
> Tie stack jwts to the lifecycle of a stack run

- go/controller/api/v1alpha1/prautomation_types.go
During tests, I noticed this issue. 
Raw is the underlying serialization of this object.
> fix: prautomation type

- assets/src/components/edge/CompleteClusterRegistrationModal.tsx
Added a predefined tag to edge clusters to be able to easily target edge/non-edge clusters.
Locally
> feat: add default plural=edge tag when registering edge devices

- assets/src/generated/graphql.ts
- go/client/models_gen.go
- lib/console/deployments/clusters.ex
- lib/console/deployments/policies/bootstrap_policies.ex
- lib/console/deployments/policies/rbac.ex
- lib/console/graphql/deployments/cluster.ex
- lib/console/graphql/resolvers/deployments/cluster.ex
- lib/console/schema/cluster_iso_image.ex
- priv/repo/migrations/20250128165205_add_cluster_isos.exs
- schema/schema.graphql
- test/console/deployments/clusters_test.exs
- test/console/graphql/mutations/deployments/cluster_mutations_test.exs
- test/console/graphql/queries/deployments/cluster_queries_test.exs
- test/support/factory.ex
This supports basic crud to persist cluster isos and authz reads of existing ISO's stored in OCI. At the moment using project writer access to govern that.
unit tests
> Add Cluster ISO Image CRUD gql

- assets/src/components/cd/logs/LogsCard.tsx
- assets/src/components/cd/logs/LogsTable.tsx
- assets/src/components/cost-management/CostManagement.tsx
- assets/src/components/cost-management/details/CostManagementDetails.tsx
- assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
- assets/src/components/cost-management/details/CostManagementDetailsOverview.tsx
- assets/src/components/cost-management/details/CostManagementDetailsRecommendations.tsx
- assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
fixes a bug that was causing cost management details view to crash if there was no data for the time series graph
adds breadcrumbs to cost management views
changes log views to toggle live state off when the user scrolls down, and back on when scrolled to the top (also triggers when "back to top" is clicked)
> small tweaks/fixes

- go/controller/internal/controller/bootstraptoken_controller.go
- go/controller/internal/controller/catalog_controller.go
- go/controller/internal/controller/project_controller.go
This fixes an issue with project/catalog CRDs that already exist in the API not being marked correctly as readonly.
`isAlreadyExist` check did not take into account the `readonly` status flag and during the subsequent reconcile
it was flipping the original `readonly: true` to `readonly: false` because project did exist in the API and ID was already synchronized.
Due to this i.e. deleting `readonly` default project was trying to delete the actual project from the API thus blocking CRD deletion and further service deployment cleanup.
Running controller locally on dev env
> fix: broken readonly feature in project and catalog controllers

- assets/src/components/kubernetes/Navigation.tsx
- assets/src/components/kubernetes/audit/Audit.tsx
- assets/src/components/kubernetes/common/DataSelect.tsx
- assets/src/generated/graphql.ts
- assets/src/graph/kubernetes.graphql
- assets/src/routes/kubernetesRoute.tsx
- assets/src/routes/kubernetesRoutesConsts.tsx
Added audit logs table view to kubernetes dashboard.
Locally w/ dev env
> feat: add cluster audit logs view to kubernetes dashboard

- lib/console/deployments/cron.ex
- lib/console/services/users.ex
Going to see if restricting cache warms a bit more helps, also adding support for adgroups claim by default
Fixes PROD-3236
n/a
> Minor additional scaling tweaks

- go/controller/api/v1alpha1/cluster_types.go
- go/controller/internal/controller/cluster_controller.go
- go/controller/internal/controller/cluster_controller_test.go
Cluster bindings should be added when in a read-only state
> feat: update cluster bindings in read-only mode

- .github/workflows/publish.yaml
- .github/workflows/softserve-cd.yaml
- charts/console/templates/softserve.yaml
- charts/console/values.yaml
- softserve/Dockerfile.softserve
- softserve/softserve_setup.sh
set up softserve git server (https://github.com/charmbracelet/soft-serve) to host the deployment-operator and scaffolds repos such that if the user desires, they don't have to connect to github.
https://linear.app/pluralsh/issue/PROD-3247/implement-self-hostability-for-core-plural-deployment-operator-and
In `softserve-cd.yaml`, initially had it set to `push` instead of `pull_request` - passing wf: https://github.com/pluralsh/console/actions/runs/13704813366
image publish on ghcr: https://github.com/pluralsh/console/pkgs/container/softserve
> Softserve setup

- dockerfiles/Dockerfile.softserve
softserve dockerfile bigfix - install git before running server
from the `dockerfiles` directory:
to build and run container
```
docker build -t git-server -f Dockerfile.softserve .`
docker run -d -p 23231:23231 -p 23232:23232 --name git-server git-server
```
then should be able to clone:
git:
```
git clone git clone http://localhost:23232/deployment-operator.git
```
ssh:
```
git clone ssh://localhost:23231/deployment-operator.git
```
also, can verify that the repos are hosted in the `git-server` by running
```
ssh -p 23231 localhost
```
which should open up the TUI and show the `deployment-operator` and `scaffolds` repos.
> Softserve Fix

- lib/console/ai/evidence/alert.ex
- lib/console/ai/evidence/vector.ex
- lib/console/ai/pubsub/vector/consumer.ex
- lib/console/ai/pubsub/vector/protocol.ex
- lib/console/ai/pubsub/vector/types.ex
- lib/console/ai/vector/elastic.ex
- lib/console/ai/vector_store.ex
- lib/console/deployments/pr/dispatcher.ex
- lib/console/deployments/pr/file.ex
- lib/console/deployments/pr/impl/github.ex
- test/console/ai/cron_test.exs
- test/console/ai/pubsub/vector/consumer_test.exs
This should improve the overall data governance around this feature, since indexing by flow limits the search scope to just prs that are chosen to be viewable from the given service
unit tests
> Add flow id filtering for pr vector search

- go/controller/internal/controller/globalservice_controller.go
reconciler recreates the global service if deleted in from the API
> fix: recreate global service

- assets/eslint.config.mjs
- assets/package.json
- assets/src/components/ai/chatbot/ChatbotPanelEvidence.tsx
- assets/src/components/ai/chatbot/ChatbotPanelInsight.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/ai/insights/LogsEvidencePanel.tsx
- assets/yarn.lock
only shows evidence info below the original insight in the chat
fixes bug that was showing the evidence header in chat even with empty evidence array
also adds eslint warnings so we can start improving react compiler compatibility
> fix chat evidence bugs

- assets/src/generated/graphql.ts
- config/config.exs
- go/client/models_gen.go
- lib/console/cost/pr.ex
- lib/console/deployments/oauth.ex
- lib/console/graphql.ex
- lib/console/graphql/deployments/oauth.ex
- lib/console/graphql/oidc.ex
- lib/console/graphql/resolvers/oauth.ex
- lib/console/policies/oidc.ex
- lib/console/schema/oidc_provider.ex
- lib/console/services/oidc.ex
- lib/console/services/oidc/hydra.ex
- priv/repo/migrations/20250408160809_add_oidc_schemas.exs
- rel/runtime.exs
- schema/schema.graphql
- test/console/graphql/mutations/oauth_mutations_test.exs
- test/console/graphql/queries/oauth_queries_test.exs
- test/console/services/oidc_test.exs
- test/support/factory.ex
This mostly copies in Plural's hydra oidc client integration into the console repo.  This will allow the console itself to be auth providers for a variety of apps which will help enterprise/fully self-hosted usecases.
unit test
> Enable Hydra integration

- lib/console/deployments/pr/impl/bitbucket.ex
- lib/console/deployments/pr/impl/gitlab.ex
- test/console/ai/pubsub/vector/consumer_test.exs
Implement files function in gitlab and bitbucket providers such that they provide files in the same format as the github provider.
- Unit tests added in the `consumer_test.exs` test file for the gitlab and bitbucket providers
- `mix test test/console/ai/pubsub/vector/consumer_test.exs`
- Not included in the PR, but sandbox tested using mix tasks (i.e. essentially copy over the implementation code for the `files` function into a mix task and then run it with the URL of an actual PR)
> provider impl

- go/controller/internal/controller/servicedeployment_controller.go
- go/controller/internal/utils/kubernetes.go
Apply an annotation to the imported InfrastructureStack containing the service's namespace and name. This enables the service controller to reconcile whenever the stack is modified.
> fix: don't set owner references on InfrastructureStack

- charts/console/values.yaml
- dockerfiles/Dockerfile.softserve
Run soft-serve server as non-root (https://linear.app/pluralsh/issue/PROD-3414/git-server-ideally-shouldnt-run-as-root)
Make sure that UID is set for our non-root user so that the value can be set in the console helm chart
spun up container (docker build and docker run), verified that i could still clone repos from it.
> Use non root user for server process

- assets/src/components/kubernetes/common/DeleteResource.tsx
- assets/src/components/kubernetes/common/ResourceList.tsx
- assets/src/components/kubernetes/common/utils.tsx
- assets/src/components/utils/Confirm.tsx
Added deletion confirmation safeguards to both CRD and CRD object lists.
Locally w/ plrl-dev-aws
> feat: add input-based confirmation to CRD delete dialog

- config/test.exs
- lib/console/deployments/observability/webhook.ex
- lib/console/deployments/observability/webhook/newrelic.ex
- lib/console_web/controllers/webhook_controller.ex
- test/console_web/controllers/webhook_controller_test.exs
Implement newrelic webhook payload handling. Newrelic webhooks are not guaranteed to have any specific format in terms of the K-V pairs in the JSON. However:
- we can scan for the `plrl_cluster`, `plrl_service`, and `plrl_project` in the raw json text
- we can try and extract certain values from the default payload structure (and use a fillter value if not found)
Unit test + will functional test after merge
> newrelic impl

- assets/src/components/ai/chatbot/ChatbotPanelExamplePrompts.tsx
- Wrap chip to the length of text
- Make click outside close example prompts
> feat: Example prompts improvements

- lib/console/ai/chat/engine.ex
- lib/console/ai/tools/alerts.ex
- lib/console/schema/alert.ex
- priv/tools/alerts.json
- test/console/ai/chat_test.exs
Implement tool to fetch Alerts for AI chat. Allow filtering by type (newrelic, pagerduty, etc), severity (critical, low, etc), and state (firing, resolved).
Also minor modification to `Alert.for_flow` where we add the `distinct: true` condition to make sure we do not get duplicates.
Unit test
> AI Chat Tool for Alerts

- assets/package.json
- assets/src/components/cd/logs/Logs.tsx
- assets/src/components/kubernetes/common/Raw.tsx
- assets/src/components/kubernetes/common/create/secret/SecretModal.tsx
- assets/src/components/kubernetes/customresources/PinnedCustomResourceDefinitions.tsx
- assets/src/components/kubernetes/workloads/CronJob.tsx
- assets/src/components/utils/Confirm.tsx
- assets/yarn.lock
it's not exactly clear what triggers this bug, but it seems like it likely stems from a race condition when "live" is rapidly toggled while the search query is changing (this is expected behavior because changing query filters in most cases will return the scroll to the top, and then the user might immediately scroll down, but "stopPolling" might not necessarily get triggered)
this change simplifies the logic a bit and makes it more declarative
also bumps apollo client minor vsn
> fix logs polling bug

- assets/src/components/stacks/overview/StackConfiguration.tsx
It looks like `version` is no longer required attribute.
> fix: Allow resetting version

- assets/src/components/cd/services/ServiceSelector.tsx
- assets/src/components/cd/services/ServiceSettings.tsx
- assets/src/components/cd/services/deployModal/DeployService.tsx
- assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
- assets/src/components/cd/services/service/ServiceDetails.tsx
- assets/src/components/cd/services/service/settings/ServiceHelmSettings.tsx
- assets/src/components/security/Security.tsx
- adds a url input to helm chart settings edit forms if one already exists (and also includes the input by default when initially creating a service deployment)
- replaces the chart and version dropdowns with standard text inputs
- tweaks the service details selector to better prepopulate with cached data, so it won't always appear blank initially while fetching the service (closes PROD-3584)
- makes security page subtabs tab-accessible (closes PROD-3472)
> update helm chart forms and small fixes

- go/datastore/Makefile
- go/datastore/api/v1alpha1/elasticsearchindextemplate_types.go
- go/datastore/config/samples/all.yaml
- go/datastore/config/samples/dbs_v1alpha1_elasticsearchilmpolicy.yaml
- go/datastore/internal/controller/common.go
- go/datastore/internal/controller/elasticsearchcredentials_controller.go
- go/datastore/internal/controller/elasticsearchilmpolicy_controller.go
- go/datastore/internal/controller/elasticsearchindextemplate_controller.go
- go/datastore/internal/controller/elasticsearchuser_controller.go
This PR fixes datastore resource deletion. All the resources depend on ElasticsearchCredentials. They must be deleted properly.
- fix reconcile ElasticsearchIndexTemplate (the name was overwritten)
> fix: datastore resource deletion 

- go/controller/config/samples/project.yaml
- go/controller/internal/client/console.go
- go/controller/internal/client/project.go
- go/controller/internal/controller/project_controller.go
- go/controller/internal/controller/project_controller_test.go
- go/controller/internal/test/mocks/ConsoleClient_mock.go
It brings two improvements:
- finalizer will not be applied to read-only projects (this probably should be replicated for all other resources)
- projects ID is used to check if exists instead of its name (deletion is based on ID)
> fix: Project deletion improvements

- go/datastore/internal/client/postgres/client.go
Change SetDatabaseOwner to grant all privileges
> fix: update SetDatabaseOwner for postgres

- go/controller/api/v1alpha1/oidcprovider_types.go
- go/controller/api/v1alpha1/previewenvironmenttemplate_types.go
- go/controller/api/v1alpha1/servicecontext_types.go
- go/controller/internal/controller/previewenvironmenttemplate_controller.go
- go/controller/internal/controller/servicecontext_controller.go
Specifying GetName() for the controller overrides the ObjectMeta.Name defined in the CRD.
> fix: name override in controllers

- lib/console/ai/evidence/base.ex
- lib/console/ai/evidence/component/persistent_volume_claim.ex
- lib/console/ai/evidence/component/resource.ex
- lib/console/ai/evidence/component/stateful_set.ex
- lib/console/ai/evidence/context.ex
- lib/console/ai/evidence/logs.ex
- test/console/ai/cron_test.exs
- test/console/graphql/queries/kubernetes_queries_test.exs
- test/support/kubernetes_scaffolds.ex
- test/test_helper.exs
Add PersistentVolume claims as AI evidence generated by the Cron job. The PVCs search CSI log drivers using provisioner and component name as filters.
The PVC module is also integrated into StatefulSet so that PersistentVolume data, if available, is added to the evidence for StatefulSet failures.
Added unit test that makes sure to check evidence string content.
Unit test
> PersistentVolume Evidence Module for AI

- .github/workflows/chart.yaml
Added a step to first pull the target version from OCI before trying to push it. Tested it on a separate repo for a public image.
Test repo: https://github.com/floreks/actions/actions/workflows/oci-test.yaml.yml
> feat(chart): add check for existing chart version before OCI push

- assets/package.json
- assets/src/components/ai/AIContext.tsx
- assets/src/components/ai/chatbot/ChatbotHeader.tsx
- assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
- assets/src/components/ai/chatbot/ChatbotThreadMoreMenu.tsx
- assets/src/components/ai/chatbot/input/ChatInput.tsx
- assets/src/components/commandpalette/CommandPalette.tsx
- assets/src/components/commandpalette/CommandPaletteContext.tsx
- assets/src/components/commandpalette/CommandPaletteDialog.tsx
- assets/src/components/commandpalette/CommandPaletteLauncher.tsx
- assets/src/components/commandpalette/commands.ts
- assets/src/components/stacks/state/StackStateGraph.tsx
- assets/src/components/utils/EditableDiv.tsx
- assets/src/components/utils/SkeletonLoaders.tsx
- assets/yarn.lock
had some ui quirks and doesn't really play nice with the cmdk library, plus we probably don't need to virtualize here because it takes a ton of threads (500+) to really have perf effects. if it becomes a problem we can also use VList under the hood which should be more reliable
also:
* more cleanly separates the logic for AI vs Command views to fix some bugs there (like inadvertently starting a new chat when hitting enter on command selection)
* adds the ability to queue a message for a specific thread, making it much more straightforward to send an initial message when a new thread is created (also allows us to remove auto thread creation entirely)
* updates search on stack state graphs to be much broader (closes PROD-3880)
> remove standard scroller from cmd k

- assets/src/components/ai/chatbot/ChatMessage.tsx
- assets/src/components/ai/chatbot/ChatMessageContent.tsx
was affecting cases when the agent injected a message with role User that had a code block in it
also removes the mostly unused "side" prop to help keep things consistent
> fix chat message width bug

- assets/src/components/login/Login.tsx
- assets/src/components/login/OauthCallback.tsx
- assets/src/helpers/refreshToken.ts
saves the current path and search query params if a user gets logged out inadvertently (generally just happens if they try to nav to a url directly before logging in), and then redirects back to it on login
> add return-to path support on login

- assets/package.json
- assets/src/components/ai/AIContext.tsx
- assets/src/components/help/HelpLauncherBtn.tsx
- assets/src/components/layout/Console.tsx
- assets/src/components/layout/Sidebar.tsx
- assets/src/components/utils/sidebar/SidebarItem.tsx
- assets/src/components/utils/sidebar/SidebarSection.tsx
- assets/yarn.lock
moves the sidebar component out of the DS, strips out the extra functionality we never use, makes it so that the expanded sidebar pushes content instead of overlaying, and makes the user's expansion choice persist in local storage (defaults closed,  and also automatically closes when the chatbot is opens so the main content isn't squeezed too much)
https://github.com/user-attachments/assets/a4c5df41-60e0-4011-948f-14b36faa2208
also bumps vulnerable apollo sandbox version
> make expanded sidebar persist

- go/client/utils.go
This PR fixes go-client error: `request failed: Post http2: request body larger than specified content length`
> fix: set Content-Length in  the new PersistedQueryInterceptor

- assets/README.md
- assets/src/components/kubernetes/Cluster.tsx
- assets/src/components/kubernetes/Navigation.tsx
- assets/src/components/kubernetes/audit/Audit.tsx
- assets/src/components/kubernetes/common/DataSelect.tsx
- assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
- assets/src/components/kubernetes/customresources/PinnedCustomResourceDefinitions.tsx
- assets/waitOnConfig.json
having to keep context, state, and search queries all in sync was making this unnecessarily brittle (and breaking the namespace selector on custom resource lists)
also fixes a couple styling bugs
> fix k8s dashboard filter logic
